"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.completely_traded_entry import (
    CompletelyTradedEntry,
)
from goeapi.models.draft_entry import DraftEntry
from goeapi.models.final_proposal_entry import (
    FinalProposalEntry,
)
from goeapi.models.partially_traded_entry import (
    PartiallyTradedEntry,
)
from goeapi.models.test_entry import TestEntry


class AdvicePayload(object):
    """Implementation of the 'AdvicePayload' model.

    Attributes:
        completely_traded (List[CompletelyTradedEntry]): Provides a list of Advice
            IDs and the corresponding timestamp of all API responses that have been
            fully traded,             where the entire portfolio recommendation was
            implemented.
        partially_traded (List[PartiallyTradedEntry]): Provides a list of Advice IDs
            and the corresponding timestamp of all API responses that have been
            partially traded.
        final_proposal (List[FinalProposalEntry]): Provides a list of Advice IDs and
            the corresponding timestamp of all API responses that have been approved,
            but not yet traded.
        draft (List[DraftEntry]): Provides a list of Advice IDs of all API responses
            that have not been approved or traded.
        test (List[TestEntry]): Provides a list of Advice IDs and the corresponding
            timestamp of all API responses that have been used with test data.
            Advice IDs provided in this list were not used in real world situations,
            purely for testing purposes.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "completely_traded": "CompletelyTraded",
        "partially_traded": "PartiallyTraded",
        "final_proposal": "FinalProposal",
        "draft": "Draft",
        "test": "Test",
    }

    _optionals = [
        "completely_traded",
        "partially_traded",
        "final_proposal",
        "draft",
        "test",
    ]

    def __init__(
        self,
        completely_traded=APIHelper.SKIP,
        partially_traded=APIHelper.SKIP,
        final_proposal=APIHelper.SKIP,
        draft=APIHelper.SKIP,
        test=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AdvicePayload instance."""
        # Initialize members of the class
        if completely_traded is not APIHelper.SKIP:
            self.completely_traded = completely_traded
        if partially_traded is not APIHelper.SKIP:
            self.partially_traded = partially_traded
        if final_proposal is not APIHelper.SKIP:
            self.final_proposal = final_proposal
        if draft is not APIHelper.SKIP:
            self.draft = draft
        if test is not APIHelper.SKIP:
            self.test = test

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        completely_traded = None
        if dictionary.get("CompletelyTraded") is not None:
            completely_traded = [
                CompletelyTradedEntry.from_dictionary(x)
                    for x in dictionary.get("CompletelyTraded")
            ]
        else:
            completely_traded = APIHelper.SKIP
        partially_traded = None
        if dictionary.get("PartiallyTraded") is not None:
            partially_traded = [
                PartiallyTradedEntry.from_dictionary(x)
                    for x in dictionary.get("PartiallyTraded")
            ]
        else:
            partially_traded = APIHelper.SKIP
        final_proposal = None
        if dictionary.get("FinalProposal") is not None:
            final_proposal = [
                FinalProposalEntry.from_dictionary(x)
                    for x in dictionary.get("FinalProposal")
            ]
        else:
            final_proposal = APIHelper.SKIP
        draft = None
        if dictionary.get("Draft") is not None:
            draft = [
                DraftEntry.from_dictionary(x)
                    for x in dictionary.get("Draft")
            ]
        else:
            draft = APIHelper.SKIP
        test = None
        if dictionary.get("Test") is not None:
            test = [
                TestEntry.from_dictionary(x)
                    for x in dictionary.get("Test")
            ]
        else:
            test = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(completely_traded,
                   partially_traded,
                   final_proposal,
                   draft,
                   test,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _completely_traded=(
            self.completely_traded
            if hasattr(self, "completely_traded")
            else None
        )
        _partially_traded=(
            self.partially_traded
            if hasattr(self, "partially_traded")
            else None
        )
        _final_proposal=(
            self.final_proposal
            if hasattr(self, "final_proposal")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _test=(
            self.test
            if hasattr(self, "test")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completely_traded={_completely_traded!r}, "
            f"partially_traded={_partially_traded!r}, "
            f"final_proposal={_final_proposal!r}, "
            f"draft={_draft!r}, "
            f"test={_test!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _completely_traded=(
            self.completely_traded
            if hasattr(self, "completely_traded")
            else None
        )
        _partially_traded=(
            self.partially_traded
            if hasattr(self, "partially_traded")
            else None
        )
        _final_proposal=(
            self.final_proposal
            if hasattr(self, "final_proposal")
            else None
        )
        _draft=(
            self.draft
            if hasattr(self, "draft")
            else None
        )
        _test=(
            self.test
            if hasattr(self, "test")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completely_traded={_completely_traded!s}, "
            f"partially_traded={_partially_traded!s}, "
            f"final_proposal={_final_proposal!s}, "
            f"draft={_draft!s}, "
            f"test={_test!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
