"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class AdviceLookupRequest(object):
    """Implementation of the 'AdviceLookupRequest' model.

    Attributes:
        advice_id (str): The system-generated unique identifier for a historical API
            request. Supplying this value retrieves the details of the corresponding
            advice interaction, including the request payload, response, user email,
            API endpoint, and timestamp.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "advice_id": "adviceId",
    }

    def __init__(
        self,
        advice_id=None,
        additional_properties=None):
        """Initialize a AdviceLookupRequest instance."""
        # Initialize members of the class
        self.advice_id = advice_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        advice_id =\
            dictionary.get("adviceId")\
            if dictionary.get("adviceId")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(advice_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _advice_id=self.advice_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"advice_id={_advice_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _advice_id=self.advice_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"advice_id={_advice_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
