"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class AssetsHeldAwayInfo(object):
    """Implementation of the '_assetsHeldAwayInfo' model.

    Attributes:
        name (str): All objects should have Unique names
        expected_date_of_liquidity (str): Future date when this asset will convert
            into assets available for GOE advice
        expected_value_at_liquidity (float): Value expected at liquidation date
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "expected_date_of_liquidity": "expectedDateOfLiquidity",
        "expected_value_at_liquidity": "expectedValueAtLiquidity",
    }

    def __init__(
        self,
        name=None,
        expected_date_of_liquidity=None,
        expected_value_at_liquidity=None,
        additional_properties=None):
        """Initialize a AssetsHeldAwayInfo instance."""
        # Initialize members of the class
        self.name = name
        self.expected_date_of_liquidity = expected_date_of_liquidity
        self.expected_value_at_liquidity = expected_value_at_liquidity

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        expected_date_of_liquidity =\
            dictionary.get("expectedDateOfLiquidity")\
            if dictionary.get("expectedDateOfLiquidity")\
                else None
        expected_value_at_liquidity =\
            dictionary.get("expectedValueAtLiquidity")\
            if dictionary.get("expectedValueAtLiquidity")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   expected_date_of_liquidity,
                   expected_value_at_liquidity,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _expected_date_of_liquidity=self.expected_date_of_liquidity
        _expected_value_at_liquidity=self.expected_value_at_liquidity
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"expected_date_of_liquidity={_expected_date_of_liquidity!r}, "
            f"expected_value_at_liquidity={_expected_value_at_liquidity!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _expected_date_of_liquidity=self.expected_date_of_liquidity
        _expected_value_at_liquidity=self.expected_value_at_liquidity
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"expected_date_of_liquidity={_expected_date_of_liquidity!s}, "
            f"expected_value_at_liquidity={_expected_value_at_liquidity!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
