"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class BulkUpsertAdvice(object):
    """Implementation of the 'BulkUpsertAdvice' model.

    Attributes:
        status (str): Provides the status of the response.
        updated (List[str]): Provides a list of Advice IDs that were successfully
            passed.
        failed (List[str]): Provides a list of Advice IDs that were not passed.
        invalid_ids (List[str]): Provides a list of Advice IDs that are invalid, and
            not passed.
        total_processed (int): Provides a count of how many Advice IDs were passed.
        chunks_processed (int): Provides a count of how many Advice ID chunks were
            passed.
        message (str): Provides the response message.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "updated": "updated",
        "failed": "failed",
        "invalid_ids": "invalid_ids",
        "total_processed": "total_processed",
        "message": "message",
        "chunks_processed": "chunks_processed",
    }

    _optionals = [
        "chunks_processed",
    ]

    def __init__(
        self,
        status=None,
        updated=None,
        failed=None,
        invalid_ids=None,
        total_processed=None,
        message=None,
        chunks_processed=0,
        additional_properties=None):
        """Initialize a BulkUpsertAdvice instance."""
        # Initialize members of the class
        self.status = status
        self.updated = updated
        self.failed = failed
        self.invalid_ids = invalid_ids
        self.total_processed = total_processed
        self.chunks_processed = chunks_processed
        self.message = message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else None
        updated =\
            dictionary.get("updated")\
            if dictionary.get("updated")\
                else None
        failed =\
            dictionary.get("failed")\
            if dictionary.get("failed")\
                else None
        invalid_ids =\
            dictionary.get("invalid_ids")\
            if dictionary.get("invalid_ids")\
                else None
        total_processed =\
            dictionary.get("total_processed")\
            if dictionary.get("total_processed")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        chunks_processed =\
            dictionary.get("chunks_processed")\
            if dictionary.get("chunks_processed")\
                else 0

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   updated,
                   failed,
                   invalid_ids,
                   total_processed,
                   message,
                   chunks_processed,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status=self.status
        _updated=self.updated
        _failed=self.failed
        _invalid_ids=self.invalid_ids
        _total_processed=self.total_processed
        _chunks_processed=(
            self.chunks_processed
            if hasattr(self, "chunks_processed")
            else None
        )
        _message=self.message
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!r}, "
            f"updated={_updated!r}, "
            f"failed={_failed!r}, "
            f"invalid_ids={_invalid_ids!r}, "
            f"total_processed={_total_processed!r}, "
            f"chunks_processed={_chunks_processed!r}, "
            f"message={_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status=self.status
        _updated=self.updated
        _failed=self.failed
        _invalid_ids=self.invalid_ids
        _total_processed=self.total_processed
        _chunks_processed=(
            self.chunks_processed
            if hasattr(self, "chunks_processed")
            else None
        )
        _message=self.message
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status={_status!s}, "
            f"updated={_updated!s}, "
            f"failed={_failed!s}, "
            f"invalid_ids={_invalid_ids!s}, "
            f"total_processed={_total_processed!s}, "
            f"chunks_processed={_chunks_processed!s}, "
            f"message={_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
