"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.cashflow_object_type import (
    CashflowObjectType,
)


class CashFlowDict2(object):
    """Implementation of the 'CashFlowDict2' model.

    Attributes:
        mtype (CashflowObjectType): Mandatory if cashflow list if defined.
        amount (float): Mandatory if cashflow list if defined.
        start_date (str): Mandatory for all types if cashflow list if defined.
            Optional only when type is BEQUEST. Date in the format of "dd-mm-yyyy".
            For Bequest, if startDate and endDate are passed, they have to be same.
        end_date (str): Mandatory for "CONTRIBUTION". For the remaining four, it is
            optional. Date in the format of "dd-mm-yyyy". When not passed, the end
            date of parent object will be considered in the algo.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "amount": "amount",
        "start_date": "startDate",
        "end_date": "endDate",
    }

    _optionals = [
        "start_date",
        "end_date",
    ]

    def __init__(
        self,
        mtype=None,
        amount=None,
        start_date=APIHelper.SKIP,
        end_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CashFlowDict2 instance."""
        # Initialize members of the class
        self.mtype = mtype
        self.amount = amount
        if start_date is not APIHelper.SKIP:
            self.start_date = start_date
        if end_date is not APIHelper.SKIP:
            self.end_date = end_date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        start_date =\
            dictionary.get("startDate")\
            if dictionary.get("startDate")\
                else APIHelper.SKIP
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   amount,
                   start_date,
                   end_date,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.mtype,
                    type_callable=lambda value:
                        CashflowObjectType.validate(value)) \
                and APIHelper.is_valid_type(
                    value=dictionary.amount,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("type"),
                type_callable=lambda value:
                    CashflowObjectType.validate(value)) \
            and APIHelper.is_valid_type(
                value=dictionary.get("amount"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _amount=self.amount
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"amount={_amount!r}, "
            f"start_date={_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _amount=self.amount
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"amount={_amount!s}, "
            f"start_date={_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
