"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class CashFlowDict(object):
    """Implementation of the 'CashFlowDict' model.

    Attributes:
        mtype (str): The model property of type str.
        amount (float): The model property of type float.
        start_date (str): The model property of type str.
        end_date (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": "type",
        "amount": "amount",
        "start_date": "startDate",
        "end_date": "endDate",
    }

    _optionals = [
        "start_date",
        "end_date",
    ]

    def __init__(
        self,
        mtype=None,
        amount=None,
        start_date=APIHelper.SKIP,
        end_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CashFlowDict instance."""
        # Initialize members of the class
        self.mtype = mtype
        self.amount = amount
        if start_date is not APIHelper.SKIP:
            self.start_date = start_date
        if end_date is not APIHelper.SKIP:
            self.end_date = end_date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        start_date =\
            dictionary.get("startDate")\
            if dictionary.get("startDate")\
                else APIHelper.SKIP
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mtype,
                   amount,
                   start_date,
                   end_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mtype=self.mtype
        _amount=self.amount
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!r}, "
            f"amount={_amount!r}, "
            f"start_date={_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mtype=self.mtype
        _amount=self.amount
        _start_date=(
            self.start_date
            if hasattr(self, "start_date")
            else None
        )
        _end_date=(
            self.end_date
            if hasattr(self, "end_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mtype={_mtype!s}, "
            f"amount={_amount!s}, "
            f"start_date={_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
