"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class CashflowObjectType(object):
    """Implementation of the 'Cashflow object type' enum.

    Mandatory if cashflow list if defined.

    Attributes:
        CONTRIBUTION: The enum member of type str.
        GOAL: The enum member of type str.
        OTHER_INCOME: The enum member of type str.
        SOCIAL_SECURITY: The enum member of type str.
        BEQUEST: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    CONTRIBUTION = "CONTRIBUTION"

    GOAL = "GOAL"

    OTHER_INCOME = "OTHER_INCOME"

    SOCIAL_SECURITY = "SOCIAL_SECURITY"

    BEQUEST = "BEQUEST"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return bool(value)

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
