"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class Category(object):
    """Implementation of the 'Category' model.

    Attributes:
        category_name (str): Unique name assigned to an asset category in the
            portfolio
        category_id (str): Unique id assigned to an asset category in the portfolio
        category_price (float): Price of the security as on the date the request
            payload is generated.                         For “Cash”, the category
            Price is assumed to be 1 for the initial call.                         In
            case of multiple lots within the same category, the average price for the
            multiple lots is used.
        quantity (float): Number of units of the underlying fund <br>
            Note: <br>                    Amount in a security = categoryPrice x
            quantity
        cost_basis (float): The purchase price of the funds. In the case of multiple
            lots within the same category, the average cost price is used.
            This field is relevant for taxable accounts where gains are computed as
            following:<br>                    Capital Gains = Market Price - Cost
            Basis
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "category_name": "categoryName",
        "category_id": "categoryID",
        "category_price": "categoryPrice",
        "quantity": "quantity",
        "cost_basis": "costBasis",
    }

    def __init__(
        self,
        category_name=None,
        category_id=None,
        category_price=None,
        quantity=None,
        cost_basis=None,
        additional_properties=None):
        """Initialize a Category instance."""
        # Initialize members of the class
        self.category_name = category_name
        self.category_id = category_id
        self.category_price = category_price
        self.quantity = quantity
        self.cost_basis = cost_basis

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        category_name =\
            dictionary.get("categoryName")\
            if dictionary.get("categoryName")\
                else None
        category_id =\
            dictionary.get("categoryID")\
            if dictionary.get("categoryID")\
                else None
        category_price =\
            dictionary.get("categoryPrice")\
            if dictionary.get("categoryPrice")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        cost_basis =\
            dictionary.get("costBasis")\
            if dictionary.get("costBasis")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(category_name,
                   category_id,
                   category_price,
                   quantity,
                   cost_basis,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _category_name=self.category_name
        _category_id=self.category_id
        _category_price=self.category_price
        _quantity=self.quantity
        _cost_basis=self.cost_basis
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"category_name={_category_name!r}, "
            f"category_id={_category_id!r}, "
            f"category_price={_category_price!r}, "
            f"quantity={_quantity!r}, "
            f"cost_basis={_cost_basis!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _category_name=self.category_name
        _category_id=self.category_id
        _category_price=self.category_price
        _quantity=self.quantity
        _cost_basis=self.cost_basis
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"category_name={_category_name!s}, "
            f"category_id={_category_id!s}, "
            f"category_price={_category_price!s}, "
            f"quantity={_quantity!s}, "
            f"cost_basis={_cost_basis!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
