"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class CompletelyTradedEntry(object):
    """Implementation of the 'CompletelyTradedEntry' model.

    Attributes:
        advice_id (str | List[str]): List of Advice IDs representing all API
            responses that have been fully traded, where the entire portfolio
            recommendation was implemented.         A single Advice ID or multiple
            Advice IDs can be submitted.
        date (str | List[str]): Provides an agnostic timestamp of when the advice was
            executed. Timestamps can be grouped against the Advice ID in either a
            '1:1' relationship, '1:many' relationship, or a 'many:many' relationship,
            respectively. The order of the Advice ID to timestamp must follow
            linearly, meaning, the first Advice ID in the list corresponds to the
            first timestamp in the list.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "advice_id": "adviceId",
        "date": "date",
    }

    def __init__(
        self,
        advice_id=None,
        date=None,
        additional_properties=None):
        """Initialize a CompletelyTradedEntry instance."""
        # Initialize members of the class
        self.advice_id = advice_id
        self.date = date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        advice_id = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("CompletelyTradedEntryAdviceId"),
            dictionary.get("adviceId"),
            False)\
            if dictionary.get("adviceId") is not None\
            else None
        date = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("CompletelyTradedEntryDate"),
            dictionary.get("date"),
            False)\
            if dictionary.get("date") is not None\
            else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(advice_id,
                   date,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return (UnionTypeLookUp.get("CompletelyTradedEntryAdviceId")
                .validate(dictionary.advice_id).is_valid) \
                and (UnionTypeLookUp.get("CompletelyTradedEntryDate")
                .validate(dictionary.date).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return (UnionTypeLookUp.get("CompletelyTradedEntryAdviceId")
            .validate(dictionary.get("adviceId")).is_valid) \
            and (UnionTypeLookUp.get("CompletelyTradedEntryDate")
            .validate(dictionary.get("date")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _advice_id=self.advice_id
        _date=self.date
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"advice_id={_advice_id!r}, "
            f"date={_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _advice_id=self.advice_id
        _date=self.date
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"advice_id={_advice_id!s}, "
            f"date={_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
