"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class CompositionDic1(object):
    """Implementation of the 'CompositionDic1' model.

    Present value of the particular asset

    Attributes:
        equity (float): % of equity / equity like assets in the asset. All three must
            add to 1
        debt (float): % of debt assets in the concerned asset. All three must add to 1
        other (float): % of any other assets in the asset. All three must add to 1
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "equity": "equity",
        "debt": "debt",
        "other": "other",
    }

    def __init__(
        self,
        equity=None,
        debt=None,
        other=None,
        additional_properties=None):
        """Initialize a CompositionDic1 instance."""
        # Initialize members of the class
        self.equity = equity
        self.debt = debt
        self.other = other

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        equity =\
            dictionary.get("equity")\
            if dictionary.get("equity")\
                else None
        debt =\
            dictionary.get("debt")\
            if dictionary.get("debt")\
                else None
        other =\
            dictionary.get("other")\
            if dictionary.get("other")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(equity,
                   debt,
                   other,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _equity=self.equity
        _debt=self.debt
        _other=self.other
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"equity={_equity!r}, "
            f"debt={_debt!r}, "
            f"other={_other!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _equity=self.equity
        _debt=self.debt
        _other=self.other
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"equity={_equity!s}, "
            f"debt={_debt!s}, "
            f"other={_other!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
