"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class EwsAccountMappingItem(object):
    """Implementation of the 'EwsAccountMappingItem' model.

    Attributes:
        funding_sequence (int): Funding order for the mapped account within a goal.
        account_id (str): Unique investment/account identifier used for goal funding.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "funding_sequence": "fundingSequence",
        "account_id": "accountId",
    }

    def __init__(
        self,
        funding_sequence=None,
        account_id=None,
        additional_properties=None):
        """Initialize a EwsAccountMappingItem instance."""
        # Initialize members of the class
        self.funding_sequence = funding_sequence
        self.account_id = account_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        funding_sequence =\
            dictionary.get("fundingSequence")\
            if dictionary.get("fundingSequence")\
                else None
        account_id =\
            dictionary.get("accountId")\
            if dictionary.get("accountId")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(funding_sequence,
                   account_id,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.funding_sequence,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.account_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("fundingSequence"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("accountId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _funding_sequence=self.funding_sequence
        _account_id=self.account_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"funding_sequence={_funding_sequence!r}, "
            f"account_id={_account_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _funding_sequence=self.funding_sequence
        _account_id=self.account_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"funding_sequence={_funding_sequence!s}, "
            f"account_id={_account_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
