"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_goal_profile import EwsGoalProfile
from goeapi.models.ews_investment_details_2 import (
    EwsInvestmentDetails2,
)


class EwsInputModel(object):
    """Implementation of the 'EwsInputModel' model.

    Attributes:
        goal_profile (EwsGoalProfile): The model property of type EwsGoalProfile.
        investment_details (EwsInvestmentDetails2): Contains all common investment
            details and the investment list.
        risk_profile (Riskprofile): The risk tolerance profile selected by the user.
            This is defined at the user level, not per goal.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_profile": "goalProfile",
        "investment_details": "investmentDetails",
        "risk_profile": "riskProfile",
    }

    def __init__(
        self,
        goal_profile=None,
        investment_details=None,
        risk_profile=None,
        additional_properties=None):
        """Initialize a EwsInputModel instance."""
        # Initialize members of the class
        self.goal_profile = goal_profile
        self.investment_details = investment_details
        self.risk_profile = risk_profile

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_profile =\
            EwsGoalProfile.from_dictionary(
                dictionary.get("goalProfile"))\
                if dictionary.get("goalProfile") else None
        investment_details =\
            EwsInvestmentDetails2.from_dictionary(
                dictionary.get("investmentDetails"))\
                if dictionary.get("investmentDetails") else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_profile,
                   investment_details,
                   risk_profile,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_profile=self.goal_profile
        _investment_details=self.investment_details
        _risk_profile=self.risk_profile
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_profile={_goal_profile!r}, "
            f"investment_details={_investment_details!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_profile=self.goal_profile
        _investment_details=self.investment_details
        _risk_profile=self.risk_profile
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_profile={_goal_profile!s}, "
            f"investment_details={_investment_details!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
