"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_goal_profile_item import (
    EwsGoalProfileItem,
)


class EwsGoalProfile(object):
    """Implementation of the 'EwsGoalProfile' model.

    Attributes:
        goal_profile_list (List[EwsGoalProfileItem]): List containing the details of
            all goals for the investor.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_profile_list": "goalProfileList",
    }

    def __init__(
        self,
        goal_profile_list=None,
        additional_properties=None):
        """Initialize a EwsGoalProfile instance."""
        # Initialize members of the class
        self.goal_profile_list = goal_profile_list

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_profile_list = None
        if dictionary.get("goalProfileList") is not None:
            goal_profile_list = [
                EwsGoalProfileItem.from_dictionary(x)
                    for x in dictionary.get("goalProfileList")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_profile_list,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_profile_list=self.goal_profile_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_profile_list={_goal_profile_list!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_profile_list=self.goal_profile_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_profile_list={_goal_profile_list!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
