"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_goal_split_infusion_item import (
    EwsGoalSplitInfusionItem,
)
from goeapi.models.ews_goal_split_lumpsum_item import (
    EwsGoalSplitLumpsumItem,
)


class EwsAccountResponseItem(object):
    """Implementation of the 'EwsAccountResponseItem' model.

    Attributes:
        investment_id (str): Account identifier
        goal_split_infusion (List[EwsGoalSplitInfusionItem]): Goal-wise infusion
            breakdown for this account
        goal_split_lumpsum (List[EwsGoalSplitLumpsumItem]): One-time lumpsum
            allocations from this account
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "investment_id": "investmentId",
        "goal_split_infusion": "goalSplitInfusion",
        "goal_split_lumpsum": "goalSplitLumpsum",
    }

    def __init__(
        self,
        investment_id=None,
        goal_split_infusion=None,
        goal_split_lumpsum=None,
        additional_properties=None):
        """Initialize a EwsAccountResponseItem instance."""
        # Initialize members of the class
        self.investment_id = investment_id
        self.goal_split_infusion = goal_split_infusion
        self.goal_split_lumpsum = goal_split_lumpsum

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        investment_id =\
            dictionary.get("investmentId")\
            if dictionary.get("investmentId")\
                else None
        goal_split_infusion = None
        if dictionary.get("goalSplitInfusion") is not None:
            goal_split_infusion = [
                EwsGoalSplitInfusionItem.from_dictionary(x)
                    for x in dictionary.get("goalSplitInfusion")
            ]
        goal_split_lumpsum = None
        if dictionary.get("goalSplitLumpsum") is not None:
            goal_split_lumpsum = [
                EwsGoalSplitLumpsumItem.from_dictionary(x)
                    for x in dictionary.get("goalSplitLumpsum")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(investment_id,
                   goal_split_infusion,
                   goal_split_lumpsum,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _investment_id=self.investment_id
        _goal_split_infusion=self.goal_split_infusion
        _goal_split_lumpsum=self.goal_split_lumpsum
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_id={_investment_id!r}, "
            f"goal_split_infusion={_goal_split_infusion!r}, "
            f"goal_split_lumpsum={_goal_split_lumpsum!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _investment_id=self.investment_id
        _goal_split_infusion=self.goal_split_infusion
        _goal_split_lumpsum=self.goal_split_lumpsum
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_id={_investment_id!s}, "
            f"goal_split_infusion={_goal_split_infusion!s}, "
            f"goal_split_lumpsum={_goal_split_lumpsum!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
