"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_account_response_item import (
    EwsAccountResponseItem,
)
from goeapi.models.ews_goal_response_item import (
    EwsGoalResponseItem,
)


class EwsResponseBody1(object):
    """Implementation of the 'EwsResponseBody1' model.

    Main response payload

    Attributes:
        goal_response_list (List[EwsGoalResponseItem]): List of all goal-level results
        account_response_list (List[EwsAccountResponseItem]): Account-level
            allocation results.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_response_list": "goalResponseList",
        "account_response_list": "AccountResponseList",
    }

    def __init__(
        self,
        goal_response_list=None,
        account_response_list=None,
        additional_properties=None):
        """Initialize a EwsResponseBody1 instance."""
        # Initialize members of the class
        self.goal_response_list = goal_response_list
        self.account_response_list = account_response_list

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_response_list = None
        if dictionary.get("goalResponseList") is not None:
            goal_response_list = [
                EwsGoalResponseItem.from_dictionary(x)
                    for x in dictionary.get("goalResponseList")
            ]
        account_response_list = None
        if dictionary.get("AccountResponseList") is not None:
            account_response_list = [
                EwsAccountResponseItem.from_dictionary(x)
                    for x in dictionary.get("AccountResponseList")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_response_list,
                   account_response_list,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_response_list=self.goal_response_list
        _account_response_list=self.account_response_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_response_list={_goal_response_list!r}, "
            f"account_response_list={_account_response_list!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_response_list=self.goal_response_list
        _account_response_list=self.account_response_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_response_list={_goal_response_list!s}, "
            f"account_response_list={_account_response_list!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
