"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class EwsGoalProfileItem(object):
    """Implementation of the 'EwsGoalProfileItem' model.

    Attributes:
        goal_amount (float): The withdrawal amount for the goal, disbursed at every
            cashflow date from the goal start date to the goal end date.
        bequest_amount (float): The final wealth amount withdrawn at the investment
            end date, in addition to the goal amount. This number has to be zero or
            greater than zero if not null.
        goal_start_date (str): The date when the goal begins to be realized.
        goal_end_date (str): The date when the goal realization ends. For regular
            scenarios, the end date is the same as the goal start date.
        goal_id (str): A unique identifier for each goal.
        goal_name (str): A descriptive name for the goal to aid identification.
        goal_type (str): Type of goal used to map accounts to the goals.
        goal_priority (Goalpriority): Specifies the importance level of the goal for
            the investor. Priority order: Need > Want > Wish > Dream > Desire
        scenario_type (Scenariotype): Specifies the goal scenario type. Same as in
            RunPipe API.
        goal_frequency (Goalfrequency): Specifies the frequency at which goal
            withdrawals occur.
        goal_rank (int): The numerical priority rank assigned to the goal
        current_portfolio_id (int): The existing portfolio ID recommended for the
            goal in the previous EWS call, used for swing calculations.
        portfolio_set_label (str): The configuration and portfolio set associated
            with the goal
        account_mapping (List[EwsAccountMappingItem] | None): The accounts and income
            sources mapped to the goal for funding, represented as a list of
            dictionaries.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_amount": "goalAmount",
        "goal_start_date": "goalStartDate",
        "goal_end_date": "goalEndDate",
        "goal_id": "goalId",
        "goal_priority": "goalPriority",
        "scenario_type": "scenarioType",
        "goal_frequency": "goalFrequency",
        "bequest_amount": "bequestAmount",
        "goal_name": "goalName",
        "goal_type": "goalType",
        "goal_rank": "goalRank",
        "current_portfolio_id": "currentPortfolioId",
        "portfolio_set_label": "portfolioSetLabel",
        "account_mapping": "accountMapping",
    }

    _optionals = [
        "bequest_amount",
        "goal_name",
        "goal_type",
        "goal_rank",
        "current_portfolio_id",
        "portfolio_set_label",
        "account_mapping",
    ]

    _nullables = [
        "bequest_amount",
        "goal_name",
        "goal_type",
        "goal_rank",
        "current_portfolio_id",
        "portfolio_set_label",
    ]

    def __init__(
        self,
        goal_amount=None,
        goal_start_date=None,
        goal_end_date=None,
        goal_id=None,
        goal_priority=None,
        scenario_type=None,
        goal_frequency=None,
        bequest_amount=0,
        goal_name=APIHelper.SKIP,
        goal_type=APIHelper.SKIP,
        goal_rank=APIHelper.SKIP,
        current_portfolio_id=APIHelper.SKIP,
        portfolio_set_label=APIHelper.SKIP,
        account_mapping=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EwsGoalProfileItem instance."""
        # Initialize members of the class
        self.goal_amount = goal_amount
        self.bequest_amount = bequest_amount
        self.goal_start_date = goal_start_date
        self.goal_end_date = goal_end_date
        self.goal_id = goal_id
        if goal_name is not APIHelper.SKIP:
            self.goal_name = goal_name
        if goal_type is not APIHelper.SKIP:
            self.goal_type = goal_type
        self.goal_priority = goal_priority
        self.scenario_type = scenario_type
        self.goal_frequency = goal_frequency
        if goal_rank is not APIHelper.SKIP:
            self.goal_rank = goal_rank
        if current_portfolio_id is not APIHelper.SKIP:
            self.current_portfolio_id = current_portfolio_id
        if portfolio_set_label is not APIHelper.SKIP:
            self.portfolio_set_label = portfolio_set_label
        if account_mapping is not APIHelper.SKIP:
            self.account_mapping = account_mapping

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_amount =\
            dictionary.get("goalAmount")\
            if dictionary.get("goalAmount")\
                else None
        goal_start_date =\
            dictionary.get("goalStartDate")\
            if dictionary.get("goalStartDate")\
                else None
        goal_end_date =\
            dictionary.get("goalEndDate")\
            if dictionary.get("goalEndDate")\
                else None
        goal_id =\
            dictionary.get("goalId")\
            if dictionary.get("goalId")\
                else None
        goal_priority =\
            dictionary.get("goalPriority")\
            if dictionary.get("goalPriority")\
                else None
        scenario_type =\
            dictionary.get("scenarioType")\
            if dictionary.get("scenarioType")\
                else None
        goal_frequency =\
            dictionary.get("goalFrequency")\
            if dictionary.get("goalFrequency")\
                else None
        bequest_amount =\
            dictionary.get("bequestAmount")\
            if dictionary.get("bequestAmount")\
                else 0
        goal_name =\
            dictionary.get("goalName")\
            if "goalName" in dictionary.keys()\
                else APIHelper.SKIP
        goal_type =\
            dictionary.get("goalType")\
            if "goalType" in dictionary.keys()\
                else APIHelper.SKIP
        goal_rank =\
            dictionary.get("goalRank")\
            if "goalRank" in dictionary.keys()\
                else APIHelper.SKIP
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if "currentPortfolioId" in dictionary.keys()\
                else APIHelper.SKIP
        portfolio_set_label =\
            dictionary.get("portfolioSetLabel")\
            if "portfolioSetLabel" in dictionary.keys()\
                else APIHelper.SKIP
        account_mapping = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("EwsGoalProfileItemAccountMapping"),
            dictionary.get("accountMapping"),
            False)\
            if dictionary.get("accountMapping") is not None\
            else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_amount,
                   goal_start_date,
                   goal_end_date,
                   goal_id,
                   goal_priority,
                   scenario_type,
                   goal_frequency,
                   bequest_amount,
                   goal_name,
                   goal_type,
                   goal_rank,
                   current_portfolio_id,
                   portfolio_set_label,
                   account_mapping,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_amount=self.goal_amount
        _bequest_amount=(
            self.bequest_amount
            if hasattr(self, "bequest_amount")
            else None
        )
        _goal_start_date=self.goal_start_date
        _goal_end_date=self.goal_end_date
        _goal_id=self.goal_id
        _goal_name=(
            self.goal_name
            if hasattr(self, "goal_name")
            else None
        )
        _goal_type=(
            self.goal_type
            if hasattr(self, "goal_type")
            else None
        )
        _goal_priority=self.goal_priority
        _scenario_type=self.scenario_type
        _goal_frequency=self.goal_frequency
        _goal_rank=(
            self.goal_rank
            if hasattr(self, "goal_rank")
            else None
        )
        _current_portfolio_id=(
            self.current_portfolio_id
            if hasattr(self, "current_portfolio_id")
            else None
        )
        _portfolio_set_label=(
            self.portfolio_set_label
            if hasattr(self, "portfolio_set_label")
            else None
        )
        _account_mapping=(
            self.account_mapping
            if hasattr(self, "account_mapping")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_amount={_goal_amount!r}, "
            f"bequest_amount={_bequest_amount!r}, "
            f"goal_start_date={_goal_start_date!r}, "
            f"goal_end_date={_goal_end_date!r}, "
            f"goal_id={_goal_id!r}, "
            f"goal_name={_goal_name!r}, "
            f"goal_type={_goal_type!r}, "
            f"goal_priority={_goal_priority!r}, "
            f"scenario_type={_scenario_type!r}, "
            f"goal_frequency={_goal_frequency!r}, "
            f"goal_rank={_goal_rank!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"portfolio_set_label={_portfolio_set_label!r}, "
            f"account_mapping={_account_mapping!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_amount=self.goal_amount
        _bequest_amount=(
            self.bequest_amount
            if hasattr(self, "bequest_amount")
            else None
        )
        _goal_start_date=self.goal_start_date
        _goal_end_date=self.goal_end_date
        _goal_id=self.goal_id
        _goal_name=(
            self.goal_name
            if hasattr(self, "goal_name")
            else None
        )
        _goal_type=(
            self.goal_type
            if hasattr(self, "goal_type")
            else None
        )
        _goal_priority=self.goal_priority
        _scenario_type=self.scenario_type
        _goal_frequency=self.goal_frequency
        _goal_rank=(
            self.goal_rank
            if hasattr(self, "goal_rank")
            else None
        )
        _current_portfolio_id=(
            self.current_portfolio_id
            if hasattr(self, "current_portfolio_id")
            else None
        )
        _portfolio_set_label=(
            self.portfolio_set_label
            if hasattr(self, "portfolio_set_label")
            else None
        )
        _account_mapping=(
            self.account_mapping
            if hasattr(self, "account_mapping")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_amount={_goal_amount!s}, "
            f"bequest_amount={_bequest_amount!s}, "
            f"goal_start_date={_goal_start_date!s}, "
            f"goal_end_date={_goal_end_date!s}, "
            f"goal_id={_goal_id!s}, "
            f"goal_name={_goal_name!s}, "
            f"goal_type={_goal_type!s}, "
            f"goal_priority={_goal_priority!s}, "
            f"scenario_type={_scenario_type!s}, "
            f"goal_frequency={_goal_frequency!s}, "
            f"goal_rank={_goal_rank!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"portfolio_set_label={_portfolio_set_label!s}, "
            f"account_mapping={_account_mapping!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
