"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_series_value import EwsSeriesValue


class EwsGoalResponseItem(object):
    """Implementation of the 'EwsGoalResponseItem' model.

    Attributes:
        goal_id (str): Goal identifier
        current_wealth (float): Current allocated wealth for this goal.
        infusions (List[EwsSeriesValue]): Cashflow timeline for this goal.
        goal_priority_order (int): Outputs the priority of the goal as inputted by
            the user or calculated by the algorithm.
        goal_amount (float): This is the bequestAmount + goalAmount(only if they lie
            on the cashflowDate).
        funded_status (Fundedstatus): Funding status of the goal
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_id": "goalId",
        "current_wealth": "currentWealth",
        "infusions": "infusions",
        "goal_priority_order": "goalPriorityOrder",
        "goal_amount": "goalAmount",
        "funded_status": "fundedStatus",
    }

    def __init__(
        self,
        goal_id=None,
        current_wealth=None,
        infusions=None,
        goal_priority_order=None,
        goal_amount=None,
        funded_status=None,
        additional_properties=None):
        """Initialize a EwsGoalResponseItem instance."""
        # Initialize members of the class
        self.goal_id = goal_id
        self.current_wealth = current_wealth
        self.infusions = infusions
        self.goal_priority_order = goal_priority_order
        self.goal_amount = goal_amount
        self.funded_status = funded_status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_id =\
            dictionary.get("goalId")\
            if dictionary.get("goalId")\
                else None
        current_wealth =\
            dictionary.get("currentWealth")\
            if dictionary.get("currentWealth")\
                else None
        infusions = None
        if dictionary.get("infusions") is not None:
            infusions = [
                EwsSeriesValue.from_dictionary(x)
                    for x in dictionary.get("infusions")
            ]
        goal_priority_order =\
            dictionary.get("goalPriorityOrder")\
            if dictionary.get("goalPriorityOrder")\
                else None
        goal_amount =\
            dictionary.get("goalAmount")\
            if dictionary.get("goalAmount")\
                else None
        funded_status =\
            dictionary.get("fundedStatus")\
            if dictionary.get("fundedStatus")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_id,
                   current_wealth,
                   infusions,
                   goal_priority_order,
                   goal_amount,
                   funded_status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_id=self.goal_id
        _current_wealth=self.current_wealth
        _infusions=self.infusions
        _goal_priority_order=self.goal_priority_order
        _goal_amount=self.goal_amount
        _funded_status=self.funded_status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!r}, "
            f"current_wealth={_current_wealth!r}, "
            f"infusions={_infusions!r}, "
            f"goal_priority_order={_goal_priority_order!r}, "
            f"goal_amount={_goal_amount!r}, "
            f"funded_status={_funded_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_id=self.goal_id
        _current_wealth=self.current_wealth
        _infusions=self.infusions
        _goal_priority_order=self.goal_priority_order
        _goal_amount=self.goal_amount
        _funded_status=self.funded_status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!s}, "
            f"current_wealth={_current_wealth!s}, "
            f"infusions={_infusions!s}, "
            f"goal_priority_order={_goal_priority_order!s}, "
            f"goal_amount={_goal_amount!s}, "
            f"funded_status={_funded_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
