"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_account_infusion_item import (
    EwsAccountInfusionItem,
)


class EwsInvestmentItem(object):
    """Implementation of the 'EwsInvestmentItem' model.

    Attributes:
        investment_id (str): Unique identifier for the investment account.
        funding_type (str): Funding type label for the account.
        account_type (str): Type of accounts used to map accounts to the goals.
        lumpsum_amount (int): The initial investment amount available as of the
            current date.
        account_infusion (List[EwsAccountInfusionItem]): Contains scheduled future
            contributions with their dates and amounts
        end_date (str): The end date of the investment account.
        infusion_type (Infusiontype): Specifies the frequency at which account
            contributions occur.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "investment_id": "investmentId",
        "lumpsum_amount": "lumpsumAmount",
        "account_infusion": "accountInfusion",
        "end_date": "endDate",
        "infusion_type": "infusionType",
        "funding_type": "fundingType",
        "account_type": "accountType",
    }

    _optionals = [
        "funding_type",
        "account_type",
    ]

    _nullables = [
        "funding_type",
        "account_type",
    ]

    def __init__(
        self,
        investment_id=None,
        lumpsum_amount=None,
        account_infusion=None,
        end_date=None,
        infusion_type=None,
        funding_type=APIHelper.SKIP,
        account_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EwsInvestmentItem instance."""
        # Initialize members of the class
        self.investment_id = investment_id
        if funding_type is not APIHelper.SKIP:
            self.funding_type = funding_type
        if account_type is not APIHelper.SKIP:
            self.account_type = account_type
        self.lumpsum_amount = lumpsum_amount
        self.account_infusion = account_infusion
        self.end_date = end_date
        self.infusion_type = infusion_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        investment_id =\
            dictionary.get("investmentId")\
            if dictionary.get("investmentId")\
                else None
        lumpsum_amount =\
            dictionary.get("lumpsumAmount")\
            if dictionary.get("lumpsumAmount")\
                else None
        account_infusion = None
        if dictionary.get("accountInfusion") is not None:
            account_infusion = [
                EwsAccountInfusionItem.from_dictionary(x)
                    for x in dictionary.get("accountInfusion")
            ]
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else None
        infusion_type =\
            dictionary.get("infusionType")\
            if dictionary.get("infusionType")\
                else None
        funding_type =\
            dictionary.get("fundingType")\
            if "fundingType" in dictionary.keys()\
                else APIHelper.SKIP
        account_type =\
            dictionary.get("accountType")\
            if "accountType" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(investment_id,
                   lumpsum_amount,
                   account_infusion,
                   end_date,
                   infusion_type,
                   funding_type,
                   account_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _investment_id=self.investment_id
        _funding_type=(
            self.funding_type
            if hasattr(self, "funding_type")
            else None
        )
        _account_type=(
            self.account_type
            if hasattr(self, "account_type")
            else None
        )
        _lumpsum_amount=self.lumpsum_amount
        _account_infusion=self.account_infusion
        _end_date=self.end_date
        _infusion_type=self.infusion_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_id={_investment_id!r}, "
            f"funding_type={_funding_type!r}, "
            f"account_type={_account_type!r}, "
            f"lumpsum_amount={_lumpsum_amount!r}, "
            f"account_infusion={_account_infusion!r}, "
            f"end_date={_end_date!r}, "
            f"infusion_type={_infusion_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _investment_id=self.investment_id
        _funding_type=(
            self.funding_type
            if hasattr(self, "funding_type")
            else None
        )
        _account_type=(
            self.account_type
            if hasattr(self, "account_type")
            else None
        )
        _lumpsum_amount=self.lumpsum_amount
        _account_infusion=self.account_infusion
        _end_date=self.end_date
        _infusion_type=self.infusion_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"investment_id={_investment_id!s}, "
            f"funding_type={_funding_type!s}, "
            f"account_type={_account_type!s}, "
            f"lumpsum_amount={_lumpsum_amount!s}, "
            f"account_infusion={_account_infusion!s}, "
            f"end_date={_end_date!s}, "
            f"infusion_type={_infusion_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
