"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_investment_item import (
    EwsInvestmentItem,
)


class EwsInvestmentDetails2(object):
    """Implementation of the 'EwsInvestmentDetails2' model.

    Contains all common investment details and the investment list.

    Attributes:
        curr_date (str): The current date, same as in RunPipe API. If not given then
            it takes the current system date.
        current_age (int): The current age of the investor.
        retirement_age (int): The retirement age of the investor.
        investment_list (List[EwsInvestmentItem]): The list of investment accounts
            with their details.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "current_age": "currentAge",
        "investment_list": "investmentList",
        "curr_date": "currDate",
        "retirement_age": "retirementAge",
    }

    _optionals = [
        "curr_date",
        "retirement_age",
    ]

    _nullables = [
        "retirement_age",
    ]

    def __init__(
        self,
        current_age=None,
        investment_list=None,
        curr_date=APIHelper.SKIP,
        retirement_age=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EwsInvestmentDetails2 instance."""
        # Initialize members of the class
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.current_age = current_age
        if retirement_age is not APIHelper.SKIP:
            self.retirement_age = retirement_age
        self.investment_list = investment_list

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        current_age =\
            dictionary.get("currentAge")\
            if dictionary.get("currentAge")\
                else None
        investment_list = None
        if dictionary.get("investmentList") is not None:
            investment_list = [
                EwsInvestmentItem.from_dictionary(x)
                    for x in dictionary.get("investmentList")
            ]
        curr_date =\
            dictionary.get("currDate")\
            if dictionary.get("currDate")\
                else APIHelper.SKIP
        retirement_age =\
            dictionary.get("retirementAge")\
            if "retirementAge" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(current_age,
                   investment_list,
                   curr_date,
                   retirement_age,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _current_age=self.current_age
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _investment_list=self.investment_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"curr_date={_curr_date!r}, "
            f"current_age={_current_age!r}, "
            f"retirement_age={_retirement_age!r}, "
            f"investment_list={_investment_list!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _current_age=self.current_age
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _investment_list=self.investment_list
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"curr_date={_curr_date!s}, "
            f"current_age={_current_age!s}, "
            f"retirement_age={_retirement_age!s}, "
            f"investment_list={_investment_list!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
