"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class EwsGoalSplitLumpsumItem(object):
    """Implementation of the 'EwsGoalSplitLumpsumItem' model.

    Attributes:
        goal_id (str): Goal receiving lumpsum
        value (float): Lumpsum amount
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_id": "goalId",
        "value": "value",
    }

    def __init__(
        self,
        goal_id=None,
        value=None,
        additional_properties=None):
        """Initialize a EwsGoalSplitLumpsumItem instance."""
        # Initialize members of the class
        self.goal_id = goal_id
        self.value = value

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_id =\
            dictionary.get("goalId")\
            if dictionary.get("goalId")\
                else None
        value =\
            dictionary.get("value")\
            if dictionary.get("value")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_id,
                   value,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_id=self.goal_id
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!r}, "
            f"value={_value!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_id=self.goal_id
        _value=self.value
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!s}, "
            f"value={_value!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
