"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.ews_series_value import EwsSeriesValue


class EwsGoalSplitInfusionItem(object):
    """Implementation of the 'EwsGoalSplitInfusionItem' model.

    Attributes:
        goal_id (str): Goal receiving infusions
        cashflow (List[EwsSeriesValue]): Timeline of infusions to this goal
        first_contribution_date (str): Date of first contribution
        first_contribution_amount (int): Value at the date of first contribution
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_id": "goalId",
        "cashflow": "cashflow",
        "first_contribution_date": "firstContributionDate",
        "first_contribution_amount": "firstContributionAmount",
    }

    _nullables = [
        "first_contribution_date",
        "first_contribution_amount",
    ]

    def __init__(
        self,
        goal_id=None,
        cashflow=None,
        first_contribution_date=None,
        first_contribution_amount=None,
        additional_properties=None):
        """Initialize a EwsGoalSplitInfusionItem instance."""
        # Initialize members of the class
        self.goal_id = goal_id
        self.cashflow = cashflow
        self.first_contribution_date = first_contribution_date
        self.first_contribution_amount = first_contribution_amount

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_id =\
            dictionary.get("goalId")\
            if dictionary.get("goalId")\
                else None
        cashflow = None
        if dictionary.get("cashflow") is not None:
            cashflow = [
                EwsSeriesValue.from_dictionary(x)
                    for x in dictionary.get("cashflow")
            ]
        first_contribution_date =\
            dictionary.get("firstContributionDate")\
            if dictionary.get("firstContributionDate")\
                else None
        first_contribution_amount =\
            dictionary.get("firstContributionAmount")\
            if dictionary.get("firstContributionAmount")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_id,
                   cashflow,
                   first_contribution_date,
                   first_contribution_amount,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_id=self.goal_id
        _cashflow=self.cashflow
        _first_contribution_date=self.first_contribution_date
        _first_contribution_amount=self.first_contribution_amount
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!r}, "
            f"cashflow={_cashflow!r}, "
            f"first_contribution_date={_first_contribution_date!r}, "
            f"first_contribution_amount={_first_contribution_amount!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_id=self.goal_id
        _cashflow=self.cashflow
        _first_contribution_date=self.first_contribution_date
        _first_contribution_amount=self.first_contribution_amount
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!s}, "
            f"cashflow={_cashflow!s}, "
            f"first_contribution_date={_first_contribution_date!s}, "
            f"first_contribution_amount={_first_contribution_amount!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
