"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.composition_dic_1 import (
    CompositionDic1,
)


class FixedAsset(object):
    """Implementation of the '_fixedAsset' model.

    Attributes:
        name (str): All objects should have Unique names
        current_value (float): Present value of the particular asset.
        current_composition (CompositionDic1): Present value of the particular asset
        expected_date_of_conversion_to_aum (str): Future date when this asset will
            convert into assets available for GOE advice. <br>             Must be in
            dd-mm-yyyy format
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "current_value": "currentValue",
        "current_composition": "currentComposition",
        "expected_date_of_conversion_to_aum": "expectedDateOfConversionToAUM",
    }

    def __init__(
        self,
        name=None,
        current_value=None,
        current_composition=None,
        expected_date_of_conversion_to_aum=None,
        additional_properties=None):
        """Initialize a FixedAsset instance."""
        # Initialize members of the class
        self.name = name
        self.current_value = current_value
        self.current_composition = current_composition
        self.expected_date_of_conversion_to_aum = expected_date_of_conversion_to_aum

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        current_value =\
            dictionary.get("currentValue")\
            if dictionary.get("currentValue")\
                else None
        current_composition =\
            CompositionDic1.from_dictionary(
                dictionary.get("currentComposition"))\
                if dictionary.get("currentComposition") else None
        expected_date_of_conversion_to_aum =\
            dictionary.get("expectedDateOfConversionToAUM")\
            if dictionary.get("expectedDateOfConversionToAUM")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   current_value,
                   current_composition,
                   expected_date_of_conversion_to_aum,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _name=self.name
        _current_value=self.current_value
        _current_composition=self.current_composition
        _expected_date_of_conversion_to_aum=self.expected_date_of_conversion_to_aum
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!r}, "
            f"current_value={_current_value!r}, "
            f"current_composition={_current_composition!r}, "
            f"expected_date_of_conversion_to_aum={_expected_date_of_conversion_to_aum!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _name=self.name
        _current_value=self.current_value
        _current_composition=self.current_composition
        _expected_date_of_conversion_to_aum=self.expected_date_of_conversion_to_aum
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"name={_name!s}, "
            f"current_value={_current_value!s}, "
            f"current_composition={_current_composition!s}, "
            f"expected_date_of_conversion_to_aum={_expected_date_of_conversion_to_aum!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
