"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.cash_flow_dict_1 import CashFlowDict1
from goeapi.models.policy_details import PolicyDetails


class GoalCalculatorInputModel(object):
    """Implementation of the 'GoalCalculatorInputModel' model.

    Attributes:
        is_new_goal (bool): If investor/end user changes the goal amount, in between
            the re-allocation dates, this is set to ‘true’. For retirement scenarios,
            this would be a change in retirement income goal, while for a capital
            accumulation goal,                                                 this
            would be a change in the lumpsum accumulation target. For first time
            calls to GOE, this needs to be set to ‘true’.
        is_new_risk_profile (bool): If investor/end user changes the goal priority in
            between the re-allocation dates, this is set to ‘true’.
            For first time calls to GOE, this needs to be set to ‘true’.
        is_new_investment_tenure (bool): If investor/end user changes the goal
            investment tenure after onboarding and before the next immediate
            re-allocation date,                                     this is set to
            ‘true’. For first time calls to GOE, this needs to be set to ‘true’.
        is_new_goal_priority (bool): If investor/end user changes the goal priority
            in between the re-allocation dates, this is set to ‘true’.
            For new plans, this needs to be ‘true’.
        reallocate (bool): If the client wants GOE to reallocate between the
            scheduled re-allocation dates, this should be set to ‘true’.
        use_caps_and_floors (bool): This is an optional parameter set as false by
            default. If this is passed as ‘true’ – the minimum and maximum
            equity allocation at any given year would be restricted based on the
            number of years to goal;Either goalStartDate or the ‘currentAge’
            is required if this is set to True. If set to true 'Risk Profile' is
            ignored.
        reallocation_freq (ReallocationFreq): Describes the frequency of
            re-allocation.
        get_path (bool): Show ideal portfolio path over time. If getPath parameter is
            set to False, the portfolio path would not be returned in the response
            payload
        current_portfolio_id (int): Displays the current portfolio index that the
            goal is allocated to;
            if GOE is getting executed for the first time, it should be null.
        scenario_type (ScenarioType1): Determines the type of the scenario, the
            suggested portfolio and the wealth glide path is created accordingly.
            ‘regular’ for regular goals accumulation goals where cash flows are
            positive (contributions) and with a typical target wealth ‘retirement’
            for scenarios where a decumulation period is included: <br>            1.
            Scenarios with an accumulation period (and an initial wealth) & positive
            cash flows followed by a decumulation period with withdrawals (negative
            cash flows) with or without an inheritance <br>                2.
            Scenarios with an initial wealth followed by a decumulation period with
            or without an inheritance.
        curr_date (str): This is an optional parameter that can be used to simulate
            the current date to be the specified value.
            GOE will process the request as if you are making the API call on the
            specified date. If not passed, the current system date will be used as
            the current date.
        risk_profile (RiskProfile1): Defines the user’s risk profile – does not vary
            by goal for each investor. On a default basis, GOE is configured for
            three Risk Profile levels, but it can be customized for up to five
            levels. Note that Risk Profiles are mapped to portfolio access.This is
            nullable and non mandatory if useCapsAndFloors is true.
        initial_investment (float): Defines the initial investment amount to the goal.
        current_wealth (float): Current wealth when the GOE is being called or
            executed. At the time of initial onboarding, currentWealth =
            initialInvestment.
            At subsequent re-allocation dates, currentWealth would be the portfolio
            account value at the time.
        cashflow_date (str): Cashflow date of the goal - this is the date (year is
            ignored) on which infusions/withdrawals
            would be realized for the goal. Format is "dd-mm-yyyy"
            If not passed or value is null, the algorithm would consider the first
            reallocation date as the cashflow date.
        goal_priority (GoalCalculatorGoalPriorityAttribute): Defines the importance a
            goal holds for a specific user. Order of priority is Need > Want > Wish >
            Dream          goalPriority can be from 1 to 4 levels. However, note that
            Goal priority defines the target probabilities and the loss threshold
            values.
        goal_amount (float): For regular scenarios, either the goal amount field
            shouldn't be provided in the input payload, or if provided, it should
            either be 'null' or '0.         For retirement cases where  the intent is
            to calculate an appropriate bequest amount, the bequest (“goal_amt”)
            should be specified as ‘null’ or ‘0’. For other cases, it can any number
            greater than zero.
        start_date (str): Defines the start date of goal. Valid input format is date
            – ‘dd-mm-yyyy’
        goal_start_date (str): Defines the goal's start date. Must be greater than
            the startDate field and in DD-MM-YYYY format. Default value is Null.
            Mandatory If useCapsAndFloors is True and currentAge is not present.
        end_date (str): Defines the end date of goal. Valid input format is date –
            ‘dd-mm-yyyy’
        infusion_type (InfusionType1): Indicates the frequency of cash flows –
            determines the cash flow array corresponding to the ‘infusions’ parameter.
        infusions (List[float]): Cash flows from the user, recurring payments yearly
            The length for this parameter is dynamic depending on the goal tenure,
            start date and end date.
            The reference will always be on the created date. So, the first infusion
            will be on the first day of the goal
            followed by infusions every year/month followed by the last
            infusion/withdrawal on the last day of the goal.
            The values are positive in case of infusions; negative in case of
            withdrawals; zero in case of no cashflows; frequency depends on
            ‘infusion_type’ parameter.
            If each of the withdrawal amounts are set as ‘-1’ in the infusions array,
            then it is assumed that the income goal needs to be calculated.
        current_age (int): Captures the current age of the investor.<br>
            Optional Parameter. Need to be passed if useCapsAndFloors is set to True
            or ‘requiredDataAvailable’ is set to False.
        retirement_age (int): Captures the retirement age of the investor.
            Optional Parameter. Considered as 65 if not passed
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        engaged_participant (bool | None): This applies only to retirement use cases
            which specifies whether a participant is engaged or unengaged. If the
            'currentAge' and the             'retirementAge' are passed, they will be
            used to determine the de-risking criteria; If set to true GOE
            will de-risk 5 years before retirement and if set to false GOE will
            de-risk 1 year before retirement as per the default admin configuration
            settings
        last_reallocation_date (str): The date on which last reallocation call was
            made to GOE. Format - dd-mm-yyyy
        plan_id (str): Plan ID of the participant.
        participant_id (str): ID of the participant.
        source_id (str): Source ID of the plan
        cashflow (List[CashFlowDict1]): Cannot be a empty list. If defined, should
            have objects with below attributes.              Multiple objects of each
            type should not be allowed. For example, you cannot allow two objects of
            type "GOAL".             When "cashflow" is passed, "infusions" and
            "goalAmount" will be optional. Otherwise these two will be mandatory.
            The field is optional if "infusions" is provided, otherwise mandatory.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_new_goal": "isNewGoal",
        "is_new_risk_profile": "isNewRiskProfile",
        "is_new_investment_tenure": "isNewInvestmentTenure",
        "is_new_goal_priority": "isNewGoalPriority",
        "reallocation_freq": "reallocationFreq",
        "get_path": "getPath",
        "current_portfolio_id": "currentPortfolioId",
        "scenario_type": "scenarioType",
        "risk_profile": "riskProfile",
        "initial_investment": "initialInvestment",
        "current_wealth": "currentWealth",
        "goal_priority": "goalPriority",
        "goal_amount": "goalAmount",
        "start_date": "startDate",
        "end_date": "endDate",
        "infusion_type": "infusionType",
        "infusions": "infusions",
        "reallocate": "reallocate",
        "use_caps_and_floors": "useCapsAndFloors",
        "curr_date": "currDate",
        "cashflow_date": "cashflowDate",
        "goal_start_date": "goalStartDate",
        "current_age": "currentAge",
        "retirement_age": "retirementAge",
        "policy": "policy",
        "engaged_participant": "engagedParticipant",
        "last_reallocation_date": "lastReallocationDate",
        "plan_id": "planID",
        "participant_id": "participantID",
        "source_id": "sourceID",
        "cashflow": "cashflow",
    }

    _optionals = [
        "reallocate",
        "use_caps_and_floors",
        "curr_date",
        "cashflow_date",
        "goal_start_date",
        "current_age",
        "retirement_age",
        "policy",
        "engaged_participant",
        "last_reallocation_date",
        "plan_id",
        "participant_id",
        "source_id",
        "cashflow",
    ]

    _nullables = [
        "current_portfolio_id",
        "curr_date",
        "current_wealth",
        "cashflow_date",
        "last_reallocation_date",
        "plan_id",
        "participant_id",
        "source_id",
    ]

    def __init__(
        self,
        is_new_goal=None,
        is_new_risk_profile=None,
        is_new_investment_tenure=None,
        is_new_goal_priority=None,
        reallocation_freq=None,
        get_path=None,
        current_portfolio_id=None,
        scenario_type=None,
        risk_profile=None,
        initial_investment=None,
        current_wealth=None,
        goal_priority=None,
        goal_amount=None,
        start_date=None,
        end_date=None,
        infusion_type=None,
        infusions=None,
        reallocate=False,
        use_caps_and_floors=False,
        curr_date=APIHelper.SKIP,
        cashflow_date=APIHelper.SKIP,
        goal_start_date=APIHelper.SKIP,
        current_age=APIHelper.SKIP,
        retirement_age=APIHelper.SKIP,
        policy=APIHelper.SKIP,
        engaged_participant=APIHelper.SKIP,
        last_reallocation_date=APIHelper.SKIP,
        plan_id=APIHelper.SKIP,
        participant_id=APIHelper.SKIP,
        source_id=APIHelper.SKIP,
        cashflow=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoalCalculatorInputModel instance."""
        # Initialize members of the class
        self.is_new_goal = is_new_goal
        self.is_new_risk_profile = is_new_risk_profile
        self.is_new_investment_tenure = is_new_investment_tenure
        self.is_new_goal_priority = is_new_goal_priority
        self.reallocate = reallocate
        self.use_caps_and_floors = use_caps_and_floors
        self.reallocation_freq = reallocation_freq
        self.get_path = get_path
        self.current_portfolio_id = current_portfolio_id
        self.scenario_type = scenario_type
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.risk_profile = risk_profile
        self.initial_investment = initial_investment
        self.current_wealth = current_wealth
        if cashflow_date is not APIHelper.SKIP:
            self.cashflow_date = cashflow_date
        self.goal_priority = goal_priority
        self.goal_amount = goal_amount
        self.start_date = start_date
        if goal_start_date is not APIHelper.SKIP:
            self.goal_start_date = goal_start_date
        self.end_date = end_date
        self.infusion_type = infusion_type
        self.infusions = infusions
        if current_age is not APIHelper.SKIP:
            self.current_age = current_age
        if retirement_age is not APIHelper.SKIP:
            self.retirement_age = retirement_age
        if policy is not APIHelper.SKIP:
            self.policy = policy
        if engaged_participant is not APIHelper.SKIP:
            self.engaged_participant = engaged_participant
        if last_reallocation_date is not APIHelper.SKIP:
            self.last_reallocation_date = last_reallocation_date
        if plan_id is not APIHelper.SKIP:
            self.plan_id = plan_id
        if participant_id is not APIHelper.SKIP:
            self.participant_id = participant_id
        if source_id is not APIHelper.SKIP:
            self.source_id = source_id
        if cashflow is not APIHelper.SKIP:
            self.cashflow = cashflow

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        is_new_goal =\
            dictionary.get("isNewGoal")\
            if "isNewGoal" in dictionary.keys()\
                else None
        is_new_risk_profile =\
            dictionary.get("isNewRiskProfile")\
            if "isNewRiskProfile" in dictionary.keys()\
                else None
        is_new_investment_tenure =\
            dictionary.get("isNewInvestmentTenure")\
            if "isNewInvestmentTenure" in dictionary.keys()\
                else None
        is_new_goal_priority =\
            dictionary.get("isNewGoalPriority")\
            if "isNewGoalPriority" in dictionary.keys()\
                else None
        reallocation_freq =\
            dictionary.get("reallocationFreq")\
            if dictionary.get("reallocationFreq")\
                else None
        get_path =\
            dictionary.get("getPath")\
            if "getPath" in dictionary.keys()\
                else None
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if dictionary.get("currentPortfolioId")\
                else None
        scenario_type =\
            dictionary.get("scenarioType")\
            if dictionary.get("scenarioType")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        initial_investment =\
            dictionary.get("initialInvestment")\
            if dictionary.get("initialInvestment")\
                else None
        current_wealth =\
            dictionary.get("currentWealth")\
            if dictionary.get("currentWealth")\
                else None
        goal_priority =\
            dictionary.get("goalPriority")\
            if dictionary.get("goalPriority")\
                else None
        goal_amount =\
            dictionary.get("goalAmount")\
            if dictionary.get("goalAmount")\
                else None
        start_date =\
            dictionary.get("startDate")\
            if dictionary.get("startDate")\
                else None
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else None
        infusion_type =\
            dictionary.get("infusionType")\
            if dictionary.get("infusionType")\
                else None
        infusions =\
            dictionary.get("infusions")\
            if dictionary.get("infusions")\
                else None
        reallocate =\
            dictionary.get("reallocate")\
            if dictionary.get("reallocate")\
                else False
        use_caps_and_floors =\
            dictionary.get("useCapsAndFloors")\
            if dictionary.get("useCapsAndFloors")\
                else False
        curr_date =\
            dictionary.get("currDate")\
            if "currDate" in dictionary.keys()\
                else APIHelper.SKIP
        cashflow_date =\
            dictionary.get("cashflowDate")\
            if "cashflowDate" in dictionary.keys()\
                else APIHelper.SKIP
        goal_start_date =\
            dictionary.get("goalStartDate")\
            if dictionary.get("goalStartDate")\
                else APIHelper.SKIP
        current_age =\
            dictionary.get("currentAge")\
            if dictionary.get("currentAge")\
                else APIHelper.SKIP
        retirement_age =\
            dictionary.get("retirementAge")\
            if dictionary.get("retirementAge")\
                else APIHelper.SKIP
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP
        engaged_participant = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("GoalCalculatorInputModelEngagedParticipant"),
            dictionary.get("engagedParticipant"),
            False)\
            if dictionary.get("engagedParticipant") is not None\
            else APIHelper.SKIP
        last_reallocation_date =\
            dictionary.get("lastReallocationDate")\
            if "lastReallocationDate" in dictionary.keys()\
                else APIHelper.SKIP
        plan_id =\
            dictionary.get("planID")\
            if "planID" in dictionary.keys()\
                else APIHelper.SKIP
        participant_id =\
            dictionary.get("participantID")\
            if "participantID" in dictionary.keys()\
                else APIHelper.SKIP
        source_id =\
            dictionary.get("sourceID")\
            if "sourceID" in dictionary.keys()\
                else APIHelper.SKIP
        cashflow = None
        if dictionary.get("cashflow") is not None:
            cashflow = [
                CashFlowDict1.from_dictionary(x)
                    for x in dictionary.get("cashflow")
            ]
        else:
            cashflow = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(is_new_goal,
                   is_new_risk_profile,
                   is_new_investment_tenure,
                   is_new_goal_priority,
                   reallocation_freq,
                   get_path,
                   current_portfolio_id,
                   scenario_type,
                   risk_profile,
                   initial_investment,
                   current_wealth,
                   goal_priority,
                   goal_amount,
                   start_date,
                   end_date,
                   infusion_type,
                   infusions,
                   reallocate,
                   use_caps_and_floors,
                   curr_date,
                   cashflow_date,
                   goal_start_date,
                   current_age,
                   retirement_age,
                   policy,
                   engaged_participant,
                   last_reallocation_date,
                   plan_id,
                   participant_id,
                   source_id,
                   cashflow,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _is_new_goal=self.is_new_goal
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_goal_priority=self.is_new_goal_priority
        _reallocate=(
            self.reallocate
            if hasattr(self, "reallocate")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _reallocation_freq=self.reallocation_freq
        _get_path=self.get_path
        _current_portfolio_id=self.current_portfolio_id
        _scenario_type=self.scenario_type
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _initial_investment=self.initial_investment
        _current_wealth=self.current_wealth
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _goal_priority=self.goal_priority
        _goal_amount=self.goal_amount
        _start_date=self.start_date
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _end_date=self.end_date
        _infusion_type=self.infusion_type
        _infusions=self.infusions
        _current_age=(
            self.current_age
            if hasattr(self, "current_age")
            else None
        )
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _engaged_participant=(
            self.engaged_participant
            if hasattr(self, "engaged_participant")
            else None
        )
        _last_reallocation_date=(
            self.last_reallocation_date
            if hasattr(self, "last_reallocation_date")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_new_goal={_is_new_goal!r}, "
            f"is_new_risk_profile={_is_new_risk_profile!r}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!r}, "
            f"is_new_goal_priority={_is_new_goal_priority!r}, "
            f"reallocate={_reallocate!r}, "
            f"use_caps_and_floors={_use_caps_and_floors!r}, "
            f"reallocation_freq={_reallocation_freq!r}, "
            f"get_path={_get_path!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"scenario_type={_scenario_type!r}, "
            f"curr_date={_curr_date!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"initial_investment={_initial_investment!r}, "
            f"current_wealth={_current_wealth!r}, "
            f"cashflow_date={_cashflow_date!r}, "
            f"goal_priority={_goal_priority!r}, "
            f"goal_amount={_goal_amount!r}, "
            f"start_date={_start_date!r}, "
            f"goal_start_date={_goal_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"infusion_type={_infusion_type!r}, "
            f"infusions={_infusions!r}, "
            f"current_age={_current_age!r}, "
            f"retirement_age={_retirement_age!r}, "
            f"policy={_policy!r}, "
            f"engaged_participant={_engaged_participant!r}, "
            f"last_reallocation_date={_last_reallocation_date!r}, "
            f"plan_id={_plan_id!r}, "
            f"participant_id={_participant_id!r}, "
            f"source_id={_source_id!r}, "
            f"cashflow={_cashflow!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _is_new_goal=self.is_new_goal
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_goal_priority=self.is_new_goal_priority
        _reallocate=(
            self.reallocate
            if hasattr(self, "reallocate")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _reallocation_freq=self.reallocation_freq
        _get_path=self.get_path
        _current_portfolio_id=self.current_portfolio_id
        _scenario_type=self.scenario_type
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _initial_investment=self.initial_investment
        _current_wealth=self.current_wealth
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _goal_priority=self.goal_priority
        _goal_amount=self.goal_amount
        _start_date=self.start_date
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _end_date=self.end_date
        _infusion_type=self.infusion_type
        _infusions=self.infusions
        _current_age=(
            self.current_age
            if hasattr(self, "current_age")
            else None
        )
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _engaged_participant=(
            self.engaged_participant
            if hasattr(self, "engaged_participant")
            else None
        )
        _last_reallocation_date=(
            self.last_reallocation_date
            if hasattr(self, "last_reallocation_date")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_new_goal={_is_new_goal!s}, "
            f"is_new_risk_profile={_is_new_risk_profile!s}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!s}, "
            f"is_new_goal_priority={_is_new_goal_priority!s}, "
            f"reallocate={_reallocate!s}, "
            f"use_caps_and_floors={_use_caps_and_floors!s}, "
            f"reallocation_freq={_reallocation_freq!s}, "
            f"get_path={_get_path!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"scenario_type={_scenario_type!s}, "
            f"curr_date={_curr_date!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"initial_investment={_initial_investment!s}, "
            f"current_wealth={_current_wealth!s}, "
            f"cashflow_date={_cashflow_date!s}, "
            f"goal_priority={_goal_priority!s}, "
            f"goal_amount={_goal_amount!s}, "
            f"start_date={_start_date!s}, "
            f"goal_start_date={_goal_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"infusion_type={_infusion_type!s}, "
            f"infusions={_infusions!s}, "
            f"current_age={_current_age!s}, "
            f"retirement_age={_retirement_age!s}, "
            f"policy={_policy!s}, "
            f"engaged_participant={_engaged_participant!s}, "
            f"last_reallocation_date={_last_reallocation_date!s}, "
            f"plan_id={_plan_id!s}, "
            f"participant_id={_participant_id!s}, "
            f"source_id={_source_id!s}, "
            f"cashflow={_cashflow!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
