"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class GoalProfileListWealthSplitterModel(object):
    """Implementation of the 'GoalProfileListWealthSplitterModel' model.

    Attributes:
        goal_id (str): Unique identifier for each goal
        goal_value (float): Target goal amount
        purpose (str): Type of goal (for example, ‘Children’s education, Vacation,
            etc.’)
        curr_wealth (float): Current wealth allocated for the goal when the Initial
            Wealth Splitter is being called or executed.
        cashflow_date (str): Cashflow date of the goal - this is the date (year is
            ignored) on which infusions/withdrawals
            would be realized for the goal. Format is "dd-mm-yyyy"
            If not passed or value is null, the algorithm would consider the first
            reallocation date as the cashflow date.
        goal_start_date (str): Defines the goal's start date. Must be greater than or
            equal to the startDate field and in DD-MM-YYYY format. Default value is
            Null.
        goal_priority (WeathSplitterGoalPriorityAttribute): Defines the importance a
            goal holds for a specific user. Order of priority is Need > Want > Wish >
            Dream  <br>         goalPriority can be from 1 to 4 levels. However, note
            that Goal priority defines the target probabilities and the loss
            threshold values.         For example, goals with a higher priority (e.g.
            Need) would have a higher target goal probability (85%) with a higher
            (aggressive) loss threshold value (slightly more than IW value) in the
            current set-up.         This needs to be re-mapped based on the number of
            goal-priority levels, in case of a change.
        cashflow_type (str): Describes the cash flow frequency.
            Valid input is ‘yearly’ or ‘monthly’.
            This parameter is provided to account for real-world investors who might
            put in monthly infusions as opposed to yearly infusions.
            Monthly infusions would be smaller in value (and hence easier to commit
            to) vs. yearly infusions.
        cashflow (List[float]): Cashflow array – includes any cash infusions and/or
            withdrawals; length would depend on cashflow_type and the goal tenure
        end_date (str): Defines the end date of goal.Valid input format is date –
            ‘dd-mm-yyyy’
        scenario_type (ScenarioType3): Determines the type of the scenario, the
            suggested portfolio and the wealth glide path is created accordingly.
            ‘regular’ for regular goals accumulation goals where cash flows are
            positive (contributions) and with a typical target wealth
            ‘retirement’ for scenarios where a decumulation period is included: <br>
            1. Scenarios with an accumulation period (and an initial wealth) &
            positive cash flows followed by a decumulation period with withdrawals
            (negative cash flows) with or without an inheritance <br>
            2. Scenarios with an initial wealth followed by a decumulation period
            with or without an inheritance
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_id": "goal_id",
        "goal_value": "goalValue",
        "purpose": "purpose",
        "curr_wealth": "curr_wealth",
        "goal_priority": "goalPriority",
        "cashflow_type": "cashflowType",
        "cashflow": "cashflow",
        "end_date": "endDate",
        "scenario_type": "scenarioType",
        "cashflow_date": "cashflowDate",
        "goal_start_date": "goalStartDate",
    }

    _optionals = [
        "cashflow_date",
        "goal_start_date",
    ]

    _nullables = [
        "cashflow_date",
    ]

    def __init__(
        self,
        goal_id=None,
        goal_value=None,
        purpose=None,
        curr_wealth=None,
        goal_priority=None,
        cashflow_type=None,
        cashflow=None,
        end_date=None,
        scenario_type=None,
        cashflow_date=APIHelper.SKIP,
        goal_start_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoalProfileListWealthSplitterModel instance."""
        # Initialize members of the class
        self.goal_id = goal_id
        self.goal_value = goal_value
        self.purpose = purpose
        self.curr_wealth = curr_wealth
        if cashflow_date is not APIHelper.SKIP:
            self.cashflow_date = cashflow_date
        if goal_start_date is not APIHelper.SKIP:
            self.goal_start_date = goal_start_date
        self.goal_priority = goal_priority
        self.cashflow_type = cashflow_type
        self.cashflow = cashflow
        self.end_date = end_date
        self.scenario_type = scenario_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_id =\
            dictionary.get("goal_id")\
            if dictionary.get("goal_id")\
                else None
        goal_value =\
            dictionary.get("goalValue")\
            if dictionary.get("goalValue")\
                else None
        purpose =\
            dictionary.get("purpose")\
            if dictionary.get("purpose")\
                else None
        curr_wealth =\
            dictionary.get("curr_wealth")\
            if dictionary.get("curr_wealth")\
                else None
        goal_priority =\
            dictionary.get("goalPriority")\
            if dictionary.get("goalPriority")\
                else None
        cashflow_type =\
            dictionary.get("cashflowType")\
            if dictionary.get("cashflowType")\
                else None
        cashflow =\
            dictionary.get("cashflow")\
            if dictionary.get("cashflow")\
                else None
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else None
        scenario_type =\
            dictionary.get("scenarioType")\
            if dictionary.get("scenarioType")\
                else None
        cashflow_date =\
            dictionary.get("cashflowDate")\
            if "cashflowDate" in dictionary.keys()\
                else APIHelper.SKIP
        goal_start_date =\
            dictionary.get("goalStartDate")\
            if dictionary.get("goalStartDate")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_id,
                   goal_value,
                   purpose,
                   curr_wealth,
                   goal_priority,
                   cashflow_type,
                   cashflow,
                   end_date,
                   scenario_type,
                   cashflow_date,
                   goal_start_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_id=self.goal_id
        _goal_value=self.goal_value
        _purpose=self.purpose
        _curr_wealth=self.curr_wealth
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _goal_priority=self.goal_priority
        _cashflow_type=self.cashflow_type
        _cashflow=self.cashflow
        _end_date=self.end_date
        _scenario_type=self.scenario_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!r}, "
            f"goal_value={_goal_value!r}, "
            f"purpose={_purpose!r}, "
            f"curr_wealth={_curr_wealth!r}, "
            f"cashflow_date={_cashflow_date!r}, "
            f"goal_start_date={_goal_start_date!r}, "
            f"goal_priority={_goal_priority!r}, "
            f"cashflow_type={_cashflow_type!r}, "
            f"cashflow={_cashflow!r}, "
            f"end_date={_end_date!r}, "
            f"scenario_type={_scenario_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_id=self.goal_id
        _goal_value=self.goal_value
        _purpose=self.purpose
        _curr_wealth=self.curr_wealth
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _goal_priority=self.goal_priority
        _cashflow_type=self.cashflow_type
        _cashflow=self.cashflow
        _end_date=self.end_date
        _scenario_type=self.scenario_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_id={_goal_id!s}, "
            f"goal_value={_goal_value!s}, "
            f"purpose={_purpose!s}, "
            f"curr_wealth={_curr_wealth!s}, "
            f"cashflow_date={_cashflow_date!s}, "
            f"goal_start_date={_goal_start_date!s}, "
            f"goal_priority={_goal_priority!s}, "
            f"cashflow_type={_cashflow_type!s}, "
            f"cashflow={_cashflow!s}, "
            f"end_date={_end_date!s}, "
            f"scenario_type={_scenario_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
