"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.cash_flow_dict import CashFlowDict


class GoalCalculatorResponseBodyModel(object):
    """Implementation of the 'GoalCalculatorResponseBodyModel' model.

    Attributes:
        goal_amt (float): The model property of type float.
        infusions (List[float]): The model property of type List[float].
        cashflow (List[CashFlowDict]): The model property of type List[CashFlowDict].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_amt": "goalAmt",
        "infusions": "infusions",
        "cashflow": "cashflow",
    }

    _optionals = [
        "cashflow",
    ]

    def __init__(
        self,
        goal_amt=None,
        infusions=None,
        cashflow=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoalCalculatorResponseBodyModel instance."""
        # Initialize members of the class
        self.goal_amt = goal_amt
        self.infusions = infusions
        if cashflow is not APIHelper.SKIP:
            self.cashflow = cashflow

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_amt =\
            dictionary.get("goalAmt")\
            if dictionary.get("goalAmt")\
                else None
        infusions =\
            dictionary.get("infusions")\
            if dictionary.get("infusions")\
                else None
        cashflow = None
        if dictionary.get("cashflow") is not None:
            cashflow = [
                CashFlowDict.from_dictionary(x)
                    for x in dictionary.get("cashflow")
            ]
        else:
            cashflow = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(goal_amt,
                   infusions,
                   cashflow,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _goal_amt=self.goal_amt
        _infusions=self.infusions
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_amt={_goal_amt!r}, "
            f"infusions={_infusions!r}, "
            f"cashflow={_cashflow!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _goal_amt=self.goal_amt
        _infusions=self.infusions
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"goal_amt={_goal_amt!s}, "
            f"infusions={_infusions!s}, "
            f"cashflow={_cashflow!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
