"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.goal_profile_goe_for_taxes_attr import (
    GoalProfileGoeForTaxesAttr,
)
from goeapi.models.goe_to_account_attr import (
    GoeToAccountAttr,
)
from goeapi.models.household_goe_for_taxes_obj_2 import (
    HouseholdGoeForTaxesObj2,
)
from goeapi.models.policy_details import PolicyDetails
from goeapi.models.tax_rates_dic_2 import TaxRatesDic2


class GoeForTaxesInputModel(object):
    """Implementation of the 'GoeForTaxesInputModel' model.

    Attributes:
        reallocate (bool): If the client wants GOE to reallocate between the
            scheduled re-allocation dates, this should be set to ‘true’.
        is_new_risk_profile (bool): If the risk profile of the investor has changed,
            this is set to ‘true’.
            For first time calls to GOE, this needs to be set to ‘true’.
        is_new_investment_tenure (bool): If investor/end user changes the goal
            investment tenure after onboarding and before the next immediate
            re-allocation date,                                     this is set to
            ‘true’. For first time calls to GOE, this needs to be set to ‘true’.
        is_new_goal_priority (bool): If investor/end user changes the goal priority
            of any of the goals within the plan, in between the re-allocation dates,
            this is set to ‘true’.                                     For new plans,
            this needs to be ‘true’.
        is_near_term_volatility (bool): When the near-term volatility indicator
            flashes, this is set to ‘true’. Currently under development,
            shold be set to ‘false’.
        is_new_goal (bool): If the end user changes the goal amount / infusions /
            withdrawals, in between the re-allocation dates,                     this
            is set to ‘true’. For retirement scenarios, this would be a change in
            retirement income goal,                     while for a capital
            accumulation goal, this would be a change in the lumpsum accumulation
            target.                     For first time calls to GOE, this needs to be
            set to ‘true’.
        get_path (bool): Shows the forward-looking portfolio path over time.
        reallocation_freq (str): Describes the frequency of re-allocation.
        current_portfolio_id (int): Displays the current portfolio index that the
            goal is allocated to;                         if GOE is getting executed
            for the first time, it should be null.
        curr_date (str): This is an optional parameter that can be used to simulate
            the current date to be the specified value.                         GOE
            will process the request as if you are making the API call on the
            specified date. If not passed,                             the current
            system date will be used as the current date. Valid input format is date
            – ‘dd-mm-yyyy’
        risk_profile (RiskProfile2): Defines the user’s risk profile. Note that Risk
            Profiles are mapped to portfolio access.             For example, a
            Conservative investor has access to portfolios 1-8 (or 50% Equity) while
            an Aggressive             investor has access to all 16 portfolios (up to
            90% Equity). This is configurable.
        compute_social_security (bool): When set to true computes the social
            security.                 Mandatory fields (part of memberList) needed
            for social security are: “DOB”, “currentSalary”, “socialSecurityStartAge”
        use_social_security_for_goals (bool): When set to “true” uses Social Security
            to meet the withdrawals.             If set to “false”, and when
            'computeSocialSecurity' is set as 'true' - only computes the Social
            Security but does not use it to fulfil the goals.             In cases
            social security (post-tax) is greater than the withdrawal amount, the
            social security is collected into the taxable accounts.             If
            set to “true”, a taxable account must be present. This is because there
            can be instances where there are no goals in a given year but an incoming
            social security infusion.             This infusion can only go into a
            taxable account.
        cashflow_date (str): Cashflow date of the goal - this is the date (year is
            ignored) on which             infusions/withdrawals would be realized for
            the goal. This parameter is optional.                 If not passed or
            value is null, the algorithm would consider the first reallocation date
            as the cashflow date.                     Scheduled cashflows should be
            planned for a date prior to the 29th of any month.
        infusion_type (InfusionType2): Defines if the infusions are at the yearly
            level or monthly level.
        cola_rate (float): Defines the Cost-of-Living Adjustment to be used for
            Social Security amount computations.
        tax_rates (TaxRatesDic2): Consists of tax rates applicable pre &
            post-retirement for the entire household
        household (HouseholdGoeForTaxesObj2): contains all information about all the
            participants.
        accounts (List[GoeToAccountAttr]): Details of different accounts associated
            with unique memberID in the household.  <br>                    Note:
            <br>                    A single account can be associated with multiple
            members within the household.                     This would generally be
            the case with joint taxable accounts.
        goal_profile_list (List[GoalProfileGoeForTaxesAttr]): Details related to the
            withdrawals associated with the plan where a plan is defined as a
            collection of goals.
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        account_held_away (bool): To be set to True if the account is a held away
            account
        mean_return (float): Mean return value for the AHA account. Can be set to
            null or ignored if ‘accountHeldAway’ is set to False
        standard_deviation (float): Standard deviation for the AHA account. Can be
            set to null or ignored if ‘accountHeldAway’ is set to False
        equity_allocation (float): The Equity '%' for the AHA account. If this value
            is provided, the mean and standard deviation is mapped to the GOE managed
            portfolios. Can be set to null or ignored if ‘accountHeldAway’ is set to
            False.
        lock_expiry_date (str): The AHA account is considered locked and unavailable
            for withdrawals till this date. Note that however contributions and RMDs
            will always be processed. Can be set to null or ignored if
            ‘accountHeldAway’ is set to False.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "reallocate": "reallocate",
        "is_new_risk_profile": "isNewRiskProfile",
        "is_new_investment_tenure": "isNewInvestmentTenure",
        "is_new_goal_priority": "isNewGoalPriority",
        "is_new_goal": "isNewGoal",
        "get_path": "getPath",
        "reallocation_freq": "reallocationFreq",
        "current_portfolio_id": "currentPortfolioId",
        "risk_profile": "riskProfile",
        "infusion_type": "infusionType",
        "tax_rates": "taxRates",
        "household": "household",
        "accounts": "accounts",
        "goal_profile_list": "goalProfileList",
        "is_near_term_volatility": "isNearTermVolatility",
        "curr_date": "currDate",
        "compute_social_security": "computeSocialSecurity",
        "use_social_security_for_goals": "useSocialSecurityForGoals",
        "cashflow_date": "cashflowDate",
        "cola_rate": "colaRate",
        "policy": "policy",
        "account_held_away": "accountHeldAway",
        "mean_return": "meanReturn",
        "standard_deviation": "standardDeviation",
        "equity_allocation": "equityAllocation",
        "lock_expiry_date": "lockExpiryDate",
    }

    _optionals = [
        "is_near_term_volatility",
        "curr_date",
        "compute_social_security",
        "use_social_security_for_goals",
        "cashflow_date",
        "cola_rate",
        "policy",
        "account_held_away",
        "mean_return",
        "standard_deviation",
        "equity_allocation",
        "lock_expiry_date",
    ]

    _nullables = [
        "current_portfolio_id",
        "cashflow_date",
    ]

    def __init__(
        self,
        reallocate=None,
        is_new_risk_profile=None,
        is_new_investment_tenure=None,
        is_new_goal_priority=None,
        is_new_goal=None,
        get_path=None,
        current_portfolio_id=None,
        risk_profile=None,
        infusion_type=None,
        tax_rates=None,
        household=None,
        accounts=None,
        goal_profile_list=None,
        is_near_term_volatility=False,
        curr_date=APIHelper.SKIP,
        compute_social_security=False,
        use_social_security_for_goals=False,
        cashflow_date=APIHelper.SKIP,
        cola_rate=0,
        policy=APIHelper.SKIP,
        account_held_away=APIHelper.SKIP,
        mean_return=APIHelper.SKIP,
        standard_deviation=APIHelper.SKIP,
        equity_allocation=APIHelper.SKIP,
        lock_expiry_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoeForTaxesInputModel instance."""
        # Initialize members of the class
        self.reallocate = reallocate
        self.is_new_risk_profile = is_new_risk_profile
        self.is_new_investment_tenure = is_new_investment_tenure
        self.is_new_goal_priority = is_new_goal_priority
        self.is_near_term_volatility = is_near_term_volatility
        self.is_new_goal = is_new_goal
        self.get_path = get_path
        self.reallocation_freq = "yearly"
        self.current_portfolio_id = current_portfolio_id
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.risk_profile = risk_profile
        self.compute_social_security = compute_social_security
        self.use_social_security_for_goals = use_social_security_for_goals
        if cashflow_date is not APIHelper.SKIP:
            self.cashflow_date = cashflow_date
        self.infusion_type = infusion_type
        self.cola_rate = cola_rate
        self.tax_rates = tax_rates
        self.household = household
        self.accounts = accounts
        self.goal_profile_list = goal_profile_list
        if policy is not APIHelper.SKIP:
            self.policy = policy
        if account_held_away is not APIHelper.SKIP:
            self.account_held_away = account_held_away
        if mean_return is not APIHelper.SKIP:
            self.mean_return = mean_return
        if standard_deviation is not APIHelper.SKIP:
            self.standard_deviation = standard_deviation
        if equity_allocation is not APIHelper.SKIP:
            self.equity_allocation = equity_allocation
        if lock_expiry_date is not APIHelper.SKIP:
            self.lock_expiry_date = lock_expiry_date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        reallocate =\
            dictionary.get("reallocate")\
            if "reallocate" in dictionary.keys()\
                else None
        is_new_risk_profile =\
            dictionary.get("isNewRiskProfile")\
            if "isNewRiskProfile" in dictionary.keys()\
                else None
        is_new_investment_tenure =\
            dictionary.get("isNewInvestmentTenure")\
            if "isNewInvestmentTenure" in dictionary.keys()\
                else None
        is_new_goal_priority =\
            dictionary.get("isNewGoalPriority")\
            if "isNewGoalPriority" in dictionary.keys()\
                else None
        is_new_goal =\
            dictionary.get("isNewGoal")\
            if "isNewGoal" in dictionary.keys()\
                else None
        get_path =\
            dictionary.get("getPath")\
            if "getPath" in dictionary.keys()\
                else None
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if dictionary.get("currentPortfolioId")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        infusion_type =\
            dictionary.get("infusionType")\
            if dictionary.get("infusionType")\
                else None
        tax_rates =\
            TaxRatesDic2.from_dictionary(
                dictionary.get("taxRates"))\
                if dictionary.get("taxRates") else None
        household =\
            HouseholdGoeForTaxesObj2.from_dictionary(
                dictionary.get("household"))\
                if dictionary.get("household") else None
        accounts = None
        if dictionary.get("accounts") is not None:
            accounts = [
                GoeToAccountAttr.from_dictionary(x)
                    for x in dictionary.get("accounts")
            ]
        goal_profile_list = None
        if dictionary.get("goalProfileList") is not None:
            goal_profile_list = [
                GoalProfileGoeForTaxesAttr.from_dictionary(x)
                    for x in dictionary.get("goalProfileList")
            ]
        is_near_term_volatility =\
            dictionary.get("isNearTermVolatility")\
            if dictionary.get("isNearTermVolatility")\
                else False
        curr_date =\
            dictionary.get("currDate")\
            if dictionary.get("currDate")\
                else APIHelper.SKIP
        compute_social_security =\
            dictionary.get("computeSocialSecurity")\
            if dictionary.get("computeSocialSecurity")\
                else False
        use_social_security_for_goals =\
            dictionary.get("useSocialSecurityForGoals")\
            if dictionary.get("useSocialSecurityForGoals")\
                else False
        cashflow_date =\
            dictionary.get("cashflowDate")\
            if "cashflowDate" in dictionary.keys()\
                else APIHelper.SKIP
        cola_rate =\
            dictionary.get("colaRate")\
            if dictionary.get("colaRate")\
                else 0
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP
        account_held_away =\
            dictionary.get("accountHeldAway")\
            if "accountHeldAway" in dictionary.keys()\
                else APIHelper.SKIP
        mean_return =\
            dictionary.get("meanReturn")\
            if dictionary.get("meanReturn")\
                else APIHelper.SKIP
        standard_deviation =\
            dictionary.get("standardDeviation")\
            if dictionary.get("standardDeviation")\
                else APIHelper.SKIP
        equity_allocation =\
            dictionary.get("equityAllocation")\
            if dictionary.get("equityAllocation")\
                else APIHelper.SKIP
        lock_expiry_date =\
            dictionary.get("lockExpiryDate")\
            if dictionary.get("lockExpiryDate")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(reallocate,
                   is_new_risk_profile,
                   is_new_investment_tenure,
                   is_new_goal_priority,
                   is_new_goal,
                   get_path,
                   current_portfolio_id,
                   risk_profile,
                   infusion_type,
                   tax_rates,
                   household,
                   accounts,
                   goal_profile_list,
                   is_near_term_volatility,
                   curr_date,
                   compute_social_security,
                   use_social_security_for_goals,
                   cashflow_date,
                   cola_rate,
                   policy,
                   account_held_away,
                   mean_return,
                   standard_deviation,
                   equity_allocation,
                   lock_expiry_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _reallocate=self.reallocate
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_goal_priority=self.is_new_goal_priority
        _is_near_term_volatility=(
            self.is_near_term_volatility
            if hasattr(self, "is_near_term_volatility")
            else None
        )
        _is_new_goal=self.is_new_goal
        _get_path=self.get_path
        _reallocation_freq=self.reallocation_freq
        _current_portfolio_id=self.current_portfolio_id
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _compute_social_security=(
            self.compute_social_security
            if hasattr(self, "compute_social_security")
            else None
        )
        _use_social_security_for_goals=(
            self.use_social_security_for_goals
            if hasattr(self, "use_social_security_for_goals")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _infusion_type=self.infusion_type
        _cola_rate=(
            self.cola_rate
            if hasattr(self, "cola_rate")
            else None
        )
        _tax_rates=self.tax_rates
        _household=self.household
        _accounts=self.accounts
        _goal_profile_list=self.goal_profile_list
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _account_held_away=(
            self.account_held_away
            if hasattr(self, "account_held_away")
            else None
        )
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _equity_allocation=(
            self.equity_allocation
            if hasattr(self, "equity_allocation")
            else None
        )
        _lock_expiry_date=(
            self.lock_expiry_date
            if hasattr(self, "lock_expiry_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reallocate={_reallocate!r}, "
            f"is_new_risk_profile={_is_new_risk_profile!r}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!r}, "
            f"is_new_goal_priority={_is_new_goal_priority!r}, "
            f"is_near_term_volatility={_is_near_term_volatility!r}, "
            f"is_new_goal={_is_new_goal!r}, "
            f"get_path={_get_path!r}, "
            f"reallocation_freq={_reallocation_freq!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"curr_date={_curr_date!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"compute_social_security={_compute_social_security!r}, "
            f"use_social_security_for_goals={_use_social_security_for_goals!r}, "
            f"cashflow_date={_cashflow_date!r}, "
            f"infusion_type={_infusion_type!r}, "
            f"cola_rate={_cola_rate!r}, "
            f"tax_rates={_tax_rates!r}, "
            f"household={_household!r}, "
            f"accounts={_accounts!r}, "
            f"goal_profile_list={_goal_profile_list!r}, "
            f"policy={_policy!r}, "
            f"account_held_away={_account_held_away!r}, "
            f"mean_return={_mean_return!r}, "
            f"standard_deviation={_standard_deviation!r}, "
            f"equity_allocation={_equity_allocation!r}, "
            f"lock_expiry_date={_lock_expiry_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _reallocate=self.reallocate
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_goal_priority=self.is_new_goal_priority
        _is_near_term_volatility=(
            self.is_near_term_volatility
            if hasattr(self, "is_near_term_volatility")
            else None
        )
        _is_new_goal=self.is_new_goal
        _get_path=self.get_path
        _reallocation_freq=self.reallocation_freq
        _current_portfolio_id=self.current_portfolio_id
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _compute_social_security=(
            self.compute_social_security
            if hasattr(self, "compute_social_security")
            else None
        )
        _use_social_security_for_goals=(
            self.use_social_security_for_goals
            if hasattr(self, "use_social_security_for_goals")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _infusion_type=self.infusion_type
        _cola_rate=(
            self.cola_rate
            if hasattr(self, "cola_rate")
            else None
        )
        _tax_rates=self.tax_rates
        _household=self.household
        _accounts=self.accounts
        _goal_profile_list=self.goal_profile_list
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _account_held_away=(
            self.account_held_away
            if hasattr(self, "account_held_away")
            else None
        )
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _equity_allocation=(
            self.equity_allocation
            if hasattr(self, "equity_allocation")
            else None
        )
        _lock_expiry_date=(
            self.lock_expiry_date
            if hasattr(self, "lock_expiry_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reallocate={_reallocate!s}, "
            f"is_new_risk_profile={_is_new_risk_profile!s}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!s}, "
            f"is_new_goal_priority={_is_new_goal_priority!s}, "
            f"is_near_term_volatility={_is_near_term_volatility!s}, "
            f"is_new_goal={_is_new_goal!s}, "
            f"get_path={_get_path!s}, "
            f"reallocation_freq={_reallocation_freq!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"curr_date={_curr_date!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"compute_social_security={_compute_social_security!s}, "
            f"use_social_security_for_goals={_use_social_security_for_goals!s}, "
            f"cashflow_date={_cashflow_date!s}, "
            f"infusion_type={_infusion_type!s}, "
            f"cola_rate={_cola_rate!s}, "
            f"tax_rates={_tax_rates!s}, "
            f"household={_household!s}, "
            f"accounts={_accounts!s}, "
            f"goal_profile_list={_goal_profile_list!s}, "
            f"policy={_policy!s}, "
            f"account_held_away={_account_held_away!s}, "
            f"mean_return={_mean_return!s}, "
            f"standard_deviation={_standard_deviation!s}, "
            f"equity_allocation={_equity_allocation!s}, "
            f"lock_expiry_date={_lock_expiry_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
