"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.annuity_price import AnnuityPrice
from goeapi.models.policy_details import PolicyDetails


class GoeWithAnnuitiesInputModel(object):
    """Implementation of the 'GoeWithAnnuitiesInputModel' model.

    Attributes:
        include_annuities (bool): Flag to recommend allocation to annuities.
        annuity_type (str): Type of annuity. [non-functional]
        annuity_price (List[AnnuityPrice]): Annuity price series         Mandatory
            only if includeAnnuities is true.         For a deferred annuity -
            complete age year rate         table to be passed covering all ages from
            current age to retirement age. This rate determines the monthly payout.
        date_of_birth (str): Participant’s date of birth.<br>            Accepts date
            in dd-mm-yyyy & mm-yyyy format.
        retirement_age (int): Participant’s retirement age. <br>            Accepts
            positive numbers only.
        drawdown_age (int): Participant’s drawdown age. <br>            Accepts
            positive numbers, greater than or equal to the retirementAge.
        planning_age (int): Age of last withdrawal. <br>            Accepts positive
            numbers, greater than the drawdownAge.
        current_salary (float): Participant’s current salary. <br>            Accepts
            positive numbers with up to 2 decimal places. Should always be passed as
            annual income.
        total_account_balance (float): Total balance in the account. <br>
            Valid values: positive numbers with up to 2 decimal places.
        periodic_contributions (float): Periodic contribution amount.<br>
            Valid values: positive numbers with up to 2 decimal places. Represented
            as a dollar value.
        contribution_freq (ContributionFreq): Frequency of the periodic contributions.
        current_annuity_balance (float): Current balance of annuity assets.<br>
            Valid values: positive numbers with up to 2 decimal places. <br>
            Only one of annuityBalance or annuityIncome can be sent,
            both cannot have values, one needs to be “null”.
        current_annuity_income (float): Current accumulated yearly income from
            annuity as of the             drawdown age. <br>            Valid values:
            positive numbers with up to 2 decimal places. <br>                 Only
            one of annuityBalance or annuityIncome can be sent,
            both cannot have values, one needs to be “null”.
        retirement_income_goal (float): Total yearly retirement income goal for the
            participant.<br>            Valid values: positive numbers with up to 2
            decimal places.
        drawdown_age_ss (int): Participant’s social security drawdown age. <br>
            Valid values: positive whole numbers, greater than or equal to retirement
            age.
        income_from_ss (float): Total yearly income from the participant from social
            security. <br>            Valid inputs: positive numbers with up to 2
            decimal places.
        outside_assets (float): Total balance in outside assets <br>        Valid
            inputs: positive numbers with up to 2 decimal places.
        other_income (float): Income from other sources. This is the sum of income
            from DB and             other annuities. <br>            Valid inputs:
            positive numbers with up to 2 decimal places.<br>                Should
            always be passed as annual income.
        current_portfolio_id (int): Current portfolio ID to which the wealth is
            allocated. If GOE             is being called for the first time, this
            should be null. [non-functional] <br>            Valid inputs: null or
            positive integers.
        calculate_retirement_income_goal (bool): Flag to ask GOE to calculate the
            retirement income goal
        current_date (str): Participant’s current date. <br>            Valid input:
            date in dd-mm-yyyy format
        risk_profile (RiskProfile4): Participant’s risk profile.
        other_guaranteed_income (float): Income from other guaranteed income sources.
            <br>            Valid inputs are numbers with up to 2 decimal places.
        reallocate (bool): Flag to ask GOE with Annuities to send updated portfolio
            advice. Sent as true when new advice is needed, else sent as false
        fixed_discretionary_split (float): Proportion of the fixed expenses as a
            proportion of total goal. Valid inputs up to 4 decimal places
        plan_id (str): Plan ID of the participant.
        participant_id (str): ID of the participant.
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        user_input_update (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "include_annuities": "includeAnnuities",
        "annuity_type": "annuityType",
        "date_of_birth": "dateOfBirth",
        "retirement_age": "retirementAge",
        "drawdown_age": "drawdownAge",
        "planning_age": "planningAge",
        "current_salary": "currentSalary",
        "total_account_balance": "totalAccountBalance",
        "periodic_contributions": "periodicContributions",
        "contribution_freq": "contributionFreq",
        "outside_assets": "outsideAssets",
        "current_portfolio_id": "currentPortfolioId",
        "current_date": "currentDate",
        "risk_profile": "riskProfile",
        "other_guaranteed_income": "otherGuaranteedIncome",
        "reallocate": "reallocate",
        "user_input_update": "userInputUpdate",
        "annuity_price": "annuityPrice",
        "current_annuity_balance": "currentAnnuityBalance",
        "current_annuity_income": "currentAnnuityIncome",
        "retirement_income_goal": "retirementIncomeGoal",
        "drawdown_age_ss": "drawdownAgeSS",
        "income_from_ss": "incomeFromSS",
        "other_income": "otherIncome",
        "calculate_retirement_income_goal": "calculateRetirementIncomeGoal",
        "fixed_discretionary_split": "fixedDiscretionarySplit",
        "plan_id": "planID",
        "participant_id": "participantID",
        "policy": "policy",
    }

    _optionals = [
        "annuity_price",
        "current_annuity_balance",
        "current_annuity_income",
        "retirement_income_goal",
        "drawdown_age_ss",
        "income_from_ss",
        "other_income",
        "calculate_retirement_income_goal",
        "fixed_discretionary_split",
        "plan_id",
        "participant_id",
        "policy",
    ]

    _nullables = [
        "current_portfolio_id",
        "plan_id",
        "participant_id",
    ]

    def __init__(
        self,
        include_annuities=None,
        date_of_birth=None,
        retirement_age=None,
        drawdown_age=None,
        planning_age=None,
        current_salary=None,
        total_account_balance=None,
        periodic_contributions=None,
        contribution_freq=None,
        outside_assets=None,
        current_portfolio_id=None,
        current_date=None,
        risk_profile=None,
        other_guaranteed_income=None,
        reallocate=None,
        user_input_update=None,
        annuity_price=APIHelper.SKIP,
        current_annuity_balance=APIHelper.SKIP,
        current_annuity_income=APIHelper.SKIP,
        retirement_income_goal=APIHelper.SKIP,
        drawdown_age_ss=APIHelper.SKIP,
        income_from_ss=0,
        other_income=APIHelper.SKIP,
        calculate_retirement_income_goal=APIHelper.SKIP,
        fixed_discretionary_split=APIHelper.SKIP,
        plan_id=APIHelper.SKIP,
        participant_id=APIHelper.SKIP,
        policy=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoeWithAnnuitiesInputModel instance."""
        # Initialize members of the class
        self.include_annuities = include_annuities
        self.annuity_type = "deferred"
        if annuity_price is not APIHelper.SKIP:
            self.annuity_price = annuity_price
        self.date_of_birth = date_of_birth
        self.retirement_age = retirement_age
        self.drawdown_age = drawdown_age
        self.planning_age = planning_age
        self.current_salary = current_salary
        self.total_account_balance = total_account_balance
        self.periodic_contributions = periodic_contributions
        self.contribution_freq = contribution_freq
        if current_annuity_balance is not APIHelper.SKIP:
            self.current_annuity_balance = current_annuity_balance
        if current_annuity_income is not APIHelper.SKIP:
            self.current_annuity_income = current_annuity_income
        if retirement_income_goal is not APIHelper.SKIP:
            self.retirement_income_goal = retirement_income_goal
        if drawdown_age_ss is not APIHelper.SKIP:
            self.drawdown_age_ss = drawdown_age_ss
        self.income_from_ss = income_from_ss
        self.outside_assets = outside_assets
        if other_income is not APIHelper.SKIP:
            self.other_income = other_income
        self.current_portfolio_id = current_portfolio_id
        if calculate_retirement_income_goal is not APIHelper.SKIP:
            self.calculate_retirement_income_goal = calculate_retirement_income_goal
        self.current_date = current_date
        self.risk_profile = risk_profile
        self.other_guaranteed_income = other_guaranteed_income
        self.reallocate = reallocate
        if fixed_discretionary_split is not APIHelper.SKIP:
            self.fixed_discretionary_split = fixed_discretionary_split
        if plan_id is not APIHelper.SKIP:
            self.plan_id = plan_id
        if participant_id is not APIHelper.SKIP:
            self.participant_id = participant_id
        if policy is not APIHelper.SKIP:
            self.policy = policy
        self.user_input_update = user_input_update

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        include_annuities =\
            dictionary.get("includeAnnuities")\
            if "includeAnnuities" in dictionary.keys()\
                else None
        date_of_birth =\
            dictionary.get("dateOfBirth")\
            if dictionary.get("dateOfBirth")\
                else None
        retirement_age =\
            dictionary.get("retirementAge")\
            if dictionary.get("retirementAge")\
                else None
        drawdown_age =\
            dictionary.get("drawdownAge")\
            if dictionary.get("drawdownAge")\
                else None
        planning_age =\
            dictionary.get("planningAge")\
            if dictionary.get("planningAge")\
                else None
        current_salary =\
            dictionary.get("currentSalary")\
            if dictionary.get("currentSalary")\
                else None
        total_account_balance =\
            dictionary.get("totalAccountBalance")\
            if dictionary.get("totalAccountBalance")\
                else None
        periodic_contributions =\
            dictionary.get("periodicContributions")\
            if dictionary.get("periodicContributions")\
                else None
        contribution_freq =\
            dictionary.get("contributionFreq")\
            if dictionary.get("contributionFreq")\
                else None
        outside_assets =\
            dictionary.get("outsideAssets")\
            if dictionary.get("outsideAssets")\
                else None
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if dictionary.get("currentPortfolioId")\
                else None
        current_date =\
            dictionary.get("currentDate")\
            if dictionary.get("currentDate")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        other_guaranteed_income =\
            dictionary.get("otherGuaranteedIncome")\
            if dictionary.get("otherGuaranteedIncome")\
                else None
        reallocate =\
            dictionary.get("reallocate")\
            if "reallocate" in dictionary.keys()\
                else None
        user_input_update =\
            dictionary.get("userInputUpdate")\
            if "userInputUpdate" in dictionary.keys()\
                else None
        annuity_price = None
        if dictionary.get("annuityPrice") is not None:
            annuity_price = [
                AnnuityPrice.from_dictionary(x)
                    for x in dictionary.get("annuityPrice")
            ]
        else:
            annuity_price = APIHelper.SKIP
        current_annuity_balance =\
            dictionary.get("currentAnnuityBalance")\
            if dictionary.get("currentAnnuityBalance")\
                else APIHelper.SKIP
        current_annuity_income =\
            dictionary.get("currentAnnuityIncome")\
            if dictionary.get("currentAnnuityIncome")\
                else APIHelper.SKIP
        retirement_income_goal =\
            dictionary.get("retirementIncomeGoal")\
            if dictionary.get("retirementIncomeGoal")\
                else APIHelper.SKIP
        drawdown_age_ss =\
            dictionary.get("drawdownAgeSS")\
            if dictionary.get("drawdownAgeSS")\
                else APIHelper.SKIP
        income_from_ss =\
            dictionary.get("incomeFromSS")\
            if dictionary.get("incomeFromSS")\
                else 0
        other_income =\
            dictionary.get("otherIncome")\
            if dictionary.get("otherIncome")\
                else APIHelper.SKIP
        calculate_retirement_income_goal =\
            dictionary.get("calculateRetirementIncomeGoal")\
            if "calculateRetirementIncomeGoal" in dictionary.keys()\
                else APIHelper.SKIP
        fixed_discretionary_split =\
            dictionary.get("fixedDiscretionarySplit")\
            if dictionary.get("fixedDiscretionarySplit")\
                else APIHelper.SKIP
        plan_id =\
            dictionary.get("planID")\
            if "planID" in dictionary.keys()\
                else APIHelper.SKIP
        participant_id =\
            dictionary.get("participantID")\
            if "participantID" in dictionary.keys()\
                else APIHelper.SKIP
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(include_annuities,
                   date_of_birth,
                   retirement_age,
                   drawdown_age,
                   planning_age,
                   current_salary,
                   total_account_balance,
                   periodic_contributions,
                   contribution_freq,
                   outside_assets,
                   current_portfolio_id,
                   current_date,
                   risk_profile,
                   other_guaranteed_income,
                   reallocate,
                   user_input_update,
                   annuity_price,
                   current_annuity_balance,
                   current_annuity_income,
                   retirement_income_goal,
                   drawdown_age_ss,
                   income_from_ss,
                   other_income,
                   calculate_retirement_income_goal,
                   fixed_discretionary_split,
                   plan_id,
                   participant_id,
                   policy,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _include_annuities=self.include_annuities
        _annuity_type=self.annuity_type
        _annuity_price=(
            self.annuity_price
            if hasattr(self, "annuity_price")
            else None
        )
        _date_of_birth=self.date_of_birth
        _retirement_age=self.retirement_age
        _drawdown_age=self.drawdown_age
        _planning_age=self.planning_age
        _current_salary=self.current_salary
        _total_account_balance=self.total_account_balance
        _periodic_contributions=self.periodic_contributions
        _contribution_freq=self.contribution_freq
        _current_annuity_balance=(
            self.current_annuity_balance
            if hasattr(self, "current_annuity_balance")
            else None
        )
        _current_annuity_income=(
            self.current_annuity_income
            if hasattr(self, "current_annuity_income")
            else None
        )
        _retirement_income_goal=(
            self.retirement_income_goal
            if hasattr(self, "retirement_income_goal")
            else None
        )
        _drawdown_age_ss=(
            self.drawdown_age_ss
            if hasattr(self, "drawdown_age_ss")
            else None
        )
        _income_from_ss=(
            self.income_from_ss
            if hasattr(self, "income_from_ss")
            else None
        )
        _outside_assets=self.outside_assets
        _other_income=(
            self.other_income
            if hasattr(self, "other_income")
            else None
        )
        _current_portfolio_id=self.current_portfolio_id
        _calculate_retirement_income_goal=(
            self.calculate_retirement_income_goal
            if hasattr(self, "calculate_retirement_income_goal")
            else None
        )
        _current_date=self.current_date
        _risk_profile=self.risk_profile
        _other_guaranteed_income=self.other_guaranteed_income
        _reallocate=self.reallocate
        _fixed_discretionary_split=(
            self.fixed_discretionary_split
            if hasattr(self, "fixed_discretionary_split")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _user_input_update=self.user_input_update
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"include_annuities={_include_annuities!r}, "
            f"annuity_type={_annuity_type!r}, "
            f"annuity_price={_annuity_price!r}, "
            f"date_of_birth={_date_of_birth!r}, "
            f"retirement_age={_retirement_age!r}, "
            f"drawdown_age={_drawdown_age!r}, "
            f"planning_age={_planning_age!r}, "
            f"current_salary={_current_salary!r}, "
            f"total_account_balance={_total_account_balance!r}, "
            f"periodic_contributions={_periodic_contributions!r}, "
            f"contribution_freq={_contribution_freq!r}, "
            f"current_annuity_balance={_current_annuity_balance!r}, "
            f"current_annuity_income={_current_annuity_income!r}, "
            f"retirement_income_goal={_retirement_income_goal!r}, "
            f"drawdown_age_ss={_drawdown_age_ss!r}, "
            f"income_from_ss={_income_from_ss!r}, "
            f"outside_assets={_outside_assets!r}, "
            f"other_income={_other_income!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"calculate_retirement_income_goal={_calculate_retirement_income_goal!r}, "
            f"current_date={_current_date!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"other_guaranteed_income={_other_guaranteed_income!r}, "
            f"reallocate={_reallocate!r}, "
            f"fixed_discretionary_split={_fixed_discretionary_split!r}, "
            f"plan_id={_plan_id!r}, "
            f"participant_id={_participant_id!r}, "
            f"policy={_policy!r}, "
            f"user_input_update={_user_input_update!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _include_annuities=self.include_annuities
        _annuity_type=self.annuity_type
        _annuity_price=(
            self.annuity_price
            if hasattr(self, "annuity_price")
            else None
        )
        _date_of_birth=self.date_of_birth
        _retirement_age=self.retirement_age
        _drawdown_age=self.drawdown_age
        _planning_age=self.planning_age
        _current_salary=self.current_salary
        _total_account_balance=self.total_account_balance
        _periodic_contributions=self.periodic_contributions
        _contribution_freq=self.contribution_freq
        _current_annuity_balance=(
            self.current_annuity_balance
            if hasattr(self, "current_annuity_balance")
            else None
        )
        _current_annuity_income=(
            self.current_annuity_income
            if hasattr(self, "current_annuity_income")
            else None
        )
        _retirement_income_goal=(
            self.retirement_income_goal
            if hasattr(self, "retirement_income_goal")
            else None
        )
        _drawdown_age_ss=(
            self.drawdown_age_ss
            if hasattr(self, "drawdown_age_ss")
            else None
        )
        _income_from_ss=(
            self.income_from_ss
            if hasattr(self, "income_from_ss")
            else None
        )
        _outside_assets=self.outside_assets
        _other_income=(
            self.other_income
            if hasattr(self, "other_income")
            else None
        )
        _current_portfolio_id=self.current_portfolio_id
        _calculate_retirement_income_goal=(
            self.calculate_retirement_income_goal
            if hasattr(self, "calculate_retirement_income_goal")
            else None
        )
        _current_date=self.current_date
        _risk_profile=self.risk_profile
        _other_guaranteed_income=self.other_guaranteed_income
        _reallocate=self.reallocate
        _fixed_discretionary_split=(
            self.fixed_discretionary_split
            if hasattr(self, "fixed_discretionary_split")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _user_input_update=self.user_input_update
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"include_annuities={_include_annuities!s}, "
            f"annuity_type={_annuity_type!s}, "
            f"annuity_price={_annuity_price!s}, "
            f"date_of_birth={_date_of_birth!s}, "
            f"retirement_age={_retirement_age!s}, "
            f"drawdown_age={_drawdown_age!s}, "
            f"planning_age={_planning_age!s}, "
            f"current_salary={_current_salary!s}, "
            f"total_account_balance={_total_account_balance!s}, "
            f"periodic_contributions={_periodic_contributions!s}, "
            f"contribution_freq={_contribution_freq!s}, "
            f"current_annuity_balance={_current_annuity_balance!s}, "
            f"current_annuity_income={_current_annuity_income!s}, "
            f"retirement_income_goal={_retirement_income_goal!s}, "
            f"drawdown_age_ss={_drawdown_age_ss!s}, "
            f"income_from_ss={_income_from_ss!s}, "
            f"outside_assets={_outside_assets!s}, "
            f"other_income={_other_income!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"calculate_retirement_income_goal={_calculate_retirement_income_goal!s}, "
            f"current_date={_current_date!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"other_guaranteed_income={_other_guaranteed_income!s}, "
            f"reallocate={_reallocate!s}, "
            f"fixed_discretionary_split={_fixed_discretionary_split!s}, "
            f"plan_id={_plan_id!s}, "
            f"participant_id={_participant_id!s}, "
            f"policy={_policy!s}, "
            f"user_input_update={_user_input_update!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
