"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class GoeWithAnnuitiesOutputModel(object):
    """Implementation of the 'GoeWithAnnuitiesOutputModel' model.

    Attributes:
        retirement_goal (float): Recommended yearly retirement income goal
        retirement_goal_min (float): Minimum recommended yearly retirement income goal
        retirement_goal_max (float): Maximum recommended yearly retirement income goal
        income_from_outside_assets (float): Projected income from outside assets.
        income_from_ss (float): Projected Social Security income
        income_from_others (float): Projected income from other sources.
        allocation_to_annuities (float): Balance to be allocated to annuities.
        allocation_to_goe (float): Balance to be allocated to GOE.
        recommended_portfolio_id (int): Recommended portfolio index for the
            participant.
        retirement_goal_probability (float): Probability of achieving the retirement
            goal
        recommended_consumption (float): Recommended yearly consumption
        rmd (float): Recommended RMD distribution. Null before RMD start age and
            valid value above RMD start age.
        income_from_guaranteed (float): Income from other non-guaranteed sources.
        monthly_topup_accumulation (float): Save more recommendation.
        monthly_topup_decumulation (float): Spend less recommendation.
        yearly_topup_accumulation (float): Save more recommendation.
        yearly_topup_decumulation (float): Spend less recommendation.
        recommended_tenure (str): Retire later recommendation.
        income_from_goe (float): Projected income from GOE account.
        income_from_annuities (float): Projected income from annuities.
        portfolio_path (List[int]): GOE’s expected portfolio path across the goal
            tenure.(corresponding to the date). <br>            Note: Represents the
            portfolios to be allocated into at the beginning of each re-allocation
            date. Asset class allocations corresponding to the portfolio indexes to
            be shown on the front end.
        wealth_path (List[float] | Dict[str, Any]): Priority based path of wealth
            across the investment tenure (corresponding to the end of each
            reallocation date).             If additional wealth paths are requested,
            a dictionary of 3 wealth paths and wealth path percentiles is returned –
            covered in the next 2 rows. <br>                Note: It Is denoted as a
            rounded number with a currency suffix ($921,537)
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "retirement_goal": "retirementGoal",
        "retirement_goal_min": "retirementGoalMin",
        "retirement_goal_max": "retirementGoalMax",
        "income_from_outside_assets": "incomeFromOutsideAssets",
        "income_from_ss": "incomeFromSS",
        "income_from_others": "incomeFromOthers",
        "allocation_to_annuities": "allocationToAnnuities",
        "allocation_to_goe": "allocationToGOE",
        "recommended_portfolio_id": "recommendedPortfolioID",
        "retirement_goal_probability": "retirementGoalProbability",
        "recommended_consumption": "recommendedConsumption",
        "rmd": "RMD",
        "income_from_guaranteed": "incomeFromGuaranteed",
        "monthly_topup_accumulation": "monthlyTopupAccumulation",
        "monthly_topup_decumulation": "monthlyTopupDecumulation",
        "yearly_topup_accumulation": "yearlyTopupAccumulation",
        "yearly_topup_decumulation": "yearlyTopupDecumulation",
        "recommended_tenure": "recommendedTenure",
        "income_from_goe": "incomeFromGOE",
        "income_from_annuities": "incomeFromAnnuities",
        "portfolio_path": "portfolioPath",
        "wealth_path": "wealthPath",
    }

    def __init__(
        self,
        retirement_goal=None,
        retirement_goal_min=None,
        retirement_goal_max=None,
        income_from_outside_assets=None,
        income_from_ss=None,
        income_from_others=None,
        allocation_to_annuities=None,
        allocation_to_goe=None,
        recommended_portfolio_id=None,
        retirement_goal_probability=None,
        recommended_consumption=None,
        rmd=None,
        income_from_guaranteed=None,
        monthly_topup_accumulation=None,
        monthly_topup_decumulation=None,
        yearly_topup_accumulation=None,
        yearly_topup_decumulation=None,
        recommended_tenure=None,
        income_from_goe=None,
        income_from_annuities=None,
        portfolio_path=None,
        wealth_path=None,
        additional_properties=None):
        """Initialize a GoeWithAnnuitiesOutputModel instance."""
        # Initialize members of the class
        self.retirement_goal = retirement_goal
        self.retirement_goal_min = retirement_goal_min
        self.retirement_goal_max = retirement_goal_max
        self.income_from_outside_assets = income_from_outside_assets
        self.income_from_ss = income_from_ss
        self.income_from_others = income_from_others
        self.allocation_to_annuities = allocation_to_annuities
        self.allocation_to_goe = allocation_to_goe
        self.recommended_portfolio_id = recommended_portfolio_id
        self.retirement_goal_probability = retirement_goal_probability
        self.recommended_consumption = recommended_consumption
        self.rmd = rmd
        self.income_from_guaranteed = income_from_guaranteed
        self.monthly_topup_accumulation = monthly_topup_accumulation
        self.monthly_topup_decumulation = monthly_topup_decumulation
        self.yearly_topup_accumulation = yearly_topup_accumulation
        self.yearly_topup_decumulation = yearly_topup_decumulation
        self.recommended_tenure = recommended_tenure
        self.income_from_goe = income_from_goe
        self.income_from_annuities = income_from_annuities
        self.portfolio_path = portfolio_path
        self.wealth_path = wealth_path

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        retirement_goal =\
            dictionary.get("retirementGoal")\
            if dictionary.get("retirementGoal")\
                else None
        retirement_goal_min =\
            dictionary.get("retirementGoalMin")\
            if dictionary.get("retirementGoalMin")\
                else None
        retirement_goal_max =\
            dictionary.get("retirementGoalMax")\
            if dictionary.get("retirementGoalMax")\
                else None
        income_from_outside_assets =\
            dictionary.get("incomeFromOutsideAssets")\
            if dictionary.get("incomeFromOutsideAssets")\
                else None
        income_from_ss =\
            dictionary.get("incomeFromSS")\
            if dictionary.get("incomeFromSS")\
                else None
        income_from_others =\
            dictionary.get("incomeFromOthers")\
            if dictionary.get("incomeFromOthers")\
                else None
        allocation_to_annuities =\
            dictionary.get("allocationToAnnuities")\
            if dictionary.get("allocationToAnnuities")\
                else None
        allocation_to_goe =\
            dictionary.get("allocationToGOE")\
            if dictionary.get("allocationToGOE")\
                else None
        recommended_portfolio_id =\
            dictionary.get("recommendedPortfolioID")\
            if dictionary.get("recommendedPortfolioID")\
                else None
        retirement_goal_probability =\
            dictionary.get("retirementGoalProbability")\
            if dictionary.get("retirementGoalProbability")\
                else None
        recommended_consumption =\
            dictionary.get("recommendedConsumption")\
            if dictionary.get("recommendedConsumption")\
                else None
        rmd =\
            dictionary.get("RMD")\
            if dictionary.get("RMD")\
                else None
        income_from_guaranteed =\
            dictionary.get("incomeFromGuaranteed")\
            if dictionary.get("incomeFromGuaranteed")\
                else None
        monthly_topup_accumulation =\
            dictionary.get("monthlyTopupAccumulation")\
            if dictionary.get("monthlyTopupAccumulation")\
                else None
        monthly_topup_decumulation =\
            dictionary.get("monthlyTopupDecumulation")\
            if dictionary.get("monthlyTopupDecumulation")\
                else None
        yearly_topup_accumulation =\
            dictionary.get("yearlyTopupAccumulation")\
            if dictionary.get("yearlyTopupAccumulation")\
                else None
        yearly_topup_decumulation =\
            dictionary.get("yearlyTopupDecumulation")\
            if dictionary.get("yearlyTopupDecumulation")\
                else None
        recommended_tenure =\
            dictionary.get("recommendedTenure")\
            if dictionary.get("recommendedTenure")\
                else None
        income_from_goe =\
            dictionary.get("incomeFromGOE")\
            if dictionary.get("incomeFromGOE")\
                else None
        income_from_annuities =\
            dictionary.get("incomeFromAnnuities")\
            if dictionary.get("incomeFromAnnuities")\
                else None
        portfolio_path =\
            dictionary.get("portfolioPath")\
            if dictionary.get("portfolioPath")\
                else None
        wealth_path = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("GoeWithAnnuitiesOutputModelWealthPath"),
            dictionary.get("wealthPath"),
            False)\
            if dictionary.get("wealthPath") is not None\
            else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(retirement_goal,
                   retirement_goal_min,
                   retirement_goal_max,
                   income_from_outside_assets,
                   income_from_ss,
                   income_from_others,
                   allocation_to_annuities,
                   allocation_to_goe,
                   recommended_portfolio_id,
                   retirement_goal_probability,
                   recommended_consumption,
                   rmd,
                   income_from_guaranteed,
                   monthly_topup_accumulation,
                   monthly_topup_decumulation,
                   yearly_topup_accumulation,
                   yearly_topup_decumulation,
                   recommended_tenure,
                   income_from_goe,
                   income_from_annuities,
                   portfolio_path,
                   wealth_path,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.retirement_goal,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.retirement_goal_min,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.retirement_goal_max,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_outside_assets,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_ss,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_others,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.allocation_to_annuities,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.allocation_to_goe,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.recommended_portfolio_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.retirement_goal_probability,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.recommended_consumption,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.rmd,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_guaranteed,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.monthly_topup_accumulation,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.monthly_topup_decumulation,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.yearly_topup_accumulation,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.yearly_topup_decumulation,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.recommended_tenure,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_goe,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.income_from_annuities,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        float,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.portfolio_path,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                )) \
                and (UnionTypeLookUp.get("GoeWithAnnuitiesOutputModelWealthPath")
                .validate(dictionary.wealth_path).is_valid)

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("retirementGoal"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("retirementGoalMin"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("retirementGoalMax"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromOutsideAssets"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromSS"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromOthers"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("allocationToAnnuities"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("allocationToGOE"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("recommendedPortfolioID"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("retirementGoalProbability"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("recommendedConsumption"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("RMD"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromGuaranteed"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("monthlyTopupAccumulation"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("monthlyTopupDecumulation"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("yearlyTopupAccumulation"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("yearlyTopupDecumulation"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("recommendedTenure"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromGOE"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("incomeFromAnnuities"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    float,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("portfolioPath"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            )) \
            and (UnionTypeLookUp.get("GoeWithAnnuitiesOutputModelWealthPath")
            .validate(dictionary.get("wealthPath")).is_valid)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _retirement_goal=self.retirement_goal
        _retirement_goal_min=self.retirement_goal_min
        _retirement_goal_max=self.retirement_goal_max
        _income_from_outside_assets=self.income_from_outside_assets
        _income_from_ss=self.income_from_ss
        _income_from_others=self.income_from_others
        _allocation_to_annuities=self.allocation_to_annuities
        _allocation_to_goe=self.allocation_to_goe
        _recommended_portfolio_id=self.recommended_portfolio_id
        _retirement_goal_probability=self.retirement_goal_probability
        _recommended_consumption=self.recommended_consumption
        _rmd=self.rmd
        _income_from_guaranteed=self.income_from_guaranteed
        _monthly_topup_accumulation=self.monthly_topup_accumulation
        _monthly_topup_decumulation=self.monthly_topup_decumulation
        _yearly_topup_accumulation=self.yearly_topup_accumulation
        _yearly_topup_decumulation=self.yearly_topup_decumulation
        _recommended_tenure=self.recommended_tenure
        _income_from_goe=self.income_from_goe
        _income_from_annuities=self.income_from_annuities
        _portfolio_path=self.portfolio_path
        _wealth_path=self.wealth_path
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"retirement_goal={_retirement_goal!r}, "
            f"retirement_goal_min={_retirement_goal_min!r}, "
            f"retirement_goal_max={_retirement_goal_max!r}, "
            f"income_from_outside_assets={_income_from_outside_assets!r}, "
            f"income_from_ss={_income_from_ss!r}, "
            f"income_from_others={_income_from_others!r}, "
            f"allocation_to_annuities={_allocation_to_annuities!r}, "
            f"allocation_to_goe={_allocation_to_goe!r}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!r}, "
            f"retirement_goal_probability={_retirement_goal_probability!r}, "
            f"recommended_consumption={_recommended_consumption!r}, "
            f"rmd={_rmd!r}, "
            f"income_from_guaranteed={_income_from_guaranteed!r}, "
            f"monthly_topup_accumulation={_monthly_topup_accumulation!r}, "
            f"monthly_topup_decumulation={_monthly_topup_decumulation!r}, "
            f"yearly_topup_accumulation={_yearly_topup_accumulation!r}, "
            f"yearly_topup_decumulation={_yearly_topup_decumulation!r}, "
            f"recommended_tenure={_recommended_tenure!r}, "
            f"income_from_goe={_income_from_goe!r}, "
            f"income_from_annuities={_income_from_annuities!r}, "
            f"portfolio_path={_portfolio_path!r}, "
            f"wealth_path={_wealth_path!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _retirement_goal=self.retirement_goal
        _retirement_goal_min=self.retirement_goal_min
        _retirement_goal_max=self.retirement_goal_max
        _income_from_outside_assets=self.income_from_outside_assets
        _income_from_ss=self.income_from_ss
        _income_from_others=self.income_from_others
        _allocation_to_annuities=self.allocation_to_annuities
        _allocation_to_goe=self.allocation_to_goe
        _recommended_portfolio_id=self.recommended_portfolio_id
        _retirement_goal_probability=self.retirement_goal_probability
        _recommended_consumption=self.recommended_consumption
        _rmd=self.rmd
        _income_from_guaranteed=self.income_from_guaranteed
        _monthly_topup_accumulation=self.monthly_topup_accumulation
        _monthly_topup_decumulation=self.monthly_topup_decumulation
        _yearly_topup_accumulation=self.yearly_topup_accumulation
        _yearly_topup_decumulation=self.yearly_topup_decumulation
        _recommended_tenure=self.recommended_tenure
        _income_from_goe=self.income_from_goe
        _income_from_annuities=self.income_from_annuities
        _portfolio_path=self.portfolio_path
        _wealth_path=self.wealth_path
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"retirement_goal={_retirement_goal!s}, "
            f"retirement_goal_min={_retirement_goal_min!s}, "
            f"retirement_goal_max={_retirement_goal_max!s}, "
            f"income_from_outside_assets={_income_from_outside_assets!s}, "
            f"income_from_ss={_income_from_ss!s}, "
            f"income_from_others={_income_from_others!s}, "
            f"allocation_to_annuities={_allocation_to_annuities!s}, "
            f"allocation_to_goe={_allocation_to_goe!s}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!s}, "
            f"retirement_goal_probability={_retirement_goal_probability!s}, "
            f"recommended_consumption={_recommended_consumption!s}, "
            f"rmd={_rmd!s}, "
            f"income_from_guaranteed={_income_from_guaranteed!s}, "
            f"monthly_topup_accumulation={_monthly_topup_accumulation!s}, "
            f"monthly_topup_decumulation={_monthly_topup_decumulation!s}, "
            f"yearly_topup_accumulation={_yearly_topup_accumulation!s}, "
            f"yearly_topup_decumulation={_yearly_topup_decumulation!s}, "
            f"recommended_tenure={_recommended_tenure!s}, "
            f"income_from_goe={_income_from_goe!s}, "
            f"income_from_annuities={_income_from_annuities!s}, "
            f"portfolio_path={_portfolio_path!s}, "
            f"wealth_path={_wealth_path!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
