"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.goe_for_taxes_response_body import (
    GoeForTaxesResponseBody,
)


class GoeForTaxesOutputModel(object):
    """Implementation of the 'GoeForTaxesOutputModel' model.

    Attributes:
        status_code (int): Status code for the response.
        message (str): Returns appropriate message for each status code.
        advice_id (str): Unique identifier for each response. The ID can be used as
            an input in the /api/goe-api/advice-status API request.
        body (GoeForTaxesResponseBody): The model property of type
            GoeForTaxesResponseBody.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status_code": "statusCode",
        "message": "message",
        "advice_id": "adviceID",
        "body": "body",
    }

    def __init__(
        self,
        status_code=None,
        message=None,
        advice_id=None,
        body=None,
        additional_properties=None):
        """Initialize a GoeForTaxesOutputModel instance."""
        # Initialize members of the class
        self.status_code = status_code
        self.message = message
        self.advice_id = advice_id
        self.body = body

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status_code =\
            dictionary.get("statusCode")\
            if dictionary.get("statusCode")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        advice_id =\
            dictionary.get("adviceID")\
            if dictionary.get("adviceID")\
                else None
        body =\
            GoeForTaxesResponseBody.from_dictionary(
                dictionary.get("body"))\
                if dictionary.get("body") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status_code,
                   message,
                   advice_id,
                   body,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status_code=self.status_code
        _message=self.message
        _advice_id=self.advice_id
        _body=self.body
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status_code={_status_code!r}, "
            f"message={_message!r}, "
            f"advice_id={_advice_id!r}, "
            f"body={_body!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status_code=self.status_code
        _message=self.message
        _advice_id=self.advice_id
        _body=self.body
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status_code={_status_code!s}, "
            f"message={_message!s}, "
            f"advice_id={_advice_id!s}, "
            f"body={_body!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
