"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.goe_to_expected_taxes_for_current_year_2 import (
    GoeToExpectedTaxesForCurrentYear2,
)
from goeapi.models.proposed_trades_current_year_info_2 import (
    ProposedTradesCurrentYearInfo2,
)


class GoeToAnalysisReport2(object):
    """Implementation of the 'GoeToAnalysisReport2' model.

    This section gives details of the GOE run for the original plan.

    Attributes:
        bankruptcy_msg (str): Message flagging an expected bankruptcy (goal running
            out of money) in any year. <br>                    Note:  <br>
            If ‘NA’, bankruptcy is unlikely to happen during the goal tenure.
            In bankruptcy cases, response would be of the format: <br>
            There is more than 75% probability of going bankrupt after year 10
        current_goal_probability (float): GOE’s estimated probability to achieve the
            goal target wealth. <br>                    Note:  <br>
            To be displayed as 63% (rounded with no decimals)
        expected_taxes_for_current_year (GoeToExpectedTaxesForCurrentYear2): Details
            of the taxes as received from LifeYield. <br>                    Note:
            <br>                    The taxes pertain to accounts that are under
            GOE’s discretion & are computed, in this dictionary, only for current
            financial year.
        is_goal_realistic (bool): To understand if the goal probability is more
            than 35% (This is a configurable field). <br>                    Note: If
            ‘false’, goal is                     unrealistic.
        meet_goal_priority (bool): Checks if goal probability is more than the
            target probability corresponding to the goal                     priority
            – Target probabilities for all goal                     priorities (Need,
            Want, Wish and Dream, Desire) are                     set in the GOE
            config. <br>                     Note: If ‘true’, goal
            probability achieves the                     target probability.
            If ‘false’, goal probability                     falls short of the
            target                     probability.
        one_time_top_up (Any): Recommendations based on available accounts. Two
            objectives of recommendations: <br>                    1. Ensure the
            probability of withdrawal from the taxable account is greater than the
            priority of the goal (pre-59.5Y). This is applicable if the user has
            taxable account with TDA / Roth account. <br>                    2. Add
            money to the retirement accounts if the current threshold for
            contributing to retirement accounts is not met.
        proposed_trades_current_year (ProposedTradesCurrentYearInfo2): Details of
            trade as of today i.e., current date & end of the year
        recommended_portfolio_id (int): GOE’s current recommended portfolio index.
            <br>                    Note: Can be between 1                     to 16.
            Also subject to                     investor’s risk profile: for
            example, conservative                     investors have access to
            1-8 portfolios while                     Aggressive investors have
            access to 1-16.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bankruptcy_msg": "bankruptcyMsg",
        "current_goal_probability": "currentGoalProbability",
        "expected_taxes_for_current_year": "expectedTaxesForCurrentYear",
        "is_goal_realistic": "isGoalRealistic",
        "meet_goal_priority": "meetGoalPriority",
        "one_time_top_up": "oneTimeTopUp",
        "proposed_trades_current_year": "proposedTradesCurrentYear",
        "recommended_portfolio_id": "recommendedPortfolioId",
    }

    def __init__(
        self,
        bankruptcy_msg=None,
        current_goal_probability=None,
        expected_taxes_for_current_year=None,
        is_goal_realistic=None,
        meet_goal_priority=None,
        one_time_top_up=None,
        proposed_trades_current_year=None,
        recommended_portfolio_id=None,
        additional_properties=None):
        """Initialize a GoeToAnalysisReport2 instance."""
        # Initialize members of the class
        self.bankruptcy_msg = bankruptcy_msg
        self.current_goal_probability = current_goal_probability
        self.expected_taxes_for_current_year = expected_taxes_for_current_year
        self.is_goal_realistic = is_goal_realistic
        self.meet_goal_priority = meet_goal_priority
        self.one_time_top_up = one_time_top_up
        self.proposed_trades_current_year = proposed_trades_current_year
        self.recommended_portfolio_id = recommended_portfolio_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bankruptcy_msg =\
            dictionary.get("bankruptcyMsg")\
            if dictionary.get("bankruptcyMsg")\
                else None
        current_goal_probability =\
            dictionary.get("currentGoalProbability")\
            if dictionary.get("currentGoalProbability")\
                else None
        expected_taxes_for_current_year =\
            GoeToExpectedTaxesForCurrentYear2.from_dictionary(
                dictionary.get("expectedTaxesForCurrentYear"))\
                if dictionary.get("expectedTaxesForCurrentYear") else None
        is_goal_realistic =\
            dictionary.get("isGoalRealistic")\
            if "isGoalRealistic" in dictionary.keys()\
                else None
        meet_goal_priority =\
            dictionary.get("meetGoalPriority")\
            if "meetGoalPriority" in dictionary.keys()\
                else None
        one_time_top_up =\
            dictionary.get("oneTimeTopUp")\
            if dictionary.get("oneTimeTopUp")\
                else None
        proposed_trades_current_year =\
            ProposedTradesCurrentYearInfo2.from_dictionary(
                dictionary.get("proposedTradesCurrentYear"))\
                if dictionary.get("proposedTradesCurrentYear") else None
        recommended_portfolio_id =\
            dictionary.get("recommendedPortfolioId")\
            if dictionary.get("recommendedPortfolioId")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(bankruptcy_msg,
                   current_goal_probability,
                   expected_taxes_for_current_year,
                   is_goal_realistic,
                   meet_goal_priority,
                   one_time_top_up,
                   proposed_trades_current_year,
                   recommended_portfolio_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _bankruptcy_msg=self.bankruptcy_msg
        _current_goal_probability=self.current_goal_probability
        _expected_taxes_for_current_year=self.expected_taxes_for_current_year
        _is_goal_realistic=self.is_goal_realistic
        _meet_goal_priority=self.meet_goal_priority
        _one_time_top_up=self.one_time_top_up
        _proposed_trades_current_year=self.proposed_trades_current_year
        _recommended_portfolio_id=self.recommended_portfolio_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bankruptcy_msg={_bankruptcy_msg!r}, "
            f"current_goal_probability={_current_goal_probability!r}, "
            f"expected_taxes_for_current_year={_expected_taxes_for_current_year!r}, "
            f"is_goal_realistic={_is_goal_realistic!r}, "
            f"meet_goal_priority={_meet_goal_priority!r}, "
            f"one_time_top_up={_one_time_top_up!r}, "
            f"proposed_trades_current_year={_proposed_trades_current_year!r}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _bankruptcy_msg=self.bankruptcy_msg
        _current_goal_probability=self.current_goal_probability
        _expected_taxes_for_current_year=self.expected_taxes_for_current_year
        _is_goal_realistic=self.is_goal_realistic
        _meet_goal_priority=self.meet_goal_priority
        _one_time_top_up=self.one_time_top_up
        _proposed_trades_current_year=self.proposed_trades_current_year
        _recommended_portfolio_id=self.recommended_portfolio_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"bankruptcy_msg={_bankruptcy_msg!s}, "
            f"current_goal_probability={_current_goal_probability!s}, "
            f"expected_taxes_for_current_year={_expected_taxes_for_current_year!s}, "
            f"is_goal_realistic={_is_goal_realistic!s}, "
            f"meet_goal_priority={_meet_goal_priority!s}, "
            f"one_time_top_up={_one_time_top_up!s}, "
            f"proposed_trades_current_year={_proposed_trades_current_year!s}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
