"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.account import Account
from goeapi.models.goal_profile_simulation_engine import (
    GoalProfileSimulationEngine,
)
from goeapi.models.household_2 import Household2
from goeapi.models.policy_details import PolicyDetails
from goeapi.models.target_portfolio_2 import (
    TargetPortfolio2,
)
from goeapi.models.tax_rates_2 import TaxRates2


class GoeSimulationEngineInputModel(object):
    """Implementation of the 'GoeSimulationEngineInputModel' model.

    Attributes:
        reallocate (bool): Set as “true” when a newportfolio is needed.
        is_new_goal_priority (bool): If investor/end user changes the goal priority
            of any of the goals within the plan, in between the re-allocation dates,
            this is set to ‘true’. <br>                                     For new
            plans, this needs to be ‘true’.
        reallocation_freq (str): Describes the frequency of re-allocation.
        current_portfolio_id (int): Displays the current portfolio assigned to a
            user. For the firsttime user, this should be set as “null”.
        curr_date (str): The date on which GOE-SOFT call is made.<br>
            Valid input format is date –‘dd-mm-yyyy’.
        risk_profile (RiskProfile3): Defines the user’s risk profile, which is mapped
            to one or more portfolios.This is customizable.
        compute_social_security (bool): When set to true computes the social
            security.                 Mandatory fields (part of memberList) needed
            for social security are: “DOB”, “currentSalary”, “socialSecurityStartAge”
        use_social_security_for_goals (bool): When set to “true” uses Social Security
            to meet the withdrawals.             If set to “false”, and when
            'computeSocialSecurity' is set as 'true' - only computes the Social
            Security but does not use it to fulfil the goals.             In cases
            social security (post-tax) is greater than the withdrawal amount, the
            social security is collected into the taxable accounts.             If no
            taxable accounts are present, SocialSecurity left – after meeting the
            goals – is ignored.
        cashflow_date (str): Cashflow date of the goal - this is the date (year is
            ignored) on which infusions/withdrawals would be realized for the goal.
            This parameter is optional.  If not passed or value is null,
            the algorithm would consider the first reallocation date as the cashflow
            date.
        is_new_risk_profile (bool): If the risk profile of the investor has changed,
            this is set to ‘true’.
            For first time calls to GOE, this needs to be set to ‘true’.
        is_new_investment_tenure (bool): If investor/end user changes the goal
            investment tenure after onboarding and before the next immediate
            re-allocation date,                                     this is set to
            ‘true’. For first time calls to GOE, this needs to be set to ‘true’.
        is_new_goal (bool): If the end user changes the goal amount / infusions /
            withdrawals, in between the re-allocation dates,                     this
            is set to ‘true’. For retirement scenarios, this would be a change in
            retirement income goal,                     while for a capital
            accumulation goal, this would be a change in the lumpsum accumulation
            target.                     For first time calls to GOE, this needs to be
            set to ‘true’.
        infusion_type (InfusionType2): Defines if the infusions are at the yearly
            level or monthly level.
        cola_rate (float): Defines the Cost-of-Living Adjustment to be used for
            Social Security amount computations.             When passed as “null”,
            this is assumed to be 0%.
        tax_rates (TaxRates2): Consists of tax rates applicable pre & post-retirement.
        household (Household2): contains all information about all the participants
            within the household.                         For MVP, only a single
            member is allowed.
        accounts (List[Account]): Details of different accounts associated with
            unique memberID in the household.
        goal_profile_list (List[GoalProfileSimulationEngine]): Details related to the
            withdrawals associated with the plan where a plan is defined as a
            collection of goals.
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        account_held_away (bool): To be set to True if the account is a held away
            account
        mean_return (float): Mean return value for the AHA account. Can be set to
            null or ignored if ‘accountHeldAway’ is set to False
        standard_deviation (float): Standard deviation for the AHA account. Can be
            set to null or ignored if ‘accountHeldAway’ is set to False
        equity_allocation (float): The Equity '%' for the AHA account. If this value
            is provided, the mean and standard deviation is mapped to the GOE managed
            portfolios. Can be set to null or ignored if ‘accountHeldAway’ is set to
            False.
        lock_expiry_date (str): The AHA account is considered locked and unavailable
            for withdrawals till this date. Note that however contributions and RMDs
            will always be processed. Can be set to null or ignored if
            ‘accountHeldAway’ is set to False.
        target_portfolio (TargetPortfolio2): Target portfolio defines the risk
            profile for AUA accounts in case user wants to use custom portfolio mode.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "reallocate": "reallocate",
        "reallocation_freq": "reallocationFreq",
        "current_portfolio_id": "currentPortfolioId",
        "risk_profile": "riskProfile",
        "is_new_risk_profile": "isNewRiskProfile",
        "infusion_type": "infusionType",
        "tax_rates": "taxRates",
        "household": "household",
        "accounts": "accounts",
        "goal_profile_list": "goalProfileList",
        "is_new_goal_priority": "isNewGoalPriority",
        "curr_date": "currDate",
        "compute_social_security": "computeSocialSecurity",
        "use_social_security_for_goals": "useSocialSecurityForGoals",
        "cashflow_date": "cashflowDate",
        "is_new_investment_tenure": "isNewInvestmentTenure",
        "is_new_goal": "isNewGoal",
        "cola_rate": "colaRate",
        "policy": "policy",
        "account_held_away": "accountHeldAway",
        "mean_return": "meanReturn",
        "standard_deviation": "standardDeviation",
        "equity_allocation": "equityAllocation",
        "lock_expiry_date": "lockExpiryDate",
        "target_portfolio": "targetPortfolio",
    }

    _optionals = [
        "is_new_goal_priority",
        "curr_date",
        "compute_social_security",
        "use_social_security_for_goals",
        "cashflow_date",
        "is_new_investment_tenure",
        "is_new_goal",
        "cola_rate",
        "policy",
        "account_held_away",
        "mean_return",
        "standard_deviation",
        "equity_allocation",
        "lock_expiry_date",
        "target_portfolio",
    ]

    _nullables = [
        "current_portfolio_id",
        "curr_date",
        "cashflow_date",
    ]

    def __init__(
        self,
        reallocate=None,
        current_portfolio_id=None,
        risk_profile=None,
        is_new_risk_profile=None,
        infusion_type=None,
        tax_rates=None,
        household=None,
        accounts=None,
        goal_profile_list=None,
        is_new_goal_priority=APIHelper.SKIP,
        curr_date=APIHelper.SKIP,
        compute_social_security=False,
        use_social_security_for_goals=False,
        cashflow_date=APIHelper.SKIP,
        is_new_investment_tenure=APIHelper.SKIP,
        is_new_goal=APIHelper.SKIP,
        cola_rate=0,
        policy=APIHelper.SKIP,
        account_held_away=APIHelper.SKIP,
        mean_return=APIHelper.SKIP,
        standard_deviation=APIHelper.SKIP,
        equity_allocation=APIHelper.SKIP,
        lock_expiry_date=APIHelper.SKIP,
        target_portfolio=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GoeSimulationEngineInputModel instance."""
        # Initialize members of the class
        self.reallocate = reallocate
        if is_new_goal_priority is not APIHelper.SKIP:
            self.is_new_goal_priority = is_new_goal_priority
        self.reallocation_freq = "yearly"
        self.current_portfolio_id = current_portfolio_id
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.risk_profile = risk_profile
        self.compute_social_security = compute_social_security
        self.use_social_security_for_goals = use_social_security_for_goals
        if cashflow_date is not APIHelper.SKIP:
            self.cashflow_date = cashflow_date
        self.is_new_risk_profile = is_new_risk_profile
        if is_new_investment_tenure is not APIHelper.SKIP:
            self.is_new_investment_tenure = is_new_investment_tenure
        if is_new_goal is not APIHelper.SKIP:
            self.is_new_goal = is_new_goal
        self.infusion_type = infusion_type
        self.cola_rate = cola_rate
        self.tax_rates = tax_rates
        self.household = household
        self.accounts = accounts
        self.goal_profile_list = goal_profile_list
        if policy is not APIHelper.SKIP:
            self.policy = policy
        if account_held_away is not APIHelper.SKIP:
            self.account_held_away = account_held_away
        if mean_return is not APIHelper.SKIP:
            self.mean_return = mean_return
        if standard_deviation is not APIHelper.SKIP:
            self.standard_deviation = standard_deviation
        if equity_allocation is not APIHelper.SKIP:
            self.equity_allocation = equity_allocation
        if lock_expiry_date is not APIHelper.SKIP:
            self.lock_expiry_date = lock_expiry_date
        if target_portfolio is not APIHelper.SKIP:
            self.target_portfolio = target_portfolio

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        reallocate =\
            dictionary.get("reallocate")\
            if "reallocate" in dictionary.keys()\
                else None
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if dictionary.get("currentPortfolioId")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        is_new_risk_profile =\
            dictionary.get("isNewRiskProfile")\
            if "isNewRiskProfile" in dictionary.keys()\
                else None
        infusion_type =\
            dictionary.get("infusionType")\
            if dictionary.get("infusionType")\
                else None
        tax_rates =\
            TaxRates2.from_dictionary(
                dictionary.get("taxRates"))\
                if dictionary.get("taxRates") else None
        household =\
            Household2.from_dictionary(
                dictionary.get("household"))\
                if dictionary.get("household") else None
        accounts = None
        if dictionary.get("accounts") is not None:
            accounts = [
                Account.from_dictionary(x)
                    for x in dictionary.get("accounts")
            ]
        goal_profile_list = None
        if dictionary.get("goalProfileList") is not None:
            goal_profile_list = [
                GoalProfileSimulationEngine.from_dictionary(x)
                    for x in dictionary.get("goalProfileList")
            ]
        is_new_goal_priority =\
            dictionary.get("isNewGoalPriority")\
            if "isNewGoalPriority" in dictionary.keys()\
                else APIHelper.SKIP
        curr_date =\
            dictionary.get("currDate")\
            if "currDate" in dictionary.keys()\
                else APIHelper.SKIP
        compute_social_security =\
            dictionary.get("computeSocialSecurity")\
            if dictionary.get("computeSocialSecurity")\
                else False
        use_social_security_for_goals =\
            dictionary.get("useSocialSecurityForGoals")\
            if dictionary.get("useSocialSecurityForGoals")\
                else False
        cashflow_date =\
            dictionary.get("cashflowDate")\
            if "cashflowDate" in dictionary.keys()\
                else APIHelper.SKIP
        is_new_investment_tenure =\
            dictionary.get("isNewInvestmentTenure")\
            if "isNewInvestmentTenure" in dictionary.keys()\
                else APIHelper.SKIP
        is_new_goal =\
            dictionary.get("isNewGoal")\
            if "isNewGoal" in dictionary.keys()\
                else APIHelper.SKIP
        cola_rate =\
            dictionary.get("colaRate")\
            if dictionary.get("colaRate")\
                else 0
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP
        account_held_away =\
            dictionary.get("accountHeldAway")\
            if "accountHeldAway" in dictionary.keys()\
                else APIHelper.SKIP
        mean_return =\
            dictionary.get("meanReturn")\
            if dictionary.get("meanReturn")\
                else APIHelper.SKIP
        standard_deviation =\
            dictionary.get("standardDeviation")\
            if dictionary.get("standardDeviation")\
                else APIHelper.SKIP
        equity_allocation =\
            dictionary.get("equityAllocation")\
            if dictionary.get("equityAllocation")\
                else APIHelper.SKIP
        lock_expiry_date =\
            dictionary.get("lockExpiryDate")\
            if dictionary.get("lockExpiryDate")\
                else APIHelper.SKIP
        target_portfolio =\
            TargetPortfolio2.from_dictionary(
                dictionary.get("targetPortfolio"))\
                if "targetPortfolio" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(reallocate,
                   current_portfolio_id,
                   risk_profile,
                   is_new_risk_profile,
                   infusion_type,
                   tax_rates,
                   household,
                   accounts,
                   goal_profile_list,
                   is_new_goal_priority,
                   curr_date,
                   compute_social_security,
                   use_social_security_for_goals,
                   cashflow_date,
                   is_new_investment_tenure,
                   is_new_goal,
                   cola_rate,
                   policy,
                   account_held_away,
                   mean_return,
                   standard_deviation,
                   equity_allocation,
                   lock_expiry_date,
                   target_portfolio,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _reallocate=self.reallocate
        _is_new_goal_priority=(
            self.is_new_goal_priority
            if hasattr(self, "is_new_goal_priority")
            else None
        )
        _reallocation_freq=self.reallocation_freq
        _current_portfolio_id=self.current_portfolio_id
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _compute_social_security=(
            self.compute_social_security
            if hasattr(self, "compute_social_security")
            else None
        )
        _use_social_security_for_goals=(
            self.use_social_security_for_goals
            if hasattr(self, "use_social_security_for_goals")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=(
            self.is_new_investment_tenure
            if hasattr(self, "is_new_investment_tenure")
            else None
        )
        _is_new_goal=(
            self.is_new_goal
            if hasattr(self, "is_new_goal")
            else None
        )
        _infusion_type=self.infusion_type
        _cola_rate=(
            self.cola_rate
            if hasattr(self, "cola_rate")
            else None
        )
        _tax_rates=self.tax_rates
        _household=self.household
        _accounts=self.accounts
        _goal_profile_list=self.goal_profile_list
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _account_held_away=(
            self.account_held_away
            if hasattr(self, "account_held_away")
            else None
        )
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _equity_allocation=(
            self.equity_allocation
            if hasattr(self, "equity_allocation")
            else None
        )
        _lock_expiry_date=(
            self.lock_expiry_date
            if hasattr(self, "lock_expiry_date")
            else None
        )
        _target_portfolio=(
            self.target_portfolio
            if hasattr(self, "target_portfolio")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reallocate={_reallocate!r}, "
            f"is_new_goal_priority={_is_new_goal_priority!r}, "
            f"reallocation_freq={_reallocation_freq!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"curr_date={_curr_date!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"compute_social_security={_compute_social_security!r}, "
            f"use_social_security_for_goals={_use_social_security_for_goals!r}, "
            f"cashflow_date={_cashflow_date!r}, "
            f"is_new_risk_profile={_is_new_risk_profile!r}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!r}, "
            f"is_new_goal={_is_new_goal!r}, "
            f"infusion_type={_infusion_type!r}, "
            f"cola_rate={_cola_rate!r}, "
            f"tax_rates={_tax_rates!r}, "
            f"household={_household!r}, "
            f"accounts={_accounts!r}, "
            f"goal_profile_list={_goal_profile_list!r}, "
            f"policy={_policy!r}, "
            f"account_held_away={_account_held_away!r}, "
            f"mean_return={_mean_return!r}, "
            f"standard_deviation={_standard_deviation!r}, "
            f"equity_allocation={_equity_allocation!r}, "
            f"lock_expiry_date={_lock_expiry_date!r}, "
            f"target_portfolio={_target_portfolio!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _reallocate=self.reallocate
        _is_new_goal_priority=(
            self.is_new_goal_priority
            if hasattr(self, "is_new_goal_priority")
            else None
        )
        _reallocation_freq=self.reallocation_freq
        _current_portfolio_id=self.current_portfolio_id
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _risk_profile=self.risk_profile
        _compute_social_security=(
            self.compute_social_security
            if hasattr(self, "compute_social_security")
            else None
        )
        _use_social_security_for_goals=(
            self.use_social_security_for_goals
            if hasattr(self, "use_social_security_for_goals")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_investment_tenure=(
            self.is_new_investment_tenure
            if hasattr(self, "is_new_investment_tenure")
            else None
        )
        _is_new_goal=(
            self.is_new_goal
            if hasattr(self, "is_new_goal")
            else None
        )
        _infusion_type=self.infusion_type
        _cola_rate=(
            self.cola_rate
            if hasattr(self, "cola_rate")
            else None
        )
        _tax_rates=self.tax_rates
        _household=self.household
        _accounts=self.accounts
        _goal_profile_list=self.goal_profile_list
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _account_held_away=(
            self.account_held_away
            if hasattr(self, "account_held_away")
            else None
        )
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _equity_allocation=(
            self.equity_allocation
            if hasattr(self, "equity_allocation")
            else None
        )
        _lock_expiry_date=(
            self.lock_expiry_date
            if hasattr(self, "lock_expiry_date")
            else None
        )
        _target_portfolio=(
            self.target_portfolio
            if hasattr(self, "target_portfolio")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"reallocate={_reallocate!s}, "
            f"is_new_goal_priority={_is_new_goal_priority!s}, "
            f"reallocation_freq={_reallocation_freq!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"curr_date={_curr_date!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"compute_social_security={_compute_social_security!s}, "
            f"use_social_security_for_goals={_use_social_security_for_goals!s}, "
            f"cashflow_date={_cashflow_date!s}, "
            f"is_new_risk_profile={_is_new_risk_profile!s}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!s}, "
            f"is_new_goal={_is_new_goal!s}, "
            f"infusion_type={_infusion_type!s}, "
            f"cola_rate={_cola_rate!s}, "
            f"tax_rates={_tax_rates!s}, "
            f"household={_household!s}, "
            f"accounts={_accounts!s}, "
            f"goal_profile_list={_goal_profile_list!s}, "
            f"policy={_policy!s}, "
            f"account_held_away={_account_held_away!s}, "
            f"mean_return={_mean_return!s}, "
            f"standard_deviation={_standard_deviation!s}, "
            f"equity_allocation={_equity_allocation!s}, "
            f"lock_expiry_date={_lock_expiry_date!s}, "
            f"target_portfolio={_target_portfolio!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
