"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class MemberGoeForTaxesObj(object):
    """Implementation of the 'MemberGoeForTaxesObj' model.

    Attributes:
        member_type (MemberType): Indicates the importance of member of to a
            household.             Usually, a higher earning member is assigned as
            “Primary” member.
        member_id (str): Identifier unique to each member of the household
        dob (str): Date of birth of a member in the household.
            Used for checking early withdrawal possibility from
            the retirement accounts & the Social Security calculations.
            Valid input format is date: MM-YYYY
        current_age (int): Current age of the household member
        retirement_age (int): Retirement age of the household member
        current_salary (float): Current salary of the household member.
            Used for Social Security calculations
        social_security_start_age (int): Custom age at which the member wishes to
            receive her Social Security benefits
        tda_balance_for_rmd (float): The previous year’s ending TDA account balance
            that canbe used to compute the first year’s RMD value.
            Can be ignored and removed from the payload no info is available. GOE
            will consider the current TDA account balance as a proxy
        rmd_utilized (float): In the event the RMD computations are desired for the
            current financial year,                     this field specifies the
            amount of RMD already taken out before the GOE call was made.
            Can be ignored removed from the payload if not applicable
        existing_monthly_social_security_amount (float): In the event when the user
            is already receiving the SS amount and             their ‘currentAge’ is
            greater than the ‘socialSecurityStartAge’,             they should not
            use the Social Security income calculator and can simply mention that
            monthly amount in this parameter.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "member_type": "memberType",
        "member_id": "memberID",
        "dob": "DOB",
        "current_age": "currentAge",
        "retirement_age": "retirementAge",
        "current_salary": "currentSalary",
        "social_security_start_age": "socialSecurityStartAge",
        "tda_balance_for_rmd": "TDABalanceForRMD",
        "rmd_utilized": "RMDUtilized",
        "existing_monthly_social_security_amount":
            "existingMonthlySocialSecurityAmount",
    }

    _optionals = [
        "tda_balance_for_rmd",
        "rmd_utilized",
        "existing_monthly_social_security_amount",
    ]

    _nullables = [
        "tda_balance_for_rmd",
        "rmd_utilized",
        "existing_monthly_social_security_amount",
    ]

    def __init__(
        self,
        member_type=None,
        member_id=None,
        dob=None,
        current_age=None,
        retirement_age=None,
        current_salary=None,
        social_security_start_age=None,
        tda_balance_for_rmd=APIHelper.SKIP,
        rmd_utilized=APIHelper.SKIP,
        existing_monthly_social_security_amount=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MemberGoeForTaxesObj instance."""
        # Initialize members of the class
        self.member_type = member_type
        self.member_id = member_id
        self.dob = dob
        self.current_age = current_age
        self.retirement_age = retirement_age
        self.current_salary = current_salary
        self.social_security_start_age = social_security_start_age
        if tda_balance_for_rmd is not APIHelper.SKIP:
            self.tda_balance_for_rmd = tda_balance_for_rmd
        if rmd_utilized is not APIHelper.SKIP:
            self.rmd_utilized = rmd_utilized
        if existing_monthly_social_security_amount is not APIHelper.SKIP:
            self.existing_monthly_social_security_amount =\
                 existing_monthly_social_security_amount

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        member_type =\
            dictionary.get("memberType")\
            if dictionary.get("memberType")\
                else None
        member_id =\
            dictionary.get("memberID")\
            if dictionary.get("memberID")\
                else None
        dob =\
            dictionary.get("DOB")\
            if dictionary.get("DOB")\
                else None
        current_age =\
            dictionary.get("currentAge")\
            if dictionary.get("currentAge")\
                else None
        retirement_age =\
            dictionary.get("retirementAge")\
            if dictionary.get("retirementAge")\
                else None
        current_salary =\
            dictionary.get("currentSalary")\
            if dictionary.get("currentSalary")\
                else None
        social_security_start_age =\
            dictionary.get("socialSecurityStartAge")\
            if dictionary.get("socialSecurityStartAge")\
                else None
        tda_balance_for_rmd =\
            dictionary.get("TDABalanceForRMD")\
            if "TDABalanceForRMD" in dictionary.keys()\
                else APIHelper.SKIP
        rmd_utilized =\
            dictionary.get("RMDUtilized")\
            if "RMDUtilized" in dictionary.keys()\
                else APIHelper.SKIP
        existing_monthly_social_security_amount =\
            dictionary.get("existingMonthlySocialSecurityAmount")\
            if "existingMonthlySocialSecurityAmount" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(member_type,
                   member_id,
                   dob,
                   current_age,
                   retirement_age,
                   current_salary,
                   social_security_start_age,
                   tda_balance_for_rmd,
                   rmd_utilized,
                   existing_monthly_social_security_amount,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _member_type=self.member_type
        _member_id=self.member_id
        _dob=self.dob
        _current_age=self.current_age
        _retirement_age=self.retirement_age
        _current_salary=self.current_salary
        _social_security_start_age=self.social_security_start_age
        _tda_balance_for_rmd=(
            self.tda_balance_for_rmd
            if hasattr(self, "tda_balance_for_rmd")
            else None
        )
        _rmd_utilized=(
            self.rmd_utilized
            if hasattr(self, "rmd_utilized")
            else None
        )
        _existing_monthly_social_security_amount=(
            self.existing_monthly_social_security_amount
            if hasattr(self, "existing_monthly_social_security_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_type={_member_type!r}, "
            f"member_id={_member_id!r}, "
            f"dob={_dob!r}, "
            f"current_age={_current_age!r}, "
            f"retirement_age={_retirement_age!r}, "
            f"current_salary={_current_salary!r}, "
            f"social_security_start_age={_social_security_start_age!r}, "
            f"tda_balance_for_rmd={_tda_balance_for_rmd!r}, "
            f"rmd_utilized={_rmd_utilized!r}, "
            f"existing_monthly_social_security_amount={_existing_monthly_social_security_amount!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _member_type=self.member_type
        _member_id=self.member_id
        _dob=self.dob
        _current_age=self.current_age
        _retirement_age=self.retirement_age
        _current_salary=self.current_salary
        _social_security_start_age=self.social_security_start_age
        _tda_balance_for_rmd=(
            self.tda_balance_for_rmd
            if hasattr(self, "tda_balance_for_rmd")
            else None
        )
        _rmd_utilized=(
            self.rmd_utilized
            if hasattr(self, "rmd_utilized")
            else None
        )
        _existing_monthly_social_security_amount=(
            self.existing_monthly_social_security_amount
            if hasattr(self, "existing_monthly_social_security_amount")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"member_type={_member_type!s}, "
            f"member_id={_member_id!s}, "
            f"dob={_dob!s}, "
            f"current_age={_current_age!s}, "
            f"retirement_age={_retirement_age!s}, "
            f"current_salary={_current_salary!s}, "
            f"social_security_start_age={_social_security_start_age!s}, "
            f"tda_balance_for_rmd={_tda_balance_for_rmd!s}, "
            f"rmd_utilized={_rmd_utilized!s}, "
            f"existing_monthly_social_security_amount={_existing_monthly_social_security_amount!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
