"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Priority3(object):
    """Implementation of the 'Priority3' enum.

    Goal priority.

    Attributes:
        NEED: The enum member of type str.
        WANT: The enum member of type str.
        WISH: The enum member of type str.
        DREAM: The enum member of type str.
        DESIRE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    NEED = "Need"

    WANT = "Want"

    WISH = "Wish"

    DREAM = "Dream"

    DESIRE = "Desire"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
