"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class RiskProfile1(object):
    """Implementation of the 'RiskProfile1' enum.

    Defines the user’s risk profile – does not vary by goal for each investor. On a
    default basis, GOE is configured for three Risk Profile levels, but it can be
    customized for up to five levels. Note that Risk Profiles are mapped to portfolio
    access.This is nullable and non mandatory if useCapsAndFloors is true.

    Attributes:
        CONSERVATIVE: The enum member of type str.
        MODERATE: The enum member of type str.
        AGGRESSIVE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    CONSERVATIVE = "Conservative"

    MODERATE = "Moderate"

    AGGRESSIVE = "Aggressive"

    @classmethod
    def validate(cls, value):
        """Validate value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return bool(value)

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
