"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Riskprofile(object):
    """Implementation of the 'Riskprofile' enum.

    The risk tolerance profile selected by the user. This is defined at the user
    level, not per goal.

    Attributes:
        CONSERVATIVE: The enum member of type str.
        MODERATE: The enum member of type str.
        AGGRESSIVE: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    CONSERVATIVE = "Conservative"

    MODERATE = "Moderate"

    AGGRESSIVE = "Aggressive"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
