"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class RunPipeAnalysisReport1(object):
    """Implementation of the 'RunPipeAnalysisReport1' model.

    Captures various important recommendations and outputs from the GOE engine.

    Attributes:
        current_goal_probability (float): GOE’s estimated probability to achieve the
            goal target wealth. This is rounded to 4 decimal places.
        recommended_portfolio_id (int): GOE’s current recommended portfolio index.
            <br>                     Note: Portfolio chosen from the list of all
            available portfolios to the goal.
        meet_goal_priority (bool): Checks if goal probability is more than the target
            probability corresponding to         the goal priority – Target
            probabilities for all goal priorities (Need, Want, Wish and Dream) are
            set in the GOE config.         Note: If ‘true’, goal probability achieves
            the target probability – goal probability to be shown on the front end.
            If ‘false’, goal probability falls short of the target probability –goal
            probability to be shown along with infusion and tenure recommendations
        is_goal_realistic (bool): To understand if the goal can be met with a
            reasonable probability (set by the ‘unrealistic’ goal probability value
            in the GOE config).         If current goal probability < desired target
            goal probability (defined by the goal priority), the goal is termed
            unrealistic <br>         Note: Flag will be set to False if the current
            goal probability is less than the probability threshold for realistic
            goal for all cases irrespective. <br>         If ‘false’, goal is
            unrealistic - need to alert the user on the front end with a message such
            as ‘Goal is not realistic, please try reducing your target         goal
            amount or increasing your initial investment’
        one_time_top_up (float): Suggested one-time top-up amount that aims to
            improve the goal probability to meet the target goal probability.
            This is rounded to the nearest integer.
        yearly_top_up_accumulation (float): Suggested recurring yearly top-up amount
            that aims to improve the goal probability to meet the target goal
            probability. This would be returned with a value if the infusionType is
            annual. This is rounded to the nearest integer. This would be 0 if
            infusionType is monthly. <br> Note: Zero in cases where meet goal
            priority = ‘true’; Non-zero otherwise.
        monthly_top_up_accumulation (float): Suggested recurring monthly top-up
            amount during the accumulation period that aims to improve
            the goal probability to meet the target goal probability. This would be
            returned only if the infusionType is monthly.             This is rounded
            to the nearest integer. <br>             Note: Zero in cases where meet
            goal priority = ‘true’; Non-zero otherwise.
        yearly_top_up_decumulation (float): Suggested recurring yearly decumulation
            amount that aims to improve the goal probability to meet the target goal
            probability.             This would be returned only if the infusionType
            is annual. This is rounded to the nearest integer.
        monthly_top_up_decumulation (float): Suggested recurring monthly top-up
            decumulation amount that aims to improve the goal probability to meet the
            target         goal probability, this value would be populated only in
            cases of decumulation of withdrawal scenario. This would be returned only
            if the infusionType is monthly. This is rounded to the nearest integer.
        recommended_tenure (str): For scenarios with goal probability less than 50%:
            <br>                     • If original tenure between 1 - 8 years
            –extended/reduced tenure 2 years to 4 years <br>                     • If
            original tenure between 9 – 14 years – extended/reduced tenure 4 years to
            8 years <br>                     • If original tenure greater than equal
            to 15 years –extended/reduced tenure 5 years to 10 years <br>         For
            scenarios with goal probability greater than or equal to 50%,
            extended/reduced tenure = 2 years to 4 years for all cases.         The
            algorithm recommends standard tenure increments/decrements based on the
            tenure input and the goal probability (calculated using current and end
            date).         Cases where tenure recommendation isn’t valid/required
            will show the recommendation as NA.         For retirement cases, where
            there is accumulation followed by decumulation, the extension is based on
            years to retirement and not on original tenure
        bankruptcy_msg (str): Message flagging an expected bankruptcy (goal running
            out of money) in any year.         The algorithm recommends standard
            tenure increments/decrements based on the tenure input and the goal
            probability (calculated using current and end date). <br>        Note: If
            ‘NA’, bankruptcy is unlikely to happen during the goal tenure.In
            bankruptcy cases, response would be similar to         ‘Bankruptcy is
            likely to happen in year 1’.
        message (str): Captures any message from the API after it is done processing
            the request.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "current_goal_probability": "currentGoalProbability",
        "recommended_portfolio_id": "recommendedPortfolioId",
        "meet_goal_priority": "meetGoalPriority",
        "is_goal_realistic": "isGoalRealistic",
        "one_time_top_up": "oneTimeTopUp",
        "yearly_top_up_accumulation": "yearlyTopUpAccumulation",
        "monthly_top_up_accumulation": "monthlyTopUpAccumulation",
        "yearly_top_up_decumulation": "yearlyTopUpDecumulation",
        "monthly_top_up_decumulation": "monthlyTopUpDecumulation",
        "recommended_tenure": "recommendedTenure",
        "bankruptcy_msg": "bankruptcyMsg",
        "message": "message",
    }

    _nullables = [
        "current_goal_probability",
        "meet_goal_priority",
        "is_goal_realistic",
        "one_time_top_up",
        "yearly_top_up_accumulation",
        "monthly_top_up_accumulation",
        "yearly_top_up_decumulation",
        "monthly_top_up_decumulation",
        "recommended_tenure",
        "bankruptcy_msg",
        "message",
    ]

    def __init__(
        self,
        current_goal_probability=None,
        recommended_portfolio_id=None,
        meet_goal_priority=None,
        is_goal_realistic=None,
        one_time_top_up=None,
        yearly_top_up_accumulation=None,
        monthly_top_up_accumulation=None,
        yearly_top_up_decumulation=None,
        monthly_top_up_decumulation=None,
        recommended_tenure=None,
        bankruptcy_msg=None,
        message=None,
        additional_properties=None):
        """Initialize a RunPipeAnalysisReport1 instance."""
        # Initialize members of the class
        self.current_goal_probability = current_goal_probability
        self.recommended_portfolio_id = recommended_portfolio_id
        self.meet_goal_priority = meet_goal_priority
        self.is_goal_realistic = is_goal_realistic
        self.one_time_top_up = one_time_top_up
        self.yearly_top_up_accumulation = yearly_top_up_accumulation
        self.monthly_top_up_accumulation = monthly_top_up_accumulation
        self.yearly_top_up_decumulation = yearly_top_up_decumulation
        self.monthly_top_up_decumulation = monthly_top_up_decumulation
        self.recommended_tenure = recommended_tenure
        self.bankruptcy_msg = bankruptcy_msg
        self.message = message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        current_goal_probability =\
            dictionary.get("currentGoalProbability")\
            if dictionary.get("currentGoalProbability")\
                else None
        recommended_portfolio_id =\
            dictionary.get("recommendedPortfolioId")\
            if dictionary.get("recommendedPortfolioId")\
                else None
        meet_goal_priority =\
            dictionary.get("meetGoalPriority")\
            if "meetGoalPriority" in dictionary.keys()\
                else None
        is_goal_realistic =\
            dictionary.get("isGoalRealistic")\
            if "isGoalRealistic" in dictionary.keys()\
                else None
        one_time_top_up =\
            dictionary.get("oneTimeTopUp")\
            if dictionary.get("oneTimeTopUp")\
                else None
        yearly_top_up_accumulation =\
            dictionary.get("yearlyTopUpAccumulation")\
            if dictionary.get("yearlyTopUpAccumulation")\
                else None
        monthly_top_up_accumulation =\
            dictionary.get("monthlyTopUpAccumulation")\
            if dictionary.get("monthlyTopUpAccumulation")\
                else None
        yearly_top_up_decumulation =\
            dictionary.get("yearlyTopUpDecumulation")\
            if dictionary.get("yearlyTopUpDecumulation")\
                else None
        monthly_top_up_decumulation =\
            dictionary.get("monthlyTopUpDecumulation")\
            if dictionary.get("monthlyTopUpDecumulation")\
                else None
        recommended_tenure =\
            dictionary.get("recommendedTenure")\
            if dictionary.get("recommendedTenure")\
                else None
        bankruptcy_msg =\
            dictionary.get("bankruptcyMsg")\
            if dictionary.get("bankruptcyMsg")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(current_goal_probability,
                   recommended_portfolio_id,
                   meet_goal_priority,
                   is_goal_realistic,
                   one_time_top_up,
                   yearly_top_up_accumulation,
                   monthly_top_up_accumulation,
                   yearly_top_up_decumulation,
                   monthly_top_up_decumulation,
                   recommended_tenure,
                   bankruptcy_msg,
                   message,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _current_goal_probability=self.current_goal_probability
        _recommended_portfolio_id=self.recommended_portfolio_id
        _meet_goal_priority=self.meet_goal_priority
        _is_goal_realistic=self.is_goal_realistic
        _one_time_top_up=self.one_time_top_up
        _yearly_top_up_accumulation=self.yearly_top_up_accumulation
        _monthly_top_up_accumulation=self.monthly_top_up_accumulation
        _yearly_top_up_decumulation=self.yearly_top_up_decumulation
        _monthly_top_up_decumulation=self.monthly_top_up_decumulation
        _recommended_tenure=self.recommended_tenure
        _bankruptcy_msg=self.bankruptcy_msg
        _message=self.message
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"current_goal_probability={_current_goal_probability!r}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!r}, "
            f"meet_goal_priority={_meet_goal_priority!r}, "
            f"is_goal_realistic={_is_goal_realistic!r}, "
            f"one_time_top_up={_one_time_top_up!r}, "
            f"yearly_top_up_accumulation={_yearly_top_up_accumulation!r}, "
            f"monthly_top_up_accumulation={_monthly_top_up_accumulation!r}, "
            f"yearly_top_up_decumulation={_yearly_top_up_decumulation!r}, "
            f"monthly_top_up_decumulation={_monthly_top_up_decumulation!r}, "
            f"recommended_tenure={_recommended_tenure!r}, "
            f"bankruptcy_msg={_bankruptcy_msg!r}, "
            f"message={_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _current_goal_probability=self.current_goal_probability
        _recommended_portfolio_id=self.recommended_portfolio_id
        _meet_goal_priority=self.meet_goal_priority
        _is_goal_realistic=self.is_goal_realistic
        _one_time_top_up=self.one_time_top_up
        _yearly_top_up_accumulation=self.yearly_top_up_accumulation
        _monthly_top_up_accumulation=self.monthly_top_up_accumulation
        _yearly_top_up_decumulation=self.yearly_top_up_decumulation
        _monthly_top_up_decumulation=self.monthly_top_up_decumulation
        _recommended_tenure=self.recommended_tenure
        _bankruptcy_msg=self.bankruptcy_msg
        _message=self.message
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"current_goal_probability={_current_goal_probability!s}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!s}, "
            f"meet_goal_priority={_meet_goal_priority!s}, "
            f"is_goal_realistic={_is_goal_realistic!s}, "
            f"one_time_top_up={_one_time_top_up!s}, "
            f"yearly_top_up_accumulation={_yearly_top_up_accumulation!s}, "
            f"monthly_top_up_accumulation={_monthly_top_up_accumulation!s}, "
            f"yearly_top_up_decumulation={_yearly_top_up_decumulation!s}, "
            f"monthly_top_up_decumulation={_monthly_top_up_decumulation!s}, "
            f"recommended_tenure={_recommended_tenure!s}, "
            f"bankruptcy_msg={_bankruptcy_msg!s}, "
            f"message={_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
