"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.cash_flow_dict_2 import CashFlowDict2
from goeapi.models.policy_details import PolicyDetails


class RunPipeInputModel(object):
    """Implementation of the 'RunPipeInputModel' model.

    Attributes:
        is_new_goal_priority (bool): If investor/end user changes the goal priority
            in between the re-allocation dates,             this is set to ‘true’.
            For first time calls to GOE, this needs to be set to ‘true’.
        is_new_investment_tenure (bool): If investor/end user changes the goal
            investment tenure after onboarding and before the next immediate
            re-allocation date,             this is set to ‘true’. For first time
            calls to GOE, this needs to be set to ‘true’.
        is_new_risk_profile (bool): If the risk profile of the investor has changed,
            this should be set to ‘true’.                     For first time calls to
            GOE, this needs to be set to ‘true’.
        is_new_goal (bool): If investor/end user changes the goal amount, in between
            the re-allocation dates, this is set to ‘true’.                     For
            retirement scenarios, this would be a change in retirement income goal,
            while for a capital accumulation goal,                     this would be
            a change in the lumpsum accumulation target. For first time calls to GOE,
            this needs to be set to ‘true’.
        reallocate (bool): If the client wants GOE to reallocate between the
            scheduled re-allocation dates, this should be set to ‘true’.
        cashflow_date (str): Cashflow date of the goal - this is the date (year is
            ignored) on which infusions/withdrawals
            would be realized for the goal. Format is "dd-mm-yyyy"
            If not passed or value is null, the algorithm would consider the first
            reallocation date as the cashflow date.
        get_path (bool): Show ideal portfolio path over time. If getPath parameter is
            set to False, the portfolio path would not be returned in the response
            payload
        reallocation_freq (ReallocationFreq): Describes the frequency of
            re-allocation.
        goal_amount (float): Defines the target wealth value associated with the goal
            at end of goal tenure.
        initial_investment (float): Defines the initial investment amount to the goal.
        current_wealth (float): Current wealth when the GOE is being called or
            executed. At the time of initial onboarding, currentWealth =
            initialInvestment.
            At subsequent re-allocation dates, currentWealth would be the portfolio
            account value at the time.
        start_date (str): Defines the start date of goal.Valid input format is date –
            ‘dd-mm-yyyy’
        goal_start_date (str): Defines the goal's start date. Must be greater than or
            equal to startDate field and in DD-MM-YYYY format. Default value is Null.
            Mandatory If useCapsAndFloors is True and currentAge is not present
        end_date (str): Defines the end date of goal.Valid input format is date –
            ‘dd-mm-yyyy’
        curr_date (str): This is an optional parameter that can be used to simulate
            the current date to be the specified value.                     GOE will
            process the request as if you are making the API call on the specified
            date.                     If not passed, the current system date will be
            used as the current date.                     Valid input format is date
            – ‘dd-mm-yyyy’.
        goal_priority (GoalPriority1): Defines the importance a goal holds for a
            specific user. Order of priority is Need > Want > Wish > Dream
            goalPriority can be from 1 to 4 levels. However, note that Goal priority
            defines the target probabilities and the loss threshold values.
        current_portfolio_id (int): Displays the current portfolio index that the
            goal is allocated to;                     if GOE is getting executed for
            the first time, it should be null.
        infusions (List[float]): Cash flows from the user, recurring payments yearly
            <br>                                                        The length
            for this parameter is dynamic depending on the goal tenure, start date
            and end date.<br>
            The reference will always be on the created date. So, the first infusion
            will be on the first day of the goal <br>
            followed by infusions every year/month followed by the last
            infusion/withdrawal on the last day of the goal.<br>
            The values are positive in case of infusions; negative in case of
            withdrawals; zero in case of no cashflows; frequency depends on
            ‘infusion_type’ parameter
        risk_profile (RiskProfile5): Defines the user’s risk profile – does not vary
            by goal for each investor.             On a default basis, GOE is
            configured for three Risk Profile levels, but it can be customized for up
            to five levels.             Note that Risk Profiles are mapped to
            portfolio access.This is nullable and non mandatory if useCapsAndFloors
            is true
        scenario_type (ScenarioType4): Determines the type of the scenario, the
            suggested portfolio and the wealth glide path is created accordingly.
            ‘regular’ for regular goals accumulation goals where cash flows are
            positive (contributions) and with a typical target wealth
            ‘retirement’ for scenarios where a decumulation period is included: <br>
            1. Scenarios with an accumulation period (and an initial wealth) &
            positive cash flows followed                     by a decumulation period
            with withdrawals (negative cash flows) with or without an inheritance
            <br>                     2. Scenarios with an initial wealth followed by
            a decumulation period with or without an inheritance.
        infusion_type (InfusionType1): Indicates the frequency of cash flows –
            determines the cash flow array corresponding to the ‘infusions’ parameter.
        current_age (int): Captures the current age of the investor.
            Optional Parameter. Need to be passed if useCapsAndFloors is set to True
            or ‘requiredDataAvailable’ is set to False.
        retirement_age (int): Captures the retirement age of the investor.
            Optional Parameter.Considered as 65 if not passed
        risk_override (bool | None): This is an optional parameter to disable GOE’s
            default de-risking logic.                     When set to False, GOE
            considers the default de-risking logic.the goal and the allocation advice
            When set to True, GOE will not consider the default de-risking logic and
            will consider the risk profile of the participant for portfolio access.
        engaged_participant (bool | None): This applies only to retirement use cases
            which specifies whether a participant is engaged or unengaged. If the
            “currentAge” and the             “retirementAge” are passed, they will be
            used to determine the de-risking criteria; If set to true GOE
            will de-risk 5 years before retirement and if set to false GOE will
            de-risk 1 year before retirement as per the default admin configuration
            settings
        required_data_available (bool): This indicates to GOE if all the mandatory
            data parameters that are required to run the GOE algorithm are available
            or not.          If all the mandatory fields are available, this
            parameter is set to true, and they need be passed to run GOE.         If
            all the mandatory fields are not available, this parameter is set to
            false, and they need not be passed to run GOE except the 'currentAge' and
            the “retirementAge”; The API response body would contain only the
            recommended portfolio and the portfolio path, which is derived from a
            pre-determined glide path         based on the current age and the
            retirement age (this would be defaulted to 65 if not passed). All other
            response parameters would be null.
        wealth_path_probabilities (List[float] | None): This is an optional input
            parameter. If this input is passed, instead of one wealth path, the GOE
            output will         have 3 wealth paths –one path at the goal priority
            probability level and one path for each of the 2 probability values
            passed in this input array.
        plan_id (str): Plan ID of the participant.
        participant_id (str): ID of the participant.
        source_id (str): Source ID of the plan
        use_caps_and_floors (bool): This is an optional parameter set as false by
            default. If this is passed as ‘true’ – the minimum and maximum equity
            allocation at any             given year would be restricted based on the
            number of years to goal;Either goalStartDate                 or the
            ‘currentAge’ is required if this is set to True. If set to true 'Risk
            Profile' is ignored.
        target_portfolio (int): Defines the portfolio ID that has to be held across
            the entire goal horizon             during single portfolio mode i.e. buy
            and hold strategy. <br>             Mandatory if mode is
            'single-portfolio'​
        mode (str): Determines the custom modes that can be invoked by GOE API
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        cashflow (List[CashFlowDict2]): Cannot be a empty list. If defined, should
            have objects with below attributes. Multiple objects of each type should
            not be allowed. For example, you cannot allow two objects of type "GOAL".
            When "cashflow" is passed, "infusions" and "goalAmount" will be optional.
            Otherwise these two will be mandatory. The field is optional if
            "infusions" is provided, otherwise mandatory.
        transition_matrix_id (str): transitionMatrixID defines the ID of the
            transaction fee matrix that needs to be used for calculating transaction
            fee in the algo if transaction fee is set to true on admin portal.
            When transaction fees = true on admin portal: Yes (Mandatory)
            When transaction fees = false on admin portal: No (Optional, defaults to
            None)                 String key following a startYear_EndYear naming
            convention (e.g., '2025_2026' for inter-year, '2025_2025' or '2026_2026'
            for intra-year).
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "is_new_goal_priority": "isNewGoalPriority",
        "is_new_investment_tenure": "isNewInvestmentTenure",
        "is_new_risk_profile": "isNewRiskProfile",
        "is_new_goal": "isNewGoal",
        "get_path": "getPath",
        "reallocation_freq": "reallocationFreq",
        "goal_amount": "goalAmount",
        "initial_investment": "initialInvestment",
        "current_wealth": "currentWealth",
        "start_date": "startDate",
        "end_date": "endDate",
        "goal_priority": "goalPriority",
        "current_portfolio_id": "currentPortfolioId",
        "infusions": "infusions",
        "risk_profile": "riskProfile",
        "scenario_type": "scenarioType",
        "infusion_type": "infusionType",
        "reallocate": "reallocate",
        "cashflow_date": "cashflowDate",
        "goal_start_date": "goalStartDate",
        "curr_date": "currDate",
        "current_age": "currentAge",
        "retirement_age": "retirementAge",
        "risk_override": "riskOverride",
        "engaged_participant": "engagedParticipant",
        "required_data_available": "requiredDataAvailable",
        "wealth_path_probabilities": "wealthPathProbabilities",
        "plan_id": "planID",
        "participant_id": "participantID",
        "source_id": "sourceID",
        "use_caps_and_floors": "useCapsAndFloors",
        "target_portfolio": "targetPortfolio",
        "mode": "mode",
        "policy": "policy",
        "cashflow": "cashflow",
        "transition_matrix_id": "transitionMatrixID",
    }

    _optionals = [
        "reallocate",
        "cashflow_date",
        "goal_start_date",
        "curr_date",
        "current_age",
        "retirement_age",
        "risk_override",
        "engaged_participant",
        "required_data_available",
        "wealth_path_probabilities",
        "plan_id",
        "participant_id",
        "source_id",
        "use_caps_and_floors",
        "target_portfolio",
        "mode",
        "policy",
        "cashflow",
        "transition_matrix_id",
    ]

    _nullables = [
        "cashflow_date",
        "current_wealth",
        "curr_date",
        "current_portfolio_id",
        "current_age",
        "retirement_age",
        "plan_id",
        "participant_id",
        "source_id",
        "target_portfolio",
        "mode",
    ]

    def __init__(
        self,
        is_new_goal_priority=None,
        is_new_investment_tenure=None,
        is_new_risk_profile=None,
        is_new_goal=None,
        get_path=None,
        reallocation_freq=None,
        goal_amount=None,
        initial_investment=None,
        current_wealth=None,
        start_date=None,
        end_date=None,
        goal_priority=None,
        current_portfolio_id=None,
        infusions=None,
        risk_profile=None,
        scenario_type=None,
        infusion_type=None,
        reallocate=False,
        cashflow_date=APIHelper.SKIP,
        goal_start_date=APIHelper.SKIP,
        curr_date=APIHelper.SKIP,
        current_age=APIHelper.SKIP,
        retirement_age=APIHelper.SKIP,
        risk_override=APIHelper.SKIP,
        engaged_participant=APIHelper.SKIP,
        required_data_available=True,
        wealth_path_probabilities=APIHelper.SKIP,
        plan_id=APIHelper.SKIP,
        participant_id=APIHelper.SKIP,
        source_id=APIHelper.SKIP,
        use_caps_and_floors=False,
        target_portfolio=APIHelper.SKIP,
        mode=APIHelper.SKIP,
        policy=APIHelper.SKIP,
        cashflow=APIHelper.SKIP,
        transition_matrix_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a RunPipeInputModel instance."""
        # Initialize members of the class
        self.is_new_goal_priority = is_new_goal_priority
        self.is_new_investment_tenure = is_new_investment_tenure
        self.is_new_risk_profile = is_new_risk_profile
        self.is_new_goal = is_new_goal
        self.reallocate = reallocate
        if cashflow_date is not APIHelper.SKIP:
            self.cashflow_date = cashflow_date
        self.get_path = get_path
        self.reallocation_freq = reallocation_freq
        self.goal_amount = goal_amount
        self.initial_investment = initial_investment
        self.current_wealth = current_wealth
        self.start_date = start_date
        if goal_start_date is not APIHelper.SKIP:
            self.goal_start_date = goal_start_date
        self.end_date = end_date
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.goal_priority = goal_priority
        self.current_portfolio_id = current_portfolio_id
        self.infusions = infusions
        self.risk_profile = risk_profile
        self.scenario_type = scenario_type
        self.infusion_type = infusion_type
        if current_age is not APIHelper.SKIP:
            self.current_age = current_age
        if retirement_age is not APIHelper.SKIP:
            self.retirement_age = retirement_age
        if risk_override is not APIHelper.SKIP:
            self.risk_override = risk_override
        if engaged_participant is not APIHelper.SKIP:
            self.engaged_participant = engaged_participant
        self.required_data_available = required_data_available
        if wealth_path_probabilities is not APIHelper.SKIP:
            self.wealth_path_probabilities = wealth_path_probabilities
        if plan_id is not APIHelper.SKIP:
            self.plan_id = plan_id
        if participant_id is not APIHelper.SKIP:
            self.participant_id = participant_id
        if source_id is not APIHelper.SKIP:
            self.source_id = source_id
        self.use_caps_and_floors = use_caps_and_floors
        if target_portfolio is not APIHelper.SKIP:
            self.target_portfolio = target_portfolio
        if mode is not APIHelper.SKIP:
            self.mode = mode
        if policy is not APIHelper.SKIP:
            self.policy = policy
        if cashflow is not APIHelper.SKIP:
            self.cashflow = cashflow
        if transition_matrix_id is not APIHelper.SKIP:
            self.transition_matrix_id = transition_matrix_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from goeapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        is_new_goal_priority =\
            dictionary.get("isNewGoalPriority")\
            if "isNewGoalPriority" in dictionary.keys()\
                else None
        is_new_investment_tenure =\
            dictionary.get("isNewInvestmentTenure")\
            if "isNewInvestmentTenure" in dictionary.keys()\
                else None
        is_new_risk_profile =\
            dictionary.get("isNewRiskProfile")\
            if "isNewRiskProfile" in dictionary.keys()\
                else None
        is_new_goal =\
            dictionary.get("isNewGoal")\
            if "isNewGoal" in dictionary.keys()\
                else None
        get_path =\
            dictionary.get("getPath")\
            if "getPath" in dictionary.keys()\
                else None
        reallocation_freq =\
            dictionary.get("reallocationFreq")\
            if dictionary.get("reallocationFreq")\
                else None
        goal_amount =\
            dictionary.get("goalAmount")\
            if dictionary.get("goalAmount")\
                else None
        initial_investment =\
            dictionary.get("initialInvestment")\
            if dictionary.get("initialInvestment")\
                else None
        current_wealth =\
            dictionary.get("currentWealth")\
            if dictionary.get("currentWealth")\
                else None
        start_date =\
            dictionary.get("startDate")\
            if dictionary.get("startDate")\
                else None
        end_date =\
            dictionary.get("endDate")\
            if dictionary.get("endDate")\
                else None
        goal_priority =\
            dictionary.get("goalPriority")\
            if dictionary.get("goalPriority")\
                else None
        current_portfolio_id =\
            dictionary.get("currentPortfolioId")\
            if dictionary.get("currentPortfolioId")\
                else None
        infusions =\
            dictionary.get("infusions")\
            if dictionary.get("infusions")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        scenario_type =\
            dictionary.get("scenarioType")\
            if dictionary.get("scenarioType")\
                else None
        infusion_type =\
            dictionary.get("infusionType")\
            if dictionary.get("infusionType")\
                else None
        reallocate =\
            dictionary.get("reallocate")\
            if dictionary.get("reallocate")\
                else False
        cashflow_date =\
            dictionary.get("cashflowDate")\
            if "cashflowDate" in dictionary.keys()\
                else APIHelper.SKIP
        goal_start_date =\
            dictionary.get("goalStartDate")\
            if dictionary.get("goalStartDate")\
                else APIHelper.SKIP
        curr_date =\
            dictionary.get("currDate")\
            if "currDate" in dictionary.keys()\
                else APIHelper.SKIP
        current_age =\
            dictionary.get("currentAge")\
            if "currentAge" in dictionary.keys()\
                else APIHelper.SKIP
        retirement_age =\
            dictionary.get("retirementAge")\
            if "retirementAge" in dictionary.keys()\
                else APIHelper.SKIP
        risk_override = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("RunPipeInputModelRiskOverride"),
            dictionary.get("riskOverride"),
            False)\
            if dictionary.get("riskOverride") is not None\
            else APIHelper.SKIP
        engaged_participant = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("RunPipeInputModelEngagedParticipant"),
            dictionary.get("engagedParticipant"),
            False)\
            if dictionary.get("engagedParticipant") is not None\
            else APIHelper.SKIP
        required_data_available =\
            dictionary.get("requiredDataAvailable")\
            if dictionary.get("requiredDataAvailable")\
                else True
        wealth_path_probabilities = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("RunPipeInputModelWealthPathProbabilities"),
            dictionary.get("wealthPathProbabilities"),
            False)\
            if dictionary.get("wealthPathProbabilities") is not None\
            else APIHelper.SKIP
        plan_id =\
            dictionary.get("planID")\
            if "planID" in dictionary.keys()\
                else APIHelper.SKIP
        participant_id =\
            dictionary.get("participantID")\
            if "participantID" in dictionary.keys()\
                else APIHelper.SKIP
        source_id =\
            dictionary.get("sourceID")\
            if "sourceID" in dictionary.keys()\
                else APIHelper.SKIP
        use_caps_and_floors =\
            dictionary.get("useCapsAndFloors")\
            if dictionary.get("useCapsAndFloors")\
                else False
        target_portfolio =\
            dictionary.get("targetPortfolio")\
            if "targetPortfolio" in dictionary.keys()\
                else APIHelper.SKIP
        mode =\
            dictionary.get("mode")\
            if "mode" in dictionary.keys()\
                else APIHelper.SKIP
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP
        cashflow = None
        if dictionary.get("cashflow") is not None:
            cashflow = [
                CashFlowDict2.from_dictionary(x)
                    for x in dictionary.get("cashflow")
            ]
        else:
            cashflow = APIHelper.SKIP
        transition_matrix_id =\
            dictionary.get("transitionMatrixID")\
            if dictionary.get("transitionMatrixID")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(is_new_goal_priority,
                   is_new_investment_tenure,
                   is_new_risk_profile,
                   is_new_goal,
                   get_path,
                   reallocation_freq,
                   goal_amount,
                   initial_investment,
                   current_wealth,
                   start_date,
                   end_date,
                   goal_priority,
                   current_portfolio_id,
                   infusions,
                   risk_profile,
                   scenario_type,
                   infusion_type,
                   reallocate,
                   cashflow_date,
                   goal_start_date,
                   curr_date,
                   current_age,
                   retirement_age,
                   risk_override,
                   engaged_participant,
                   required_data_available,
                   wealth_path_probabilities,
                   plan_id,
                   participant_id,
                   source_id,
                   use_caps_and_floors,
                   target_portfolio,
                   mode,
                   policy,
                   cashflow,
                   transition_matrix_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _is_new_goal_priority=self.is_new_goal_priority
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_goal=self.is_new_goal
        _reallocate=(
            self.reallocate
            if hasattr(self, "reallocate")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _get_path=self.get_path
        _reallocation_freq=self.reallocation_freq
        _goal_amount=self.goal_amount
        _initial_investment=self.initial_investment
        _current_wealth=self.current_wealth
        _start_date=self.start_date
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _end_date=self.end_date
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _goal_priority=self.goal_priority
        _current_portfolio_id=self.current_portfolio_id
        _infusions=self.infusions
        _risk_profile=self.risk_profile
        _scenario_type=self.scenario_type
        _infusion_type=self.infusion_type
        _current_age=(
            self.current_age
            if hasattr(self, "current_age")
            else None
        )
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _risk_override=(
            self.risk_override
            if hasattr(self, "risk_override")
            else None
        )
        _engaged_participant=(
            self.engaged_participant
            if hasattr(self, "engaged_participant")
            else None
        )
        _required_data_available=(
            self.required_data_available
            if hasattr(self, "required_data_available")
            else None
        )
        _wealth_path_probabilities=(
            self.wealth_path_probabilities
            if hasattr(self, "wealth_path_probabilities")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _target_portfolio=(
            self.target_portfolio
            if hasattr(self, "target_portfolio")
            else None
        )
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _transition_matrix_id=(
            self.transition_matrix_id
            if hasattr(self, "transition_matrix_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_new_goal_priority={_is_new_goal_priority!r}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!r}, "
            f"is_new_risk_profile={_is_new_risk_profile!r}, "
            f"is_new_goal={_is_new_goal!r}, "
            f"reallocate={_reallocate!r}, "
            f"cashflow_date={_cashflow_date!r}, "
            f"get_path={_get_path!r}, "
            f"reallocation_freq={_reallocation_freq!r}, "
            f"goal_amount={_goal_amount!r}, "
            f"initial_investment={_initial_investment!r}, "
            f"current_wealth={_current_wealth!r}, "
            f"start_date={_start_date!r}, "
            f"goal_start_date={_goal_start_date!r}, "
            f"end_date={_end_date!r}, "
            f"curr_date={_curr_date!r}, "
            f"goal_priority={_goal_priority!r}, "
            f"current_portfolio_id={_current_portfolio_id!r}, "
            f"infusions={_infusions!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"scenario_type={_scenario_type!r}, "
            f"infusion_type={_infusion_type!r}, "
            f"current_age={_current_age!r}, "
            f"retirement_age={_retirement_age!r}, "
            f"risk_override={_risk_override!r}, "
            f"engaged_participant={_engaged_participant!r}, "
            f"required_data_available={_required_data_available!r}, "
            f"wealth_path_probabilities={_wealth_path_probabilities!r}, "
            f"plan_id={_plan_id!r}, "
            f"participant_id={_participant_id!r}, "
            f"source_id={_source_id!r}, "
            f"use_caps_and_floors={_use_caps_and_floors!r}, "
            f"target_portfolio={_target_portfolio!r}, "
            f"mode={_mode!r}, "
            f"policy={_policy!r}, "
            f"cashflow={_cashflow!r}, "
            f"transition_matrix_id={_transition_matrix_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _is_new_goal_priority=self.is_new_goal_priority
        _is_new_investment_tenure=self.is_new_investment_tenure
        _is_new_risk_profile=self.is_new_risk_profile
        _is_new_goal=self.is_new_goal
        _reallocate=(
            self.reallocate
            if hasattr(self, "reallocate")
            else None
        )
        _cashflow_date=(
            self.cashflow_date
            if hasattr(self, "cashflow_date")
            else None
        )
        _get_path=self.get_path
        _reallocation_freq=self.reallocation_freq
        _goal_amount=self.goal_amount
        _initial_investment=self.initial_investment
        _current_wealth=self.current_wealth
        _start_date=self.start_date
        _goal_start_date=(
            self.goal_start_date
            if hasattr(self, "goal_start_date")
            else None
        )
        _end_date=self.end_date
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _goal_priority=self.goal_priority
        _current_portfolio_id=self.current_portfolio_id
        _infusions=self.infusions
        _risk_profile=self.risk_profile
        _scenario_type=self.scenario_type
        _infusion_type=self.infusion_type
        _current_age=(
            self.current_age
            if hasattr(self, "current_age")
            else None
        )
        _retirement_age=(
            self.retirement_age
            if hasattr(self, "retirement_age")
            else None
        )
        _risk_override=(
            self.risk_override
            if hasattr(self, "risk_override")
            else None
        )
        _engaged_participant=(
            self.engaged_participant
            if hasattr(self, "engaged_participant")
            else None
        )
        _required_data_available=(
            self.required_data_available
            if hasattr(self, "required_data_available")
            else None
        )
        _wealth_path_probabilities=(
            self.wealth_path_probabilities
            if hasattr(self, "wealth_path_probabilities")
            else None
        )
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _target_portfolio=(
            self.target_portfolio
            if hasattr(self, "target_portfolio")
            else None
        )
        _mode=(
            self.mode
            if hasattr(self, "mode")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _cashflow=(
            self.cashflow
            if hasattr(self, "cashflow")
            else None
        )
        _transition_matrix_id=(
            self.transition_matrix_id
            if hasattr(self, "transition_matrix_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"is_new_goal_priority={_is_new_goal_priority!s}, "
            f"is_new_investment_tenure={_is_new_investment_tenure!s}, "
            f"is_new_risk_profile={_is_new_risk_profile!s}, "
            f"is_new_goal={_is_new_goal!s}, "
            f"reallocate={_reallocate!s}, "
            f"cashflow_date={_cashflow_date!s}, "
            f"get_path={_get_path!s}, "
            f"reallocation_freq={_reallocation_freq!s}, "
            f"goal_amount={_goal_amount!s}, "
            f"initial_investment={_initial_investment!s}, "
            f"current_wealth={_current_wealth!s}, "
            f"start_date={_start_date!s}, "
            f"goal_start_date={_goal_start_date!s}, "
            f"end_date={_end_date!s}, "
            f"curr_date={_curr_date!s}, "
            f"goal_priority={_goal_priority!s}, "
            f"current_portfolio_id={_current_portfolio_id!s}, "
            f"infusions={_infusions!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"scenario_type={_scenario_type!s}, "
            f"infusion_type={_infusion_type!s}, "
            f"current_age={_current_age!s}, "
            f"retirement_age={_retirement_age!s}, "
            f"risk_override={_risk_override!s}, "
            f"engaged_participant={_engaged_participant!s}, "
            f"required_data_available={_required_data_available!s}, "
            f"wealth_path_probabilities={_wealth_path_probabilities!s}, "
            f"plan_id={_plan_id!s}, "
            f"participant_id={_participant_id!s}, "
            f"source_id={_source_id!s}, "
            f"use_caps_and_floors={_use_caps_and_floors!s}, "
            f"target_portfolio={_target_portfolio!s}, "
            f"mode={_mode!s}, "
            f"policy={_policy!s}, "
            f"cashflow={_cashflow!s}, "
            f"transition_matrix_id={_transition_matrix_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
