"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class TargetPortfolio2(object):
    """Implementation of the 'TargetPortfolio2' model.

    Target portfolio defines the risk profile for AUA accounts in case user wants to
    use custom portfolio mode.

    Attributes:
        mean_return (float): Mean return value for the AUA account, in case user
            wants to use custom portfolio mode.
        standard_deviation (float): Standard deviation for the AUA account, in case
            user wants to use custom portfolio mode.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mean_return": "meanReturn",
        "standard_deviation": "standardDeviation",
    }

    _optionals = [
        "mean_return",
        "standard_deviation",
    ]

    def __init__(
        self,
        mean_return=APIHelper.SKIP,
        standard_deviation=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a TargetPortfolio2 instance."""
        # Initialize members of the class
        if mean_return is not APIHelper.SKIP:
            self.mean_return = mean_return
        if standard_deviation is not APIHelper.SKIP:
            self.standard_deviation = standard_deviation

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mean_return =\
            dictionary.get("meanReturn")\
            if dictionary.get("meanReturn")\
                else APIHelper.SKIP
        standard_deviation =\
            dictionary.get("standardDeviation")\
            if dictionary.get("standardDeviation")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(mean_return,
                   standard_deviation,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mean_return={_mean_return!r}, "
            f"standard_deviation={_standard_deviation!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _mean_return=(
            self.mean_return
            if hasattr(self, "mean_return")
            else None
        )
        _standard_deviation=(
            self.standard_deviation
            if hasattr(self, "standard_deviation")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"mean_return={_mean_return!s}, "
            f"standard_deviation={_standard_deviation!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
