"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class TradeInfo(object):
    """Implementation of the 'TradeInfo' model.

    Attributes:
        direction (str): “S” indicates sale of the asset while “B” indicated purchase
        symbol (str): Identifier associated with an asset class
        cusip (str): Cusip associated with an asset class
        quantity (float): Refers to the amount of sell associated with a trade
        amount (float): Refers to the amount of buy associated with a trade
        phase (str): “Rebalance” refers to trades required to move from one portfolio
            to another.             “Withdrawal” refers to trades needed to withdraw
            a goal amount
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "direction": "direction",
        "symbol": "symbol",
        "cusip": "cusip",
        "quantity": "quantity",
        "amount": "amount",
        "phase": "phase",
    }

    def __init__(
        self,
        direction=None,
        symbol=None,
        cusip=None,
        quantity=None,
        amount=None,
        phase=None,
        additional_properties=None):
        """Initialize a TradeInfo instance."""
        # Initialize members of the class
        self.direction = direction
        self.symbol = symbol
        self.cusip = cusip
        self.quantity = quantity
        self.amount = amount
        self.phase = phase

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        direction =\
            dictionary.get("direction")\
            if dictionary.get("direction")\
                else None
        symbol =\
            dictionary.get("symbol")\
            if dictionary.get("symbol")\
                else None
        cusip =\
            dictionary.get("cusip")\
            if dictionary.get("cusip")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else None
        phase =\
            dictionary.get("phase")\
            if dictionary.get("phase")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(direction,
                   symbol,
                   cusip,
                   quantity,
                   amount,
                   phase,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _direction=self.direction
        _symbol=self.symbol
        _cusip=self.cusip
        _quantity=self.quantity
        _amount=self.amount
        _phase=self.phase
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"direction={_direction!r}, "
            f"symbol={_symbol!r}, "
            f"cusip={_cusip!r}, "
            f"quantity={_quantity!r}, "
            f"amount={_amount!r}, "
            f"phase={_phase!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _direction=self.direction
        _symbol=self.symbol
        _cusip=self.cusip
        _quantity=self.quantity
        _amount=self.amount
        _phase=self.phase
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"direction={_direction!s}, "
            f"symbol={_symbol!s}, "
            f"cusip={_cusip!s}, "
            f"quantity={_quantity!s}, "
            f"amount={_amount!s}, "
            f"phase={_phase!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
