"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.cashflow_recommendation_1 import (
    CashflowRecommendation1,
)


class UpaAnalysisReport1(object):
    """Implementation of the 'UPAAnalysisReport1' model.

    <b>For the Original Plan:</b><br>            GOE’s outputs including probability,
    portfolio advice, etc.

    Attributes:
        current_goal_probability (float): GOE’s estimated probability to achieve the
            goal target wealth.
        recommended_portfolio_id (int): GOE’s current recommended portfolio index.
        meet_goal_priority (bool): Checks if goal probability is more than the target
            probability corresponding to the goal             priority – Target
            probabilities for all goal priorities (Need, Want, Wish and Dream) are
            set in the GOE config.
        is_goal_realistic (bool): To understand if the goal probability is more than
            35% (This is a configurable field).
        one_time_top_up (float): Suggested one-time top-up amount that aims to
            improve the goal probability to meet the target goal probability.
        cashflow_recommendation (CashflowRecommendation1): Cashflow recommendation is
            at the plan level.Note: -               Empty in case plan meets the
            target probability.
        bankruptcy_msg (str): Message flagging an expected bankruptcy (goal running
            out of money) in any year.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "current_goal_probability": "currentGoalProbability",
        "recommended_portfolio_id": "recommendedPortfolioId",
        "meet_goal_priority": "meetGoalPriority",
        "is_goal_realistic": "isGoalRealistic",
        "one_time_top_up": "oneTimeTopUp",
        "cashflow_recommendation": "cashflowRecommendation",
        "bankruptcy_msg": "bankruptcyMsg",
    }

    _nullables = [
        "current_goal_probability",
    ]

    def __init__(
        self,
        current_goal_probability=None,
        recommended_portfolio_id=None,
        meet_goal_priority=None,
        is_goal_realistic=None,
        one_time_top_up=None,
        cashflow_recommendation=None,
        bankruptcy_msg=None,
        additional_properties=None):
        """Initialize a UpaAnalysisReport1 instance."""
        # Initialize members of the class
        self.current_goal_probability = current_goal_probability
        self.recommended_portfolio_id = recommended_portfolio_id
        self.meet_goal_priority = meet_goal_priority
        self.is_goal_realistic = is_goal_realistic
        self.one_time_top_up = one_time_top_up
        self.cashflow_recommendation = cashflow_recommendation
        self.bankruptcy_msg = bankruptcy_msg

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        current_goal_probability =\
            dictionary.get("currentGoalProbability")\
            if dictionary.get("currentGoalProbability")\
                else None
        recommended_portfolio_id =\
            dictionary.get("recommendedPortfolioId")\
            if dictionary.get("recommendedPortfolioId")\
                else None
        meet_goal_priority =\
            dictionary.get("meetGoalPriority")\
            if "meetGoalPriority" in dictionary.keys()\
                else None
        is_goal_realistic =\
            dictionary.get("isGoalRealistic")\
            if "isGoalRealistic" in dictionary.keys()\
                else None
        one_time_top_up =\
            dictionary.get("oneTimeTopUp")\
            if dictionary.get("oneTimeTopUp")\
                else None
        cashflow_recommendation =\
            CashflowRecommendation1.from_dictionary(
                dictionary.get("cashflowRecommendation"))\
                if dictionary.get("cashflowRecommendation") else None
        bankruptcy_msg =\
            dictionary.get("bankruptcyMsg")\
            if dictionary.get("bankruptcyMsg")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(current_goal_probability,
                   recommended_portfolio_id,
                   meet_goal_priority,
                   is_goal_realistic,
                   one_time_top_up,
                   cashflow_recommendation,
                   bankruptcy_msg,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _current_goal_probability=self.current_goal_probability
        _recommended_portfolio_id=self.recommended_portfolio_id
        _meet_goal_priority=self.meet_goal_priority
        _is_goal_realistic=self.is_goal_realistic
        _one_time_top_up=self.one_time_top_up
        _cashflow_recommendation=self.cashflow_recommendation
        _bankruptcy_msg=self.bankruptcy_msg
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"current_goal_probability={_current_goal_probability!r}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!r}, "
            f"meet_goal_priority={_meet_goal_priority!r}, "
            f"is_goal_realistic={_is_goal_realistic!r}, "
            f"one_time_top_up={_one_time_top_up!r}, "
            f"cashflow_recommendation={_cashflow_recommendation!r}, "
            f"bankruptcy_msg={_bankruptcy_msg!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _current_goal_probability=self.current_goal_probability
        _recommended_portfolio_id=self.recommended_portfolio_id
        _meet_goal_priority=self.meet_goal_priority
        _is_goal_realistic=self.is_goal_realistic
        _one_time_top_up=self.one_time_top_up
        _cashflow_recommendation=self.cashflow_recommendation
        _bankruptcy_msg=self.bankruptcy_msg
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"current_goal_probability={_current_goal_probability!s}, "
            f"recommended_portfolio_id={_recommended_portfolio_id!s}, "
            f"meet_goal_priority={_meet_goal_priority!s}, "
            f"is_goal_realistic={_is_goal_realistic!s}, "
            f"one_time_top_up={_one_time_top_up!s}, "
            f"cashflow_recommendation={_cashflow_recommendation!s}, "
            f"bankruptcy_msg={_bankruptcy_msg!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
