"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.goal_response_item import (
    GoalResponseItem,
)


class WealthSplitterOutputModel(object):
    """Implementation of the 'WealthSplitterOutputModel' model.

    Attributes:
        status_code (int): Status code for the response.
        message (str): Returns appropriate message for each status code.
        body (Any): The model property of type Any.
        goal_response_list (List[GoalResponseItem]): Optimal wealth split details for
            all goals
        request_type (str): The model property of type str.
        advice_id (str): Unique identifier for each response. The ID can be used as
            an input in the /api/goe-api/advice-status API request.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status_code": "statusCode",
        "message": "message",
        "body": "body",
        "goal_response_list": "goal_response_list",
        "request_type": "requestType",
        "advice_id": "adviceID",
    }

    def __init__(
        self,
        status_code=None,
        message=None,
        body=None,
        goal_response_list=None,
        request_type=None,
        advice_id=None,
        additional_properties=None):
        """Initialize a WealthSplitterOutputModel instance."""
        # Initialize members of the class
        self.status_code = status_code
        self.message = message
        self.body = body
        self.goal_response_list = goal_response_list
        self.request_type = request_type
        self.advice_id = advice_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status_code =\
            dictionary.get("statusCode")\
            if dictionary.get("statusCode")\
                else None
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None
        body =\
            dictionary.get("body")\
            if dictionary.get("body")\
                else None
        goal_response_list = None
        if dictionary.get("goal_response_list") is not None:
            goal_response_list = [
                GoalResponseItem.from_dictionary(x)
                    for x in dictionary.get("goal_response_list")
            ]
        request_type =\
            dictionary.get("requestType")\
            if dictionary.get("requestType")\
                else None
        advice_id =\
            dictionary.get("adviceID")\
            if dictionary.get("adviceID")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status_code,
                   message,
                   body,
                   goal_response_list,
                   request_type,
                   advice_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _status_code=self.status_code
        _message=self.message
        _body=self.body
        _goal_response_list=self.goal_response_list
        _request_type=self.request_type
        _advice_id=self.advice_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status_code={_status_code!r}, "
            f"message={_message!r}, "
            f"body={_body!r}, "
            f"goal_response_list={_goal_response_list!r}, "
            f"request_type={_request_type!r}, "
            f"advice_id={_advice_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _status_code=self.status_code
        _message=self.message
        _body=self.body
        _goal_response_list=self.goal_response_list
        _request_type=self.request_type
        _advice_id=self.advice_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"status_code={_status_code!s}, "
            f"message={_message!s}, "
            f"body={_body!s}, "
            f"goal_response_list={_goal_response_list!s}, "
            f"request_type={_request_type!s}, "
            f"advice_id={_advice_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
