"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper
from goeapi.models.goal_profile_list_wealth_splitter_model import (
    GoalProfileListWealthSplitterModel,
)
from goeapi.models.policy_details import PolicyDetails


class WealthSplitterInputModel(object):
    """Implementation of the 'WealthSplitterInputModel' model.

    Attributes:
        curr_date (str): This is an optional parameter that can be used to simulate
            the current date to be the specified value.
            GOE will process the request as if you are making the API call on the
            specified date. If not passed, the current system date will be used as
            the current date.
        start_date (str): Defines the start date of goal.Valid input format is date –
            ‘dd-mm-yyyy’
        risk_profile (RiskProfile8): Defines the user’s overall risk profile – does
            not vary by goal for each investor.         On a default basis, GOE is
            configured for three Risk Profile levels, but it can be customized for up
            to five levels.
        goal_profile_list (List[GoalProfileListWealthSplitterModel]): Array
            consisting of goal objects
        plan_id (str): This is an optional identifier for the participants’ plan
            identifier.
        participant_id (str): This is an optional identifier for the participants’
            unique identifier.
        source_id (str): This is an optional identifier for the name of the partner
            initiating the GOE API call.
        use_caps_and_floors (bool): By default, the risk profile of the participant
            is considered while determining the max equity exposure
            available for GOE to optimize. When opted for this feature, the risk
            profile of the participant is ignored and the max equity allocation
            (available for GOE to optimize) is determined using the participant’s
            current age, retirement age and a mapper table determining the maximum
            equity allocation
        transition_matrix_id (str): transitionMatrixID defines the ID of the
            transaction fee matrix that needs to be used for calculating transaction
            fee in the algo if transaction fee is set to true on admin portal.
            When transaction fees = true on admin portal: Yes (Mandatory)
            When transaction fees = false on admin portal: No (Optional, defaults to
            None)                 String key following a startYear_EndYear naming
            convention (e.g., '2025_2026' for inter-year, '2025_2025' or '2026_2026'
            for intra-year).
        policy (List[PolicyDetails]): Contains details about the policy validation
            associated with the Platform Partner. In this example,             the
            array includes participantType and callType, however, the dictionary is
            open and Platform Partners are able to send other fields to define their
            respective API Policy.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "start_date": "start_date",
        "risk_profile": "riskProfile",
        "goal_profile_list": "goal_profile_list",
        "curr_date": "currDate",
        "plan_id": "planID",
        "participant_id": "participantID",
        "source_id": "sourceID",
        "use_caps_and_floors": "useCapsAndFloors",
        "transition_matrix_id": "transitionMatrixID",
        "policy": "policy",
    }

    _optionals = [
        "curr_date",
        "plan_id",
        "participant_id",
        "source_id",
        "use_caps_and_floors",
        "transition_matrix_id",
        "policy",
    ]

    _nullables = [
        "curr_date",
    ]

    def __init__(
        self,
        start_date=None,
        risk_profile=None,
        goal_profile_list=None,
        curr_date=APIHelper.SKIP,
        plan_id=APIHelper.SKIP,
        participant_id=APIHelper.SKIP,
        source_id=APIHelper.SKIP,
        use_caps_and_floors=False,
        transition_matrix_id=APIHelper.SKIP,
        policy=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a WealthSplitterInputModel instance."""
        # Initialize members of the class
        if curr_date is not APIHelper.SKIP:
            self.curr_date = curr_date
        self.start_date = start_date
        self.risk_profile = risk_profile
        self.goal_profile_list = goal_profile_list
        if plan_id is not APIHelper.SKIP:
            self.plan_id = plan_id
        if participant_id is not APIHelper.SKIP:
            self.participant_id = participant_id
        if source_id is not APIHelper.SKIP:
            self.source_id = source_id
        self.use_caps_and_floors = use_caps_and_floors
        if transition_matrix_id is not APIHelper.SKIP:
            self.transition_matrix_id = transition_matrix_id
        if policy is not APIHelper.SKIP:
            self.policy = policy

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        start_date =\
            dictionary.get("start_date")\
            if dictionary.get("start_date")\
                else None
        risk_profile =\
            dictionary.get("riskProfile")\
            if dictionary.get("riskProfile")\
                else None
        goal_profile_list = None
        if dictionary.get("goal_profile_list") is not None:
            goal_profile_list = [
                GoalProfileListWealthSplitterModel.from_dictionary(x)
                    for x in dictionary.get("goal_profile_list")
            ]
        curr_date =\
            dictionary.get("currDate")\
            if "currDate" in dictionary.keys()\
                else APIHelper.SKIP
        plan_id =\
            dictionary.get("planID")\
            if dictionary.get("planID")\
                else APIHelper.SKIP
        participant_id =\
            dictionary.get("participantID")\
            if dictionary.get("participantID")\
                else APIHelper.SKIP
        source_id =\
            dictionary.get("sourceID")\
            if dictionary.get("sourceID")\
                else APIHelper.SKIP
        use_caps_and_floors =\
            dictionary.get("useCapsAndFloors")\
            if dictionary.get("useCapsAndFloors")\
                else False
        transition_matrix_id =\
            dictionary.get("transitionMatrixID")\
            if dictionary.get("transitionMatrixID")\
                else APIHelper.SKIP
        policy = None
        if dictionary.get("policy") is not None:
            policy = [
                PolicyDetails.from_dictionary(x)
                    for x in dictionary.get("policy")
            ]
        else:
            policy = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(start_date,
                   risk_profile,
                   goal_profile_list,
                   curr_date,
                   plan_id,
                   participant_id,
                   source_id,
                   use_caps_and_floors,
                   transition_matrix_id,
                   policy,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _start_date=self.start_date
        _risk_profile=self.risk_profile
        _goal_profile_list=self.goal_profile_list
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _transition_matrix_id=(
            self.transition_matrix_id
            if hasattr(self, "transition_matrix_id")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"curr_date={_curr_date!r}, "
            f"start_date={_start_date!r}, "
            f"risk_profile={_risk_profile!r}, "
            f"goal_profile_list={_goal_profile_list!r}, "
            f"plan_id={_plan_id!r}, "
            f"participant_id={_participant_id!r}, "
            f"source_id={_source_id!r}, "
            f"use_caps_and_floors={_use_caps_and_floors!r}, "
            f"transition_matrix_id={_transition_matrix_id!r}, "
            f"policy={_policy!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _curr_date=(
            self.curr_date
            if hasattr(self, "curr_date")
            else None
        )
        _start_date=self.start_date
        _risk_profile=self.risk_profile
        _goal_profile_list=self.goal_profile_list
        _plan_id=(
            self.plan_id
            if hasattr(self, "plan_id")
            else None
        )
        _participant_id=(
            self.participant_id
            if hasattr(self, "participant_id")
            else None
        )
        _source_id=(
            self.source_id
            if hasattr(self, "source_id")
            else None
        )
        _use_caps_and_floors=(
            self.use_caps_and_floors
            if hasattr(self, "use_caps_and_floors")
            else None
        )
        _transition_matrix_id=(
            self.transition_matrix_id
            if hasattr(self, "transition_matrix_id")
            else None
        )
        _policy=(
            self.policy
            if hasattr(self, "policy")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"curr_date={_curr_date!s}, "
            f"start_date={_start_date!s}, "
            f"risk_profile={_risk_profile!s}, "
            f"goal_profile_list={_goal_profile_list!s}, "
            f"plan_id={_plan_id!s}, "
            f"participant_id={_participant_id!s}, "
            f"source_id={_source_id!s}, "
            f"use_caps_and_floors={_use_caps_and_floors!s}, "
            f"transition_matrix_id={_transition_matrix_id!s}, "
            f"policy={_policy!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
