"""goeapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from goeapi.api_helper import APIHelper


class WealthPath2(object):
    """Implementation of the 'WealthPath2' model.

    Priority based path of wealth across the investment tenure         (corresponding
    to the end of each reallocation date).  If additional wealth paths are
    requested, a dictionary of 3 wealth paths and wealth path percentiles is returned
    – covered in the next 2 rows         The probability levels can be configured.

    Attributes:
        default (List[float]): Wealth paths corresponding to the priority-based
            probability level are returned.
        pessimistic (List[float]): Wealth paths corresponding to the Pessimistic
            probability level are returned
        optimistic (List[float]): Wealth paths corresponding to the Optimistic
            probability level are returned
        default_percentile (str): Percentile values corresponding to default path.
        pessimistic_percentile (str): Percentile values corresponding to Pessimistic
            path.
        optimistic_percentile (str): Percentile values corresponding to Optimistic
            path.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "default": "default",
        "pessimistic": "pessimistic",
        "optimistic": "optimistic",
        "default_percentile": "defaultPercentile",
        "pessimistic_percentile": "pessimisticPercentile",
        "optimistic_percentile": "optimisticPercentile",
    }

    _nullables = [
        "default",
        "pessimistic",
        "optimistic",
        "default_percentile",
        "pessimistic_percentile",
        "optimistic_percentile",
    ]

    def __init__(
        self,
        default=None,
        pessimistic=None,
        optimistic=None,
        default_percentile=None,
        pessimistic_percentile=None,
        optimistic_percentile=None,
        additional_properties=None):
        """Initialize a WealthPath2 instance."""
        # Initialize members of the class
        self.default = default
        self.pessimistic = pessimistic
        self.optimistic = optimistic
        self.default_percentile = default_percentile
        self.pessimistic_percentile = pessimistic_percentile
        self.optimistic_percentile = optimistic_percentile

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        default =\
            dictionary.get("default")\
            if dictionary.get("default")\
                else None
        pessimistic =\
            dictionary.get("pessimistic")\
            if dictionary.get("pessimistic")\
                else None
        optimistic =\
            dictionary.get("optimistic")\
            if dictionary.get("optimistic")\
                else None
        default_percentile =\
            dictionary.get("defaultPercentile")\
            if dictionary.get("defaultPercentile")\
                else None
        pessimistic_percentile =\
            dictionary.get("pessimisticPercentile")\
            if dictionary.get("pessimisticPercentile")\
                else None
        optimistic_percentile =\
            dictionary.get("optimisticPercentile")\
            if dictionary.get("optimisticPercentile")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(default,
                   pessimistic,
                   optimistic,
                   default_percentile,
                   pessimistic_percentile,
                   optimistic_percentile,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _default=self.default
        _pessimistic=self.pessimistic
        _optimistic=self.optimistic
        _default_percentile=self.default_percentile
        _pessimistic_percentile=self.pessimistic_percentile
        _optimistic_percentile=self.optimistic_percentile
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"default={_default!r}, "
            f"pessimistic={_pessimistic!r}, "
            f"optimistic={_optimistic!r}, "
            f"default_percentile={_default_percentile!r}, "
            f"pessimistic_percentile={_pessimistic_percentile!r}, "
            f"optimistic_percentile={_optimistic_percentile!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _default=self.default
        _pessimistic=self.pessimistic
        _optimistic=self.optimistic
        _default_percentile=self.default_percentile
        _pessimistic_percentile=self.pessimistic_percentile
        _optimistic_percentile=self.optimistic_percentile
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"default={_default!s}, "
            f"pessimistic={_pessimistic!s}, "
            f"optimistic={_optimistic!s}, "
            f"default_percentile={_default_percentile!s}, "
            f"pessimistic_percentile={_pessimistic_percentile!s}, "
            f"optimistic_percentile={_optimistic_percentile!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
