
"""
goeapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: E501
from __future__ import annotations

from datetime import date
from typing import (
    Callable,
    ClassVar,
)

from apimatic_core.types.union_types.any_of import (
    AnyOf,
)
from apimatic_core.types.union_types.leaf_type import (
    LeafType,
)
from apimatic_core.types.union_types.union_type_context import (
    UnionTypeContext as Context,
)

from goeapi.models.ews_account_mapping_item import (
    EwsAccountMappingItem,
)


class UnionTypeLookUp:
    """
    Provides lookup and factory methods for predefined union type templates.
    This class stores a mapping of template names to callables that construct
    union type instances. These templates are used to describe compatible
    data shapes by combining primitive or model-based types into a single
    resolved representation at runtime.

    Attributes:
        _templates (dict): A mapping of template names to factory callables
        that create configured union types.

    """

    _templates: ClassVar[dict[str, Callable]] = {
        "CompletelyTradedEntryAdviceId": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "CompletelyTradedEntryDate": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "DraftEntryAdviceId": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "EwsGoalProfileItemAccountMapping": lambda: AnyOf(
            [
                LeafType(EwsAccountMappingItem,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "FinalProposalEntryAdviceId": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "FinalProposalEntryDate": lambda: AnyOf(
            [
                LeafType(date),
                LeafType(date,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "GoalCalculatorInputModelEngagedParticipant": lambda: AnyOf(
            [
                LeafType(bool),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "GoeWithAnnuitiesOutputModelWealthPath": lambda: AnyOf(
            [
                LeafType(float,
                         Context.create(
                             is_array=True,
                         )),
                LeafType(object,
                         Context.create(
                             is_dict=True,
                         )),
            ],
        ),
        "PartiallyTradedEntryAdviceId": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "PartiallyTradedEntryDate": lambda: AnyOf(
            [
                LeafType(date),
                LeafType(date,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "RunPipeInputModelRiskOverride": lambda: AnyOf(
            [
                LeafType(bool),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "RunPipeInputModelEngagedParticipant": lambda: AnyOf(
            [
                LeafType(bool),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "RunPipeInputModelWealthPathProbabilities": lambda: AnyOf(
            [
                LeafType(float,
                         Context.create(
                             is_array=True,
                         )),
            ],
            Context.create(
               is_optional=True,
            ),
        ),
        "TestEntryAdviceId": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
        "TestEntryDate": lambda: AnyOf(
            [
                LeafType(str),
                LeafType(str,
                         Context.create(
                             is_array=True,
                         )),
            ],
        ),
    }

    @staticmethod
    def get(name):
        """
        Retrieve and construct a union type template by name.

        Args:
            name (str): The key identifying the template to resolve.

        Returns:
            Any: A new instance of the union type defined for the given name.

        Raises:
            KeyError: If no template exists for the specified name.

        """
        return UnionTypeLookUp._templates[name]()
